// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Tests() *Tests { // tests (../../../../../:0:0)
	q := r.query.Select("tests")

	return &Tests{
		query: q,
	}
}

type Tests struct { // tests (../../../../../:0:0)
	query *querybuilder.Selection

	all                                              *Void
	appAnnotatesEveryPlatformVariant                 *Void
	appAttachesSbomsAndProvenance                    *Void
	appAttestsTwoSegmentRepositories                 *Void
	appBuildTagsReachTheCompiler                     *Void
	appBuilderRefusesAnInconsistentVariantSet        *Void
	appComposedImageStaysAttested                    *Void
	appComposesAcompleteApplication                  *Void
	appComposesAderivedImage                         *Void
	appComposesAnotherAppsPayload                    *Void
	appContainerRunsTheEntrypoint                    *Void
	appContainersCoverEveryPlatformInOrder           *Void
	appContributionsLandInEveryVariant               *Void
	appCustomizedImageStaysAttested                  *Void
	appCustomizedImageStillNeedsProvenance           *Void
	appDocumentHelpersDescribeContentWithNoEcosystem *Void
	appFromPrebuiltComposesAtreeShapedPayload        *Void
	appFromPrebuiltExecutablesIsHardenedLikeAnyOther *Void
	appFromPrebuiltExecutablesPublishesAttested      *Void
	appImageRunsUnderAnyUser                         *Void
	appImagesCarryTheStandardConfiguration           *Void
	appKeylessSignatureVerifiesAgainstAlocalSigstore *Void
	appPrereleaseMovesNoMovingTags                   *Void
	appPublishLeavesNoTagWhenAttachFails             *Void
	appPublishLeavesNoTagWhenSigningFails            *Void
	appPublishRefusesAnUnusableTarget                *Void
	appPublishReturnsDigestPinnedReferences          *Void
	appPublishesEveryRepositoryNamed                 *Void
	appPublishesTheContainersItReturned              *Void
	appRebuildIsByteIdenticalPerPlatform             *Void
	appRedactsCredentialsFromTheSourceAnnotation     *Void
	appRefusesAdocumentThatDescribesOtherBytes       *Void
	appRefusesContributionsOntoThePath               *Void
	appRefusesContributionsThatCollide               *Void
	appRefusesPlaintextRegistryUnlessInsecure        *Void
	appRefusesToComposeAcrossPlatforms               *Void
	appRefusesToComposeOntoOccupiedPaths             *Void
	appRefusesToPublishApayloadThatCannotRun         *Void
	appRefusesToPublishWithoutProvenanceMachinery    *Void
	appRefusesTreesCarryingSymlinks                  *Void
	appRejectsSourceWithoutGitMetadata               *Void
	appReleaseMovesTheMovingTags                     *Void
	appSbomsDescribeThePublishedImage                *Void
	appSignatureDoesNotVerifyForAnotherKey           *Void
	appSignsEveryPublishedManifest                   *Void
	appStampsEveryPlatformVariant                    *Void
	appValidatesTheVersion                           *Void
	goCiChainsEveryWithMethod                        *Void
	goCiFailsForFailingTest                          *Void
	goCiLintConfigOverridesBundledPolicy             *Void
	goCiPassesForValidSource                         *Void
	goCiRoutesLintVersion                            *Void
	goCiRunsWithRaceByDefault                        *Void
	id                                               *ID
}

func (r *Tests) WithGraphQLQuery(q *querybuilder.Selection) *Tests {
	return &Tests{
		query: q,
	}
}

// TestsAllOpts contains options for Tests.All
type TestsAllOpts struct {
	Parallel int
}

// All runs every z5labs test. parallel caps concurrency; defaults to 0
// (unbounded fan-out — GH Actions schedules each `dagger check` job onto
// its own runner, so in-runner parallelism is bounded by the VM).
func (r *Tests) All(ctx context.Context, opts ...TestsAllOpts) error {
	if r.all != nil {
		return nil
	}
	q := r.query.Select("all")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// AppAnnotatesEveryPlatformVariant asserts that a published image
// carries the standard OCI source annotations, on every platform variant
// and not merely on the index.
//
// Per variant rather than per index because that is what survives a
// consumer: pulling linux/arm64 resolves the variant's own manifest, and
// an annotation that lived only on the manifest list would be invisible
// to everything downstream of that resolution. The values are checked
// against the git state the fixture was built with, so a plausible-but-
// wrong annotation fails.
func (r *Tests) AppAnnotatesEveryPlatformVariant(ctx context.Context) error {
	if r.appAnnotatesEveryPlatformVariant != nil {
		return nil
	}
	q := r.query.Select("appAnnotatesEveryPlatformVariant")

	return q.Execute(ctx)
}

// AppAttachesSbomsAndProvenance asserts that a publish leaves an
// SPDX document, a CycloneDX document and a signed provenance statement
// attached to the digest it returned, each retrievable from the registry
// and told apart by its artifact type.
//
// The provenance is not merely counted: the DSSE envelope is verified
// against the key the publish signed with, the statement's subject is
// checked to be the published digest, and the build identity is checked
// to be the one the token endpoint minted. An attestation nobody
// verifies is a file.
func (r *Tests) AppAttachesSbomsAndProvenance(ctx context.Context) error {
	if r.appAttachesSbomsAndProvenance != nil {
		return nil
	}
	q := r.query.Select("appAttachesSbomsAndProvenance")

	return q.Execute(ctx)
}

// AppAttestsTwoSegmentRepositories asserts a publish whose repository
// carries a "/" still lands all three attestations.
//
// A two-segment repository is not an edge case, it is the only working
// GHCR configuration: GHCR has no single-segment repositories, so
// `ghcr.io/<name>` cannot exist and the owner is part of the repository
// path — folding it into the registry address instead breaks the attach,
// because the oci module keys its credential on that address.
//
// It is checked end to end because the break was not in the push: the
// provenance envelope is written to the module's own filesystem before it
// is attached, and the helper that wrote it treated the name as a single
// path element. That failed only after the image and both SBOMs had
// already been pushed, leaving a published image with no provenance and a
// red build (devex#363). The SBOMs go through Dagger's Directory.withFile
// and were never affected, so they are asserted here too — the point is
// that the whole publish survives the name, not one document of it.
func (r *Tests) AppAttestsTwoSegmentRepositories(ctx context.Context) error {
	if r.appAttestsTwoSegmentRepositories != nil {
		return nil
	}
	q := r.query.Select("appAttestsTwoSegmentRepositories")

	return q.Execute(ctx)
}

// AppBuildTagsReachTheCompiler asserts WithBuild's tags select which files
// compile, rather than being accepted and dropped.
//
// WithBuild recorded tags nothing consumed until App existed, and its doc
// said so; App is what consumes them now, so the assertion has to live here.
// The fixture has two files behind opposite `//go:build` constraints and
// prints which one it was built with, so the binary's own output is the
// evidence — and the run without tags is the control that stops the run with
// them from passing for any other reason.
func (r *Tests) AppBuildTagsReachTheCompiler(ctx context.Context) error {
	if r.appBuildTagsReachTheCompiler != nil {
		return nil
	}
	q := r.query.Select("appBuildTagsReachTheCompiler")

	return q.Execute(ctx)
}

// AppBuilderRefusesAnInconsistentVariantSet asserts the refusals that make an
// App from prebuilt executables trustworthy, through the real API.
//
// The rules themselves are a table in Z5labs.VariantSetSelfTest, which costs
// no build. What cannot be checked in process is that they are wired into
// WithVariant and Build at all — and the empty set especially, because an App
// with no variants is the one that would swallow every contribution made to it
// in silence and publish nothing.
func (r *Tests) AppBuilderRefusesAnInconsistentVariantSet(ctx context.Context) error {
	if r.appBuilderRefusesAnInconsistentVariantSet != nil {
		return nil
	}
	q := r.query.Select("appBuilderRefusesAnInconsistentVariantSet")

	return q.Execute(ctx)
}

// AppComposedImageStaysAttested asserts that a derived image publishes to a
// repository of its own, and that its documents and its provenance describe
// what is actually in it — both sides' payloads, per platform.
//
// The repository is deliberately neither application's binary name. A derived
// image is published as `avroc-gen-go` while the executables inside it are
// called `avroc` and `avroc-gen-go`, so a publish that derived the repository
// from anything in the image would be wrong for exactly the shape this seam
// exists to serve.
//
// The document assertion is the union, and it is what makes composition
// honest: an SBOM that accounted for the base and not the plugin would be
// well-formed, would attach cleanly and would be indistinguishable from a
// complete one. The provenance assertion covers the one fact nothing else
// records — the derived image carries the base's version, so without the
// composed entry in the predicate nothing anywhere says which release of the
// plugin shipped.
func (r *Tests) AppComposedImageStaysAttested(ctx context.Context) error {
	if r.appComposedImageStaysAttested != nil {
		return nil
	}
	q := r.query.Select("appComposedImageStaysAttested")

	return q.Execute(ctx)
}

// AppComposesACompleteApplication asserts that the application being composed
// may be a complete one — an executable plus the tree it needs — and that its
// own contributions come along at their own paths.
//
// This is the half of the design that keeps a composable application
// buildable, testable and publishable the way every other application is,
// rather than a slim carrier that only makes sense once merged. The payload
// fixture is useless without the tree beside it, so running it in the derived
// image is what proves nothing was silently discarded: the entry alone would
// land, run, and fail.
func (r *Tests) AppComposesAcompleteApplication(ctx context.Context) error {
	if r.appComposesAcompleteApplication != nil {
		return nil
	}
	q := r.query.Select("appComposesAcompleteApplication")

	return q.Execute(ctx)
}

// AppComposesADerivedImage asserts that an application that has already been
// composed into may itself be composed, and that the plugins it picked up on
// the way stay runnable.
//
// A derived image is an ordinary App, so composing one is a documented use and
// the payload of the result is the union of both sides'. The failure this test
// exists for is that the union is not uniform: the composed application's own
// entry is declared, while a plugin it picked up earlier travels as an ordinary
// contribution — so a composition that decided what lands executable from the
// declaration alone would carry the earlier plugin across read-only and strip
// the one bit that makes it runnable. That failure is caught at publish, as a
// payload that will not start, which blames the payload rather than the
// composition; so it is caught here, where the mode can be read.
//
// Every executable in the final image is run rather than merely stat'd, and by
// bare name where it is on the PATH. A mode assertion alone would not catch a
// plugin that landed executable and unreachable.
func (r *Tests) AppComposesAderivedImage(ctx context.Context) error {
	if r.appComposesAderivedImage != nil {
		return nil
	}
	q := r.query.Select("appComposesAderivedImage")

	return q.Execute(ctx)
}

// AppComposesAnotherAppsPayload asserts that a composed payload lands in the
// plugin directory of every platform's image, with the module's own mode and
// ownership, and that the derived image is otherwise the base unchanged.
//
// Both halves are the point, and the second is the one this seam exists to
// protect. A derived image that quietly became a *different* program wearing
// the base's filesystem is the failure the whole design refuses, so the
// entrypoint, the environment and the base's own binary are all asserted to
// have survived rather than been restated: a composition that rebuilt the
// image around the plugin would satisfy every assertion about where the plugin
// landed.
//
// Two platforms are built because composing into the host's variant alone
// would be invisible in a single-platform test and would ship an arm64 release
// whose plugin is missing — or, worse, holds an amd64 executable, which is the
// failure devex#397 names.
//
// The plugin is then run two ways on the host's variant: by its absolute path,
// which proves it landed executable, and by its bare name, which proves it is
// on the PATH where a base image's plugin discovery will look for it. The
// second is the whole contract and the first alone would not establish it.
func (r *Tests) AppComposesAnotherAppsPayload(ctx context.Context) error {
	if r.appComposesAnotherAppsPayload != nil {
		return nil
	}
	q := r.query.Select("appComposesAnotherAppsPayload")

	return q.Execute(ctx)
}

// AppContainerRunsTheEntrypoint asserts App.Container produces an image
// whose entrypoint runs the compiled binary.
func (r *Tests) AppContainerRunsTheEntrypoint(ctx context.Context) error {
	if r.appContainerRunsTheEntrypoint != nil {
		return nil
	}
	q := r.query.Select("appContainerRunsTheEntrypoint")

	return q.Execute(ctx)
}

// AppContainersCoverEveryPlatformInOrder asserts Containers returns one
// image per platform in the order the platforms were given, and that
// Container names the same images individually.
//
// Order is asserted because it is the only thing that tells the variants
// apart from the outside: Containers hands back containers and nothing
// else, so a caller matching a platform to an image is matching by index.
// Naming a platform that was not built is an error rather than an empty
// result, because a silently absent variant is a publish that quietly
// ships fewer architectures than it was asked for.
func (r *Tests) AppContainersCoverEveryPlatformInOrder(ctx context.Context) error {
	if r.appContainersCoverEveryPlatformInOrder != nil {
		return nil
	}
	q := r.query.Select("appContainersCoverEveryPlatformInOrder")

	return q.Execute(ctx)
}

// AppContributionsLandInEveryVariant asserts that contributed content reaches
// every platform's image with the module's own mode and owner, and that an app
// nobody contributed to is untouched by the seam existing.
//
// Both halves are the point. Contributing to the host's variant alone would be
// invisible in a single-platform test and would ship an arm64 release missing
// its certificate bundle, so two platforms are built and both are read. And
// the mode and the owner are checked rather than assumed because they are the
// one thing a caller cannot state: the helpers take no permission and no owner
// argument precisely so that every image this pipeline publishes answers those
// two questions the same way, and a helper that passed the supplied content's
// mode through would satisfy every other assertion here.
//
// The metadata is read by mounting each variant's rootfs into an image that
// has a shell, because a scratch image has none. Mounted rather than copied:
// a copy is a second chance for ownership to be rewritten, which is the exact
// property under test.
func (r *Tests) AppContributionsLandInEveryVariant(ctx context.Context) error {
	if r.appContributionsLandInEveryVariant != nil {
		return nil
	}
	q := r.query.Select("appContributionsLandInEveryVariant")

	return q.Execute(ctx)
}

// AppCustomizedImageStaysAttested asserts that an image a caller contributed
// to is attested exactly as one they did not: the documents account for every
// contribution, the provenance still describes what was published, and the
// annotations are still on the variant.
//
// This is the criterion the whole contribution seam turns on. A publish that
// accepted contributed content and attached documents describing only the
// binary would be well formed, would attach cleanly, and would be
// indistinguishable from a complete one — the same undetectable incompleteness
// that moved the documents' subject from the binary to the image in the first
// place. So the assertion is on what a consumer can fetch: the image CONTAINS
// three things, both formats agree on all three, and the envelope over the
// published digest still verifies against the identity that signed it.
func (r *Tests) AppCustomizedImageStaysAttested(ctx context.Context) error {
	if r.appCustomizedImageStaysAttested != nil {
		return nil
	}
	q := r.query.Select("appCustomizedImageStaysAttested")

	return q.Execute(ctx)
}

// AppCustomizedImageStillNeedsProvenance asserts that contributing content is
// not a route to publishing without provenance.
//
// It is a test of its own rather than a line in the refusal test above because
// the two failures it rules out are both plausible and both silent: a helper
// that rebuilt the app object could drop the machinery a caller had already
// supplied, and a publish path that took a different branch for a customized
// image could skip the refusal entirely. An image published without an
// attestation is indistinguishable from one published with, so the registry is
// checked afterwards too — the refusal has to happen before the push, not
// after it.
func (r *Tests) AppCustomizedImageStillNeedsProvenance(ctx context.Context) error {
	if r.appCustomizedImageStillNeedsProvenance != nil {
		return nil
	}
	q := r.query.Select("appCustomizedImageStillNeedsProvenance")

	return q.Execute(ctx)
}

// AppDocumentHelpersDescribeContentWithNoEcosystem asserts that the two
// helpers a caller reaches for when their content has no ecosystem module
// produce a document that says something true about it.
//
// They exist because of a burden argument rather than a capability one:
// SPDX can describe a CA bundle as a package with a checksum and
// NOASSERTION, and always could. What decides whether the documents on a
// published image are worth anything is whether producing one for a
// certificate bundle is a chore — because a caller who finds it one will
// supply whatever satisfies the signature, and a worthless document is worse
// than an absent one, being indistinguishable from a real one.
//
// So this checks the two things that make the helpers not-a-chore: they
// compute the digests themselves, and the only thing they ask for is the one
// thing they cannot know. It also checks that a licence has to be an
// expression, which is the other half of the same argument — a field a
// consumer matches against a policy must not be able to hold prose.
func (r *Tests) AppDocumentHelpersDescribeContentWithNoEcosystem(ctx context.Context) error {
	if r.appDocumentHelpersDescribeContentWithNoEcosystem != nil {
		return nil
	}
	q := r.query.Select("appDocumentHelpersDescribeContentWithNoEcosystem")

	return q.Execute(ctx)
}

// AppFromPrebuiltComposesATreeShapedPayload asserts the payload shape a
// language chain cannot produce: an executable plus the files it needs to run.
//
// This is what devex#410 exists to unblock. The contribution seam was designed
// around payloads that might be a *tree* — an entry and the content beside it
// — and the reason the single-file assumption looked safe for so long is that
// Go was the only chain there was, so every payload was one static binary.
// With the generic constructor the suite can assemble a tree payload and put
// the composition, the collision refusal and the exec check over it, without
// waiting for a second language chain to exist.
//
// The fixture is an executable that is *useless* without the tree: it lists
// what it found and reads a file out of it, so an image where the entry landed
// and the tree did not fails here rather than passing an exec check that only
// proves the binary starts.
func (r *Tests) AppFromPrebuiltComposesAtreeShapedPayload(ctx context.Context) error {
	if r.appFromPrebuiltComposesAtreeShapedPayload != nil {
		return nil
	}
	q := r.query.Select("appFromPrebuiltComposesAtreeShapedPayload")

	return q.Execute(ctx)
}

// AppFromPrebuiltExecutablesIsHardenedLikeAnyOther asserts that an App built
// with no language chain involved produces exactly the image the chain
// produces: the standardized executable directory and PATH, the module's mode
// and ownership on the entry, nothing else in the filesystem, and an
// entrypoint that runs.
//
// The hardening is the whole reason this seam exists rather than being left to
// each project's hand-rolled Dockerfile, so it is asserted rather than assumed.
// A caller-supplied entrypoint is not an exemption from any of it: the module
// still builds the image around the executable, which is exactly what
// distinguishes a bounded seam from the caller-supplied *container* that
// devex#400 refused.
//
// Both platforms are read because packaging only the host's would be invisible
// in a single-platform test and would ship an arm64 release built around an
// amd64 binary — the failure devex#397 names, and the reason no platform here
// is ever inferred from a file.
func (r *Tests) AppFromPrebuiltExecutablesIsHardenedLikeAnyOther(ctx context.Context) error {
	if r.appFromPrebuiltExecutablesIsHardenedLikeAnyOther != nil {
		return nil
	}
	q := r.query.Select("appFromPrebuiltExecutablesIsHardenedLikeAnyOther")

	return q.Execute(ctx)
}

// AppFromPrebuiltExecutablesPublishesAttested asserts that an App assembled
// from prebuilt executables publishes exactly like one a language chain
// produced: both SBOMs and the signed provenance attached to the published
// digest, and the image annotated.
//
// This is the criterion the whole story turns on — "published, annotated and
// attested exactly like one Go.App produced" — and it is checked by reading
// the registry rather than the module, because what a consumer can fetch is
// the only thing that counts.
//
// The annotations are asserted in both directions. The version is present,
// because the caller stated it. The revision, the source and the created time
// are *absent*, because nothing observed them: an App assembled from prebuilt
// bytes read no working tree, and a key present and blank would be
// indistinguishable to a consumer from a revision that really is "". The same
// silence shows up in the predicate, which records no source and no package.
func (r *Tests) AppFromPrebuiltExecutablesPublishesAttested(ctx context.Context) error {
	if r.appFromPrebuiltExecutablesPublishesAttested != nil {
		return nil
	}
	q := r.query.Select("appFromPrebuiltExecutablesPublishesAttested")

	return q.Execute(ctx)
}

// AppImageRunsUnderAnyUser asserts the image's entrypoint is executable by the
// uid the image pins and by any uid a deployment overrides that with.
//
// Executability is the claim, and it is a different one from the pin itself.
// assertStandardImageConfig reads the User field and says what the image
// *declares*; nothing about a declaration says the binary is executable by the
// uid it names. A file owned by 65532 and mode 0500 would satisfy that check
// and fail here, and one at 0550 would satisfy both and fail the moment a
// cluster allocated a uid of its own.
//
// Be clear about what this does not do, because the reverse is easy to assume.
// It does not observe the effective uid of the process — a scratch image has no
// `id` to ask — so three of the four rows below override the user outright and
// would pass just as well against an image that had never set one. The first
// row is what ties this to the pin, and only because it asserts the declared
// user first: a revert of imageForEntry's WithUser makes that assertion fail
// here, rather than leaving the row silently exercising root. Beyond that one
// line, the revert protection for the pin lives in assertStandardImageConfig.
//
// Each row is a deployment somebody really writes:
//
//   - nothing overridden, which is the image running as the 65532 it declares.
//     Before devex#399 this row would have been green for the wrong reason:
//     root can exec anything.
//   - an unrelated uid:gid, which is `docker run --user $(id -u):$(id -g)` and
//     a Kubernetes securityContext naming a uid from a namespace's allocated
//     range. Nothing in the image knows that number, so only a world-executable
//     entrypoint makes it work.
//   - the pinned uid with the runtime's group, which is what a securityContext
//     that sets runAsUser and omits runAsGroup produces. It is a near miss
//     rather than an exotic case: the group is gid 0 there.
//   - root, because a deployment that deliberately overrides back to uid 0 is
//     still a supported configuration of the image even though nothing here
//     ships it.
//
// It runs on the host's platform alone: executability is a property of the file
// modes, which the module writes identically for every variant, and a foreign
// platform's binary cannot be executed here to learn anything more.
func (r *Tests) AppImageRunsUnderAnyUser(ctx context.Context) error {
	if r.appImageRunsUnderAnyUser != nil {
		return nil
	}
	q := r.query.Select("appImageRunsUnderAnyUser")

	return q.Execute(ctx)
}

// AppImagesCarryTheStandardConfiguration asserts every image carries exactly
// the OCI configuration the module promises — the standardized environment,
// the entrypoint, and nothing else — and that the entrypoint does not depend
// on the environment.
//
// Exactly, not at least, and that applies to every field rather than to the
// environment alone: the contract an extension writes against is that the
// image's configuration is knowable, and a stray variable — a credential
// leaked in from a build step, a debug flag — ships silently inside something
// people pull, as would a CMD, a WORKDIR or a label nobody here wrote. The
// plugin directory is asserted to be on the PATH by name because that is the
// promise a `COPY` line is written against, and the entrypoint is asserted to
// be one absolute path in /app because the app must run whatever the PATH
// says: PATH is for what an extension adds, not for finding the app.
//
// Part of the contract is also a claim about the image's filesystem — HOME
// names a directory that is there, TMPDIR one that is not, and /app one the
// application cannot write — and this is the test that checks it, once, on the
// host's platform. See assertHomeAndScratch.
func (r *Tests) AppImagesCarryTheStandardConfiguration(ctx context.Context) error {
	if r.appImagesCarryTheStandardConfiguration != nil {
		return nil
	}
	q := r.query.Select("appImagesCarryTheStandardConfiguration")

	return q.Execute(ctx)
}

// AppKeylessSignatureVerifiesAgainstALocalSigstore drives a publish through
// the keyless branch and verifies it with the command Publish's doc comment
// tells consumers to run: stock `cosign verify` by certificate identity and
// OIDC issuer, with no key anywhere.
//
// # What this is for
//
// Every line of the keyless path was unreachable from the suite before it:
// the certificate request and its proof of possession, the chain split, the
// log upload, and the three annotations that carry a certificate, a chain
// and a bundle. AppSignsEveryPublishedManifest covers the supplied-key mode,
// where none of those exist. So the identity half of the story — a
// certificate identity, an issuer, a log entry — had never been executed
// anywhere but a real release.
//
// # One platform, on purpose
//
// The recursive half — that the index and every per-platform manifest beneath
// it are each signed — is AppSignsEveryPublishedManifest's subject and is
// mode-independent, since signImage walks the same digests whichever signer
// it holds. This test's subject is the identity, so it builds for one
// platform and asserts the annotations of every signature the publish did
// write, whether that is one or two.
//
// # What the local sigstore cannot establish, stated rather than hidden
//
// Three flags below exist only because the sigstore is this session's:
//
//   - --ca-roots and --ca-intermediates, because the leaf chains to a root
//     generated in this process rather than to one in cosign's trust root.
//     This is the same kind of flag as --allow-http-registry: it tells
//     cosign where to look, not what to skip.
//   - --insecure-ignore-sct, because a certificate transparency log is a
//     third service this harness does not stand up, so there is no embedded
//     SCT to check.
//   - --insecure-ignore-tlog, because the bundle is countersigned by a log
//     key nobody trusts. The entry is still round-tripped through a log that
//     verifies the signature against the certificate before answering, and
//     the bundle it returned is asserted below — so what goes unchecked here
//     is a verifier's trust in the log, not the module's encoding of the
//     entry.
//
// None of them weakens what the test is about. The identity and the issuer
// are matched by cosign, from the certificate, exactly as a consumer's
// command would; the last assertion below is that the same command goes red
// when the identity is not the one that signed, which is what makes the
// green one evidence.
func (r *Tests) AppKeylessSignatureVerifiesAgainstAlocalSigstore(ctx context.Context) error {
	if r.appKeylessSignatureVerifiesAgainstAlocalSigstore != nil {
		return nil
	}
	q := r.query.Select("appKeylessSignatureVerifiesAgainstAlocalSigstore")

	return q.Execute(ctx)
}

// AppPrereleaseMovesNoMovingTags asserts a prerelease publishes its own full
// version tag and moves none of the tags a release left behind.
//
// This is the rule that keeps a release candidate from being handed to
// everybody pinning `v1`, and it is only observable against a registry that
// already holds a release: a prerelease published into an empty repository
// leaves `v1` absent whether the rule holds or not, so the assertion would
// pass over a publish that moves every moving tag it can find. So a release
// goes up first, and what is checked is that the three moving tags still
// resolve to *its* digest afterwards.
//
// The two publishes are different bytes by construction — the version is
// stamped into the binary — and that is asserted rather than assumed,
// because two identical digests would make every comparison below hold
// trivially.
func (r *Tests) AppPrereleaseMovesNoMovingTags(ctx context.Context) error {
	if r.appPrereleaseMovesNoMovingTags != nil {
		return nil
	}
	q := r.query.Select("appPrereleaseMovesNoMovingTags")

	return q.Execute(ctx)
}

// AppPublishLeavesNoTagWhenAttachFails asserts that a publish whose attach
// fails leaves nothing a consumer can pull.
//
// This is devex#361's acceptance criterion and it is deliberately not
// "the run goes red". The run went red in devex#360 too; what made that
// failure worth an issue is that the image was tagged and pullable and
// carried no attestations, so nobody resolving the tag could tell a failed
// attach from a registry where nothing is ever attested. Asserting on the exit
// status would have passed against exactly that behaviour, which is why the
// assertions below are all about what the registry holds afterwards.
//
// Two registry states are covered, because a failed publish means different
// things in each:
//
//   - A version nobody has published: nothing may name the digest, so no tag
//     resolves at all and the tag listing is empty.
//   - A version already published: the old tag has to be exactly where it was,
//     still pointing at the release that did attest. A publish that moved the
//     tag first and then failed would have replaced a good release with an
//     unattested one, which is worse than the fresh case rather than milder.
func (r *Tests) AppPublishLeavesNoTagWhenAttachFails(ctx context.Context) error {
	if r.appPublishLeavesNoTagWhenAttachFails != nil {
		return nil
	}
	q := r.query.Select("appPublishLeavesNoTagWhenAttachFails")

	return q.Execute(ctx)
}

// AppPublishLeavesNoTagWhenSigningFails asserts a publish that cannot sign
// leaves no tag a consumer can pull.
//
// This is the half of the story's fifth acceptance criterion that
// AppRefusesToPublishWithoutProvenanceMachinery does not reach. That one
// covers the refusal that fires before the first byte moves, when the
// machinery to sign was never supplied. This one covers the other shape
// entirely: the machinery is present, the image is pushed, every attestation
// lands, and *then* the signature cannot be written. Nothing before this
// exercised that path, and it is the one where "fails rather than publishing
// unsigned" is a claim about ordering rather than about validation.
//
// The stand-in refuses only ".sig" pushes, so the attaches succeed and the
// failure is unambiguously the signature. What is asserted afterwards is the
// same pair as the attach test: no tag resolves, and the manifest really is
// in the registry — because a publish that had simply never pushed would
// satisfy the first half on its own.
func (r *Tests) AppPublishLeavesNoTagWhenSigningFails(ctx context.Context) error {
	if r.appPublishLeavesNoTagWhenSigningFails != nil {
		return nil
	}
	q := r.query.Select("appPublishLeavesNoTagWhenSigningFails")

	return q.Execute(ctx)
}

// AppPublishRefusesAnUnusableTarget asserts the publish refuses a target it
// cannot honour, rather than publishing somewhere the caller did not mean.
//
// Every case here is a refusal that has to happen before any byte moves.
// A repository carrying a registry address is the one that would otherwise
// succeed: "ghcr.io/z5labs/app" appended to "ghcr.io" publishes to
// ghcr.io/ghcr.io/z5labs/app, which the registry accepts and which is
// discovered by somebody failing to pull it.
func (r *Tests) AppPublishRefusesAnUnusableTarget(ctx context.Context) error {
	if r.appPublishRefusesAnUnusableTarget != nil {
		return nil
	}
	q := r.query.Select("appPublishRefusesAnUnusableTarget")

	return q.Execute(ctx)
}

// AppPublishReturnsDigestPinnedReferences asserts a release is published
// under the whole family of tags its version implies, that every one of them
// names one digest, and that Publish reports each as a digest-pinned
// reference.
//
// The family is what lets a consumer pin at the level of risk they want —
// `v2.0.0` never moves, `v2.0` picks up patches, `v2` picks up minor
// releases, `latest` picks up everything — and the guarantee that makes it
// worth anything is that they are one set of bytes rather than four
// publishes that agree. So each tag's digest is read back from the registry
// and compared, rather than the reported references being compared with each
// other: a publish that pushed the image once per tag would satisfy every
// assertion about the reference strings and none of this one.
//
// A tag is a mutable name, so a caller anchoring an attestation, a
// deployment or a release note to a publish has to be handed something
// immutable. The digests here are the registry's own view of what it stored
// rather than a value this pipeline computed, which is what makes it an
// independent check.
//
// The tag listing is checked last, and exactly, per repository: a family with
// a fifth tag in it — one derived from the branch, or a `v2.0.0` also
// published as `stable` — would leave every assertion above true.
//
// What this does not cover is a moving tag actually moving; every tag here is
// created rather than moved, because both repositories are fresh. That is
// AppReleaseMovesTheMovingTags.
func (r *Tests) AppPublishReturnsDigestPinnedReferences(ctx context.Context) error {
	if r.appPublishReturnsDigestPinnedReferences != nil {
		return nil
	}
	q := r.query.Select("appPublishReturnsDigestPinnedReferences")

	return q.Execute(ctx)
}

// AppPublishesEveryRepositoryNamed asserts one manifest list lands per
// repository, under the app's version, with a reference returned for each.
//
// More than one repository in a call is not a curiosity: a release that
// goes to a public registry and to an internal mirror is one build, and
// re-running the build per destination would publish bytes that are only
// probably the same.
//
// The version is deliberately not SemVer, which makes this the check that
// the one-tag-per-publish behaviour survives the tag family: a version this
// module cannot read as SemVer publishes as itself and moves nothing at all.
// That is the high-frequency-install case — no semantic versioning, many
// builds — and this shape is the one the version used to be derived as, so
// what is preserved here is precisely what every caller had before. The
// family is AppPublishReturnsDigestPinnedReferences.
func (r *Tests) AppPublishesEveryRepositoryNamed(ctx context.Context) error {
	if r.appPublishesEveryRepositoryNamed != nil {
		return nil
	}
	q := r.query.Select("appPublishesEveryRepositoryNamed")

	return q.Execute(ctx)
}

// AppPublishesTheContainersItReturned asserts the bytes a publish pushed
// are the bytes Container handed back, and that the published image still
// carries the standardized environment.
//
// This is the check seam. A caller inspecting an image and then publishing
// it is only doing something meaningful if the two are the same artifact;
// App and Container are session-cached precisely so that one chained call
// builds once. The binary is compared by digest rather than by rerunning
// it, and the published variant is pulled back out of the registry so the
// comparison is against what a consumer would get.
//
// What this cannot distinguish on its own is a second build that happened
// to be identical — which is exactly what AppRebuildIsByteIdenticalPerPlatform
// says would happen. The structural half of the guarantee is the caching
// directive; this is the half that can fail.
func (r *Tests) AppPublishesTheContainersItReturned(ctx context.Context) error {
	if r.appPublishesTheContainersItReturned != nil {
		return nil
	}
	q := r.query.Select("appPublishesTheContainersItReturned")

	return q.Execute(ctx)
}

// AppRebuildIsByteIdenticalPerPlatform asserts building one (commit,
// version) pair twice produces byte-identical binaries for every platform.
//
// The two runs build from independently created working trees of the same
// commit, differing by one untracked file so that the engine cannot serve
// the second compile from the first — see pinnedGitFixture, where that is
// the whole reason the file exists. What makes the outputs agree is that
// the stamp and everything else in the link line are functions of the
// commit and the stated version alone: a wall clock, a build host path or a
// nondeterministic link order would show up here as two different digests.
func (r *Tests) AppRebuildIsByteIdenticalPerPlatform(ctx context.Context) error {
	if r.appRebuildIsByteIdenticalPerPlatform != nil {
		return nil
	}
	q := r.query.Select("appRebuildIsByteIdenticalPerPlatform")

	return q.Execute(ctx)
}

// AppRedactsCredentialsFromTheSourceAnnotation asserts a
// credential-bearing origin remote does not travel in the published
// image's source annotation.
//
// This is not hypothetical: `actions/checkout` leaves the origin URL as
// `https://x-access-token:<token>@github.com/org/repo`, and an
// annotation is readable by anyone who can pull the image. So the host
// and path have to survive — the annotation is useless without them —
// while the userinfo must not.
func (r *Tests) AppRedactsCredentialsFromTheSourceAnnotation(ctx context.Context) error {
	if r.appRedactsCredentialsFromTheSourceAnnotation != nil {
		return nil
	}
	q := r.query.Select("appRedactsCredentialsFromTheSourceAnnotation")

	return q.Execute(ctx)
}

// AppRefusesADocumentThatDescribesOtherBytes asserts a publish refuses a
// contribution whose document names some other artifact's digest.
//
// This is the mitigation that makes an asserted document worth having. A
// language chain's document is derived from the artifact and cannot disagree
// with it; everything the generic constructor and the contribution helpers
// accept is a claim someone made, and before this a claim about entirely
// different bytes was well-formed, attached cleanly and indistinguishable from
// a right one. The refusal happens before anything is pushed, which is checked
// by looking for the tag afterwards — a document verified after the push would
// leave a published release to be retracted rather than a publish that failed.
func (r *Tests) AppRefusesAdocumentThatDescribesOtherBytes(ctx context.Context) error {
	if r.appRefusesAdocumentThatDescribesOtherBytes != nil {
		return nil
	}
	q := r.query.Select("appRefusesAdocumentThatDescribesOtherBytes")

	return q.Execute(ctx)
}

// AppRefusesContributionsOntoThePath asserts that the directories the image's
// PATH resolves against are filled by composition and by nothing else.
//
// The image contract has always said that /usr/local/bin is where an
// extension's executables land. Until devex#427 the two halves of the module
// disagreed about what that meant: WithFile lands content 0444, so a binary
// contributed there was not executable and the directory was unusable through
// the seam that names a single file, while WithDirectory lands a tree 0555, so
// wrapping the same binary in a directory worked — and the rule the mode policy
// enforced by omission was bypassed by the shape of the call. Both halves are
// asserted here, in both directions, because the decision is that neither
// helper reaches the directory and the bypass is the one that shipped.
//
// What makes it a rule about paths rather than about modes is the last case: a
// tree contributed at /usr/local is refused without anything reading what is in
// it. Whether it carries a bin/ is a property of the caller's tree rather than
// of the call, and a rule that has to look inside changes its mind between
// builds.
//
// The rule is the whole PATH rather than the plugin directory alone, which is
// the correction this test's last case pins: /usr/local/bin is one of six
// directories the image searches, and a tree at /usr/bin would be discovered by
// bare name exactly as one in the plugin directory would.
//
// The positive half is the point of the negative half and is asserted in the
// same test rather than left to be inferred from a comment: the same base, with
// the same directory, takes a composed application's entry and runs it **by
// bare name**, which is what a base image's plugin discovery does. That is the
// path the contract describes, and it works because composition carries a
// platform on every byte and pairs the variant sets — which is exactly what a
// *dagger.File and a *dagger.Directory cannot do.
func (r *Tests) AppRefusesContributionsOntoThePath(ctx context.Context) error {
	if r.appRefusesContributionsOntoThePath != nil {
		return nil
	}
	q := r.query.Select("appRefusesContributionsOntoThePath")

	return q.Execute(ctx)
}

// AppRefusesContributionsThatCollide asserts the helpers refuse
// content that would land on top of content already in the image.
//
// The failure being refused is not a broken image — it is a *described* image
// that is wrong. Whatever loses the collision is still in the documents the
// publish attaches, so a consumer reads an SBOM naming two things where the
// image holds one, and nothing about the document says which. The entrypoint
// case is the same failure with the application's own binary on the losing
// side, which would also leave the provenance describing a build whose output
// is no longer in the image.
//
// Two of the cases below are not collisions with content — a relative path,
// and a path under the scratch space TMPDIR names — and they are here rather
// than in a test of their own because they are refused by the same call and
// would be just as easy to leave unwired. The scratch-space one is the same
// failure as a collision, with the deployment's mount on the winning side
// instead of another contribution.
//
// The rules themselves are a table in Z5labs.ContributionPathSelfTest, which
// costs no build. What is asserted here is the part that cannot be checked in
// process: that they are wired into both helpers, and that the entrypoint they
// protect is the one the image really runs rather than a path this module
// assumed.
func (r *Tests) AppRefusesContributionsThatCollide(ctx context.Context) error {
	if r.appRefusesContributionsThatCollide != nil {
		return nil
	}
	q := r.query.Select("appRefusesContributionsThatCollide")

	return q.Execute(ctx)
}

// AppRefusesPlaintextRegistryUnlessInsecure asserts TLS verification is not
// inferred from WithRegistryService being set.
//
// The publish path used to disable verification whenever a service was
// present, so a caller who supplied one for their own reasons — a private
// registry that happens to be a Dagger service — silently published over an
// unverified connection they never asked for. Verification is now the
// caller's explicit choice, and with WithInsecure left off a plain-HTTP
// registry is refused rather than accommodated.
func (r *Tests) AppRefusesPlaintextRegistryUnlessInsecure(ctx context.Context) error {
	if r.appRefusesPlaintextRegistryUnlessInsecure != nil {
		return nil
	}
	q := r.query.Select("appRefusesPlaintextRegistryUnlessInsecure")

	return q.Execute(ctx)
}

// AppRefusesToComposeAcrossPlatforms asserts that a platform set which does
// not match exactly is refused, in both directions.
//
// A platform the payload was not built for would publish an index whose
// manifest for that architecture holds an executable for another one: the
// failure arrives at exec time, with the kernel's message, in front of a
// consumer, and nothing in the manifest list says anything is wrong. A
// platform only the payload carries is a variant the caller built and would
// have dropped without a word. Neither can be resolved by picking a side.
func (r *Tests) AppRefusesToComposeAcrossPlatforms(ctx context.Context) error {
	if r.appRefusesToComposeAcrossPlatforms != nil {
		return nil
	}
	q := r.query.Select("appRefusesToComposeAcrossPlatforms")

	return q.Execute(ctx)
}

// AppRefusesToComposeOntoOccupiedPaths asserts that a collision is refused and
// that the refusal names both sides.
//
// Both sides, because a caller told only that a path is taken has to go and
// find out by what. Composing the same plugin twice collides with an
// application composed earlier, and the refusal names it: the image would
// otherwise hold one thing while its documents describe two, which is the
// undetectable incompleteness this whole mechanism exists to prevent.
//
// Contributing a file where a plugin already is used to be the same collision
// arriving through the seam that was there first, and after devex#427 it is
// refused *before* the collision rule is consulted — every composed entry lives
// in the plugin directory, and no contribution may reach any directory on the
// image's PATH whether or not something is already in it. So the second case
// asserts the distinguishing half of that message rather than the path, which
// both refusals name and which would therefore pass whichever rule fired.
//
// That leaves the third case doing what the second used to. A composed
// application's *other* paths are still ordinary contributed paths — a complete
// application brings its own tree at its own path — so a contribution can still
// collide with content a composition brought, and the refusal still has to name
// which application brought it. That branch of the collision rule would
// otherwise have lost its only coverage to the PATH rule taking the case away
// from it.
func (r *Tests) AppRefusesToComposeOntoOccupiedPaths(ctx context.Context) error {
	if r.appRefusesToComposeOntoOccupiedPaths != nil {
		return nil
	}
	q := r.query.Select("appRefusesToComposeOntoOccupiedPaths")

	return q.Execute(ctx)
}

// AppRefusesToPublishAPayloadThatCannotRun asserts that the entry of every
// composed payload is executed in the derived image before the first byte is
// pushed, and that one which cannot start fails the build.
//
// This is the criterion no API shape can establish. Enumerating a payload is
// always a guess — a script's imports, a template opened on the first request,
// a dlopen, a loader that lives in the image the executable came out of — so
// completeness is proven by running it. The fixture here is the crudest
// version of the same failure: bytes that are not an executable at all, which
// come back from the runtime as an exec format error, exactly as an executable
// built for another architecture does.
//
// The refusal has to happen before the push, so the registry is probed
// afterwards: an image published and then reported as broken is one a consumer
// can already have pulled.
func (r *Tests) AppRefusesToPublishApayloadThatCannotRun(ctx context.Context) error {
	if r.appRefusesToPublishApayloadThatCannotRun != nil {
		return nil
	}
	q := r.query.Select("appRefusesToPublishApayloadThatCannotRun")

	return q.Execute(ctx)
}

// AppRefusesToPublishWithoutProvenanceMachinery asserts a publish
// that cannot produce provenance fails, and fails before pushing.
//
// Skipping provenance would be worse than failing: an image published
// without an attestation is indistinguishable from one published with
// until somebody goes looking, so the pipeline that quietly drops it is
// the one nobody notices. The registry is checked afterwards to confirm
// the refusal happened before the push and not after it.
//
// It is the *image signature's* refusal too, and deliberately not a second
// test. One signer signs the provenance envelope and the image, and it is
// resolved once before the first byte moves, so "cannot attest" and "cannot
// sign" are the same failure at the same moment. Splitting them would mean
// two refusals to keep in agreement, and the way they would drift is one of
// them quietly becoming conditional.
func (r *Tests) AppRefusesToPublishWithoutProvenanceMachinery(ctx context.Context) error {
	if r.appRefusesToPublishWithoutProvenanceMachinery != nil {
		return nil
	}
	q := r.query.Select("appRefusesToPublishWithoutProvenanceMachinery")

	return q.Execute(ctx)
}

// AppRefusesTreesCarryingSymlinks asserts that a symbolic link in a
// contributed tree is refused, and measures the two Dagger behaviours the
// decision rests on.
//
// A link is the one kind of content the contribution rules do not see. They
// work on path strings: the mode is set on the copied tree and a mode on a link
// is not a mode on what it resolves to, the overlap rules compare cleaned paths
// and a link names a path they never compare, and the digest that makes an
// asserted document checkable is taken over a list of regular files, which a
// link is not in. So before this, a tree with a link and the same tree without
// one were one tree to every check the module makes, and the link was in the
// image regardless. contribute.go carries the decision; this is the part that
// cannot be checked in process.
//
// The measurements are the reason it has to be a refusal rather than a
// documented caveat, and they are asserted rather than described because both
// are Dagger's behaviour rather than this module's:
//
//   - the copy into an image preserves the link, unchanged and still a link
//     through the normalization the module copies a tree with — so an admitted
//     link really would be in the published image;
//   - Directory.Export preserves it too, which is what the refusal firing at
//     all establishes: the module walks an export, and a walk that saw a
//     regular file there would have described the target's bytes instead. It is
//     driven with an absolute link as well as a relative one, because the
//     absolute case is what rules out the middle answer the issue offered — a
//     link resolving inside the contributed tree — and it would be a silent
//     hole if Dagger ever resolved or dropped those on export.
//
// Both readers of a contributed tree are driven. DirectoryDocument is the paved
// path, where an adopter is refused at the call that would have produced the
// document. The publish is the path a caller who brought a document of their
// own takes, and it is checked with a document that is valid and about another
// tree entirely: the tree is refused as content, before anything is compared,
// so no document could have made it publishable.
func (r *Tests) AppRefusesTreesCarryingSymlinks(ctx context.Context) error {
	if r.appRefusesTreesCarryingSymlinks != nil {
		return nil
	}
	q := r.query.Select("appRefusesTreesCarryingSymlinks")

	return q.Execute(ctx)
}

// AppRejectsSourceWithoutGitMetadata asserts App refuses a source tree
// that is not a git working tree, and says so.
//
// The commit stamp comes from HEAD and from nothing else, so a tree with
// no HEAD cannot be built into an app at all. Failing here rather than
// somewhere inside the compile is what keeps the message about the input
// the caller got wrong instead of about a bare git error.
func (r *Tests) AppRejectsSourceWithoutGitMetadata(ctx context.Context) error {
	if r.appRejectsSourceWithoutGitMetadata != nil {
		return nil
	}
	q := r.query.Select("appRejectsSourceWithoutGitMetadata")

	return q.Execute(ctx)
}

// AppReleaseMovesTheMovingTags asserts the other half of the family: a later
// release takes the moving tags over, and leaves every earlier release's
// immutable tags exactly where they were.
//
// Nothing else in this suite ever watches a moving tag *move*. A fresh
// repository has `v1`, `latest` created rather than moved, and the prerelease
// test asserts only that they stay put — so a re-tag that silently no-opped
// over an existing name, or a registry that refused to overwrite one, would
// leave every other assertion about the family true while consumers pinning
// `v1` sat on the first release forever. That is the whole value proposition
// of the family, and this is the test that can fail when it stops holding.
//
// The two releases differ in their minor version, so `v1.4` and `v1.5` are
// each frozen to their own release while `v1` and `latest` follow the newer
// one. That is the only interesting ordering property the family has: a wider
// tag catching up while a narrower one does not.
func (r *Tests) AppReleaseMovesTheMovingTags(ctx context.Context) error {
	if r.appReleaseMovesTheMovingTags != nil {
		return nil
	}
	q := r.query.Select("appReleaseMovesTheMovingTags")

	return q.Execute(ctx)
}

// AppSbomsDescribeThePublishedImage asserts that the documents on a
// published digest are about **the image**, and that the two formats agree
// about what is in it.
//
// The criterion this covers moved in devex#409. Before it, the documents
// described the binary a language chain compiled — which was complete only
// because a scratch image holding one static binary *is* its binary, and
// stops being true the moment anything else can enter the image. Three
// things are checked here and none of them could pass under the old shape:
//
//   - the subject is the published digest, so a consumer who pulled
//     `<repo>@<digest>` can tell the document is about the bytes they have
//     rather than about some artifact they cannot see;
//   - the image is a package that CONTAINS what was contributed to it, so
//     attribution survives the assembly that replaced the per-contribution
//     documents;
//   - the SPDX and the CycloneDX list the same components, over a real
//     publish rather than over synthesized input.
//
// It reads the documents back off the registry rather than off the module,
// because what a consumer can check is the only thing that counts: an
// assembly that is right and an attach that pushed something else are the
// same failure from outside.
//
// The multi-source case — an image with contributions from more than one
// place — is AppCustomizedImageStaysAttested, which publishes an image a
// caller contributed a file and a directory to and reads the same documents
// back. The de-duplication and merge rules underneath both are driven directly
// by Z5labs.ImageSbomSelfTest, which says why they are not a publish per case.
func (r *Tests) AppSbomsDescribeThePublishedImage(ctx context.Context) error {
	if r.appSbomsDescribeThePublishedImage != nil {
		return nil
	}
	q := r.query.Select("appSbomsDescribeThePublishedImage")

	return q.Execute(ctx)
}

// AppSignatureDoesNotVerifyForAnotherKey asserts `cosign verify` fails when
// the key it is given is not the one that signed.
//
// Without it every assertion in AppSignsEveryPublishedManifest could be
// satisfied by a cosign invocation that checks nothing — a wrong flag, a
// missing digest, a verifier that resolves nothing and reports success. A
// green verification is only evidence if the same command goes red when the
// signature does not belong to the key.
func (r *Tests) AppSignatureDoesNotVerifyForAnotherKey(ctx context.Context) error {
	if r.appSignatureDoesNotVerifyForAnotherKey != nil {
		return nil
	}
	q := r.query.Select("appSignatureDoesNotVerifyForAnotherKey")

	return q.Execute(ctx)
}

// AppSignsEveryPublishedManifest asserts that stock `cosign verify` passes
// against the published tag and against every per-platform manifest
// beneath it.
//
// Both halves matter and the second is the one that is easy to lose. A
// consumer verifies the tag, which resolves to the manifest list; their
// runtime then pulls the per-platform manifest for its architecture, a
// different digest the index signature says nothing about. Signing the
// index alone would leave this test's first assertion passing and its
// second failing — a verification reporting success over bytes it never
// checked, which is worse than no signature at all.
//
// It runs in the supplied-key mode, which is a division of labour rather
// than a limitation: the certificate, the identity and the transparency log
// entry are AppKeylessSignatureVerifiesAgainstALocalSigstore's subject, and
// the recursion is this one's. What each covers is the half the other cannot
// see cheaply — signImage walks the same digests whichever signer it holds,
// so the recursive property is mode-independent and is asserted once, over
// the mode that needs no CA standing behind it.
//
// What it covers is the payload, the signature over it, the annotations, the
// manifest shape and the tag cosign computes to find them, all of it read by
// cosign rather than asserted against this module's own idea of the layout.
func (r *Tests) AppSignsEveryPublishedManifest(ctx context.Context) error {
	if r.appSignsEveryPublishedManifest != nil {
		return nil
	}
	q := r.query.Select("appSignsEveryPublishedManifest")

	return q.Execute(ctx)
}

// AppStampsEveryPlatformVariant asserts a multi-platform build stamps
// every variant with the caller's version and the commit read from HEAD.
//
// A publish collapses the per-platform images into a single manifest list,
// so a stamp applied at the image or publish layer would land on an
// artifact whose variants have already been merged; only a stamp applied in
// the per-variant compile reaches them all. Each variant is therefore
// checked individually: the one matching the engine's architecture is
// executed, and the foreign one — which cannot be executed here — is
// searched for the stamped bytes.
func (r *Tests) AppStampsEveryPlatformVariant(ctx context.Context) error {
	if r.appStampsEveryPlatformVariant != nil {
		return nil
	}
	q := r.query.Select("appStampsEveryPlatformVariant")

	return q.Execute(ctx)
}

// AppValidatesTheVersion asserts the version a caller states is checked
// against the OCI tag charset, as a table rather than only by releasing.
//
// A table is the point. The version used to be derived from HEAD and
// sanitized — any character outside the charset became "-" — which is the
// right trade for a value the pipeline invented and the wrong one for a
// value the caller states, because two versions that differ only outside
// the charset would sanitize to one tag and the second publish would
// silently replace the first. There is no way to observe that from a
// release: both publishes succeed. So the rule is asserted directly, on
// every shape of input that distinguishes it, including the accepting
// cases — a validator that refused everything would pass a table of
// refusals alone.
//
// The build is never evaluated here. Validation happens before App reads
// anything, so a refused version costs one call and no compile, and an
// accepted one costs the git read the fixture has already paid for.
func (r *Tests) AppValidatesTheVersion(ctx context.Context) error {
	if r.appValidatesTheVersion != nil {
		return nil
	}
	q := r.query.Select("appValidatesTheVersion")

	return q.Execute(ctx)
}

// GoCiChainsEveryWithMethod asserts each With* method returns a chain the
// next call can be made on, and that a fully configured chain still runs.
//
// WithBuild's tags reach App rather than Ci, so what is asserted here is
// that supplying them neither errors nor disturbs the checks. That they
// reach the compiler is AppBuildTagsReachTheCompiler.
func (r *Tests) GoCiChainsEveryWithMethod(ctx context.Context) error {
	if r.goCiChainsEveryWithMethod != nil {
		return nil
	}
	q := r.query.Select("goCiChainsEveryWithMethod")

	return q.Execute(ctx)
}

// GoCiFailsForFailingTest asserts that Go.Ci surfaces a test failure as an
// error containing "FAIL" or "exit code: 1".
//
// The test stage is not opt-in — this calls Ci with no With* configuration
// at all — so a library whose tests fail cannot pass the check by simply
// not asking for tests.
func (r *Tests) GoCiFailsForFailingTest(ctx context.Context) error {
	if r.goCiFailsForFailingTest != nil {
		return nil
	}
	q := r.query.Select("goCiFailsForFailingTest")

	return q.Execute(ctx)
}

// GoCiLintConfigOverridesBundledPolicy asserts WithLint's config replaces
// the bundled configs/golangci.yml rather than being accepted and dropped.
//
// The supplied file is a well-formed v2 config enabling a linter that does
// not exist, which golangci-lint refuses to start with. The same fixture
// passes under the bundled policy — that is GoCiPassesForValidSource — so a
// failure here can only come from the caller's file having reached the
// stage.
//
// The assertion is on golangci-lint's exit code rather than on its message
// because the message does not survive the module boundary: a failing
// WithExec inside a dependency arrives as `exit code: N` and nothing else,
// with the command's output visible only in the trace. Exit 3 is
// golangci-lint's general failure code as opposed to 1 for issues it
// found, so what it rules out is the stage merely reporting lint findings;
// it is not specific to configuration. The evidence that the caller's file
// is what reached the stage is the differential above — this fixture
// passes under the bundled policy — and the exit code only pins the
// failure to the lint stage rather than to fmt, vet or test.
func (r *Tests) GoCiLintConfigOverridesBundledPolicy(ctx context.Context) error {
	if r.goCiLintConfigOverridesBundledPolicy != nil {
		return nil
	}
	q := r.query.Select("goCiLintConfigOverridesBundledPolicy")

	return q.Execute(ctx)
}

// GoCiPassesForValidSource asserts that Go.Ci against a clean, vet-clean,
// gofmt-clean library fixture returns no error.
//
// This is also what proves the bundled configs/golangci.yml and the
// pinned golangci-lint speak the same dialect. The two majors reject each
// other's config files outright, so a v1 config reaching a v2 binary — or
// the reverse — fails this test before any linter runs.
func (r *Tests) GoCiPassesForValidSource(ctx context.Context) error {
	if r.goCiPassesForValidSource != nil {
		return nil
	}
	q := r.query.Select("goCiPassesForValidSource")

	return q.Execute(ctx)
}

// GoCiRoutesLintVersion asserts WithLint's version reaches the lint stage
// rather than being accepted and dropped.
//
// It pins a version the `go` module refuses to read a major out of, so the
// assertion is a message naming that version — which can only have come
// from the lint stage. Proving routing this way costs no container work,
// and a pin that *is* valid is exercised where the behaviour lives, in the
// `go` module's own suite.
func (r *Tests) GoCiRoutesLintVersion(ctx context.Context) error {
	if r.goCiRoutesLintVersion != nil {
		return nil
	}
	q := r.query.Select("goCiRoutesLintVersion")

	return q.Execute(ctx)
}

// GoCiRunsWithRaceByDefault asserts the test stage runs with the race
// detector unless a caller says otherwise, and that WithTest(false) is
// what says otherwise.
//
// The fixture's test passes under `go test` and fails under `go test
// -race`, so the two halves of this assertion cannot both hold unless the
// default really is on and the flag really reaches the stage. Asserting
// the default this way is what keeps it a property of the chain rather
// than of whoever constructed it: a GoChain built without the detector set
// would pass every other test in this suite.
func (r *Tests) GoCiRunsWithRaceByDefault(ctx context.Context) error {
	if r.goCiRunsWithRaceByDefault != nil {
		return nil
	}
	q := r.query.Select("goCiRunsWithRaceByDefault")

	return q.Execute(ctx)
}

// A unique identifier for this Tests.
func (r *Tests) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Tests) XXX_GraphQLType() string {
	return "Tests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Tests) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Tests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Tests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Tests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Tests{query: selectNode(dag.query, id, "Tests")}
	return nil
}
