// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Tesseract
func (r *Binding) AsTesseract() *Tesseract { // tesseract (../../../../../daggerverse/tesseract/main.go:93:6)
	q := r.query.Select("asTesseract")

	return &Tesseract{
		query: q,
	}
}

// Retrieve the binding value, as type TesseractDocument
func (r *Binding) AsTesseractDocument() *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:20:6)
	q := r.query.Select("asTesseractDocument")

	return &TesseractDocument{
		query: q,
	}
}

// Create or update a binding of type TesseractDocument in the environment
func (r *Env) WithTesseractDocumentInput(name string, value *TesseractDocument, description string) *Env { // tesseract (../../../../../daggerverse/tesseract/document.go:20:6)
	assertNotNil("value", value)
	q := r.query.Select("withTesseractDocumentInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired TesseractDocument output to be assigned in the environment
func (r *Env) WithTesseractDocumentOutput(name string, description string) *Env { // tesseract (../../../../../daggerverse/tesseract/document.go:20:6)
	q := r.query.Select("withTesseractDocumentOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Tesseract in the environment
func (r *Env) WithTesseractInput(name string, value *Tesseract, description string) *Env { // tesseract (../../../../../daggerverse/tesseract/main.go:93:6)
	assertNotNil("value", value)
	q := r.query.Select("withTesseractInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Tesseract output to be assigned in the environment
func (r *Env) WithTesseractOutput(name string, description string) *Env { // tesseract (../../../../../daggerverse/tesseract/main.go:93:6)
	q := r.query.Select("withTesseractOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// TesseractOpts contains options for Query.Tesseract
type TesseractOpts struct {
	//
	// Container registry hosting the alpine image.
	//
	//
	// Default: "docker.io"
	Registry string // tesseract (../../../../../daggerverse/tesseract/main.go:109:2)
	//
	// Tag of the alpine image the toolchain is assembled on.
	//
	//
	// Default: "3.24"
	AlpineTag string // tesseract (../../../../../daggerverse/tesseract/main.go:112:2)
	//
	// Language codes to install, one apk package each. Empty installs "eng".
	// "osd" is not a recognition language but is required by Document.Osd.
	//
	Languages []string // tesseract (../../../../../daggerverse/tesseract/main.go:116:2)
	//
	// Upper bound on the OpenMP threads tesseract may use, set on the
	// assembled image as OMP_THREAD_LIMIT. Unset, tesseract uses one thread
	// per available CPU, which is what a caller who owns the machine wants.
	// Set it when several recognitions share the cores — concurrent passes
	// each claiming every CPU oversubscribe the box badly enough to cost an
	// order of magnitude, which is the shape of the long-standing upstream
	// slowdown reports (tesseract-ocr/tesseract#2611, #1171, #263). One
	// thread per pass is the usual setting there.
	//
	OmpThreadLimit int // tesseract (../../../../../daggerverse/tesseract/main.go:126:2)
}

// New returns a Tesseract module backed by <registry>/library/alpine:<tag>
// with tesseract-ocr and one language package per requested language.
func (r *Query) Tesseract(opts ...TesseractOpts) *Tesseract { // tesseract (../../../../../daggerverse/tesseract/main.go:106:1)
	q := r.query.Select("tesseract")
	for i := len(opts) - 1; i >= 0; i-- {
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `alpineTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].AlpineTag) {
			q = q.Arg("alpineTag", opts[i].AlpineTag)
		}
		// `languages` optional argument
		if !querybuilder.IsZeroValue(opts[i].Languages) {
			q = q.Arg("languages", opts[i].Languages)
		}
		// `ompThreadLimit` optional argument
		if !querybuilder.IsZeroValue(opts[i].OmpThreadLimit) {
			q = q.Arg("ompThreadLimit", opts[i].OmpThreadLimit)
		}
	}

	return &Tesseract{
		query: q,
	}
}

// Tesseract is the root namespace for every exported function in this module.
// It carries the image coordinates and the language set the image is built
// with; Document hangs off it so the generated SDK surfaces recognition under
// `dag.Tesseract().Document(...)`.
type Tesseract struct { // tesseract (../../../../../daggerverse/tesseract/main.go:93:6)
	query *querybuilder.Selection

	id         *ID
	parameters *string
	version    *string
}

func (r *Tesseract) WithGraphQLQuery(q *querybuilder.Selection) *Tesseract {
	return &Tesseract{
		query: q,
	}
}

// Container returns the assembled toolchain image. This is the escape hatch
// for everything this module does not wrap — the training binaries the apk
// package ships, `combine_tessdata`, and tesseract's long tail of renderers
// stay reachable via `container with-exec`.
//
// A requested OpenMP bound lives here rather than on the recognition
// invocation so everything reached through this escape hatch inherits it too.
func (r *Tesseract) Container() *Container { // tesseract (../../../../../daggerverse/tesseract/main.go:156:1)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// Document binds one image to the toolchain.
//
// The boundary input is a *dagger.File rather than a *dagger.Directory, unlike
// the kicad module's Project: tesseract resolves nothing relative to its input,
// so one image — including a multi-page TIFF — is the whole unit of work.
func (r *Tesseract) Document(source *File) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/main.go:225:1)
	assertNotNil("source", source)
	q := r.query.Select("document")
	q = q.Arg("source", source)

	return &TesseractDocument{
		query: q,
	}
}

// A unique identifier for this Tesseract.
func (r *Tesseract) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Tesseract) XXX_GraphQLType() string {
	return "Tesseract"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Tesseract) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Tesseract) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Tesseract) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Tesseract) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Tesseract{query: selectNode(dag.query, id, "Tesseract")}
	return nil
}

// Langs returns the language codes installed in the image, as reported by
// `tesseract --list-langs`. This is the set Document.WithLanguage validates
// against, and it includes "osd" when that package was requested.
func (r *Tesseract) Langs(ctx context.Context) ([]string, error) { // tesseract (../../../../../daggerverse/tesseract/main.go:195:1)
	q := r.query.Select("langs")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Parameters returns tesseract's control-variable table — every name, its
// default value and a one-line description — as `tesseract --print-parameters`
// prints it. These are the names Document.WithParameter accepts.
func (r *Tesseract) Parameters(ctx context.Context) (string, error) { // tesseract (../../../../../daggerverse/tesseract/main.go:210:1)
	if r.parameters != nil {
		return *r.parameters, nil
	}
	q := r.query.Select("parameters")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Version returns the tesseract release the assembled image ships, as the
// bare version number reported by `tesseract --version`.
func (r *Tesseract) Version(ctx context.Context) (string, error) { // tesseract (../../../../../daggerverse/tesseract/main.go:177:1)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Tesseract as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Tesseract) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Document is one image plus the recognition options that apply to it. It is
// immutable: every With* returns a copy, so a configured Document can be
// branched into several outputs without the branches interfering.
//
// Options are validated at output time rather than in the builders, because a
// builder has no error return and some checks (is this language installed? is
// this a real control variable?) need the image itself to answer.
type TesseractDocument struct { // tesseract (../../../../../daggerverse/tesseract/document.go:20:6)
	query *querybuilder.Selection

	id   *ID
	osd  *string
	text *string
}
type WithTesseractDocumentFunc func(r *TesseractDocument) *TesseractDocument

// With calls the provided function with current TesseractDocument.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *TesseractDocument) With(f WithTesseractDocumentFunc) *TesseractDocument {
	return f(r)
}

func (r *TesseractDocument) WithGraphQLQuery(q *querybuilder.Selection) *TesseractDocument {
	return &TesseractDocument{
		query: q,
	}
}

// Alto returns ALTO XML, the layout schema libraries and archives ingest.
func (r *TesseractDocument) Alto() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:147:1)
	q := r.query.Select("alto")

	return &File{
		query: q,
	}
}

// Export runs one recognition pass and returns a directory holding every
// requested format.
//
// It exists alongside the single-artifact functions because tesseract accepts
// several renderers per invocation: asking for text, hOCR and PDF together is
// one pass over the image, not three. Each artifact is named `result` plus the
// renderer's own extension.
func (r *TesseractDocument) Export(formats []TesseractFormat) *Directory { // tesseract (../../../../../daggerverse/tesseract/document.go:176:1)
	q := r.query.Select("export")
	q = q.Arg("formats", formats)

	return &Directory{
		query: q,
	}
}

// Hocr returns hOCR: HTML in which every recognised word carries its bounding
// box and confidence, which is what layout-aware post-processing reads.
func (r *TesseractDocument) Hocr() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:142:1)
	q := r.query.Select("hocr")

	return &File{
		query: q,
	}
}

// A unique identifier for this TesseractDocument.
func (r *TesseractDocument) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *TesseractDocument) XXX_GraphQLType() string {
	return "TesseractDocument"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *TesseractDocument) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *TesseractDocument) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *TesseractDocument) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *TesseractDocument) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = TesseractDocument{query: selectNode(dag.query, id, "TesseractDocument")}
	return nil
}

// Osd detects the document's orientation and script without recognising any
// text (`--psm 0`), reporting the rotation needed to make the page upright.
//
// It builds its own invocation rather than reusing the document's recognition
// options: orientation detection runs off the osd model alone, so the selected
// language, engine and page-segmentation mode have nothing to say about it.
// The `osd` package must be in the language set New was given.
func (r *TesseractDocument) Osd(ctx context.Context) (string, error) { // tesseract (../../../../../daggerverse/tesseract/document.go:199:1)
	if r.osd != nil {
		return *r.osd, nil
	}
	q := r.query.Select("osd")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Page returns PAGE XML, the PRImA layout-analysis schema — the alternative to
// ALTO for tools built around that ecosystem.
func (r *TesseractDocument) Page() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:165:1)
	q := r.query.Select("page")

	return &File{
		query: q,
	}
}

// Pdf returns a searchable PDF: the source image with an invisible text layer
// positioned behind it, so the page looks untouched but selects and greps.
func (r *TesseractDocument) Pdf() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:159:1)
	q := r.query.Select("pdf")

	return &File{
		query: q,
	}
}

// Text recognises the document and returns the plain text directly, by asking
// tesseract to write to stdout instead of a file. This is the shortest path
// for the common case; Txt is the same content as a *dagger.File.
func (r *TesseractDocument) Text(ctx context.Context) (string, error) { // tesseract (../../../../../daggerverse/tesseract/document.go:121:1)
	if r.text != nil {
		return *r.text, nil
	}
	q := r.query.Select("text")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Tsv returns tab-separated recognition results: one row per layout element,
// descending from page to word, each with its box and confidence.
func (r *TesseractDocument) Tsv() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:153:1)
	q := r.query.Select("tsv")

	return &File{
		query: q,
	}
}

// Txt recognises the document and returns the plain text as a file. It is the
// same content Text returns; take this when the next step wants a file rather
// than a string.
func (r *TesseractDocument) Txt() *File { // tesseract (../../../../../daggerverse/tesseract/document.go:136:1)
	q := r.query.Select("txt")

	return &File{
		query: q,
	}
}

// WithDpi declares the source image's resolution (`--dpi`), which tesseract
// otherwise guesses from the image metadata. Guessing wrong hurts recognition
// on images that carry no resolution at all. A non-positive value is rejected
// at output time.
func (r *TesseractDocument) WithDpi(dpi int) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:80:1)
	q := r.query.Select("withDpi")
	q = q.Arg("dpi", dpi)

	return &TesseractDocument{
		query: q,
	}
}

// WithEngine selects the OCR engine (`--oem`). Unset, tesseract picks based on
// what the language data provides.
func (r *TesseractDocument) WithEngine(mode TesseractEngineMode) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:70:1)
	q := r.query.Select("withEngine")
	q = q.Arg("mode", mode)

	return &TesseractDocument{
		query: q,
	}
}

// WithLanguage selects the recognition language (`-l`). Several languages can
// be combined with `+`, as in "eng+deu", in which case tesseract loads all of
// them for one pass.
//
// The value picks from what New installed; it cannot add a language, because
// each one is a separate apk package baked into the image. An unknown value is
// rejected at output time with the installed set listed. Unset, recognition
// runs in the first installed language.
func (r *TesseractDocument) WithLanguage(lang string) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:53:1)
	q := r.query.Select("withLanguage")
	q = q.Arg("lang", lang)

	return &TesseractDocument{
		query: q,
	}
}

// WithPageSegmentation sets how much layout analysis precedes recognition
// (`--psm`). Unset, tesseract uses fully automatic segmentation without
// orientation detection.
func (r *TesseractDocument) WithPageSegmentation(mode TesseractPageSegMode) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:62:1)
	q := r.query.Select("withPageSegmentation")
	q = q.Arg("mode", mode)

	return &TesseractDocument{
		query: q,
	}
}

// WithParameter sets one of tesseract's control variables (`-c name=value`);
// Parameters lists every name and its default.
//
// It takes a name and a value separately rather than a map because Dagger
// functions cannot accept map parameters. An unknown name is rejected at
// output time: tesseract itself only warns and carries on, so a typo would
// otherwise silently do nothing.
func (r *TesseractDocument) WithParameter(name string, value string) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:94:1)
	q := r.query.Select("withParameter")
	q = q.Arg("name", name)
	q = q.Arg("value", value)

	return &TesseractDocument{
		query: q,
	}
}

// WithUserPatterns supplies a pattern list (`--user-patterns`): one pattern
// per line describing the shape of expected strings, such as part numbers.
func (r *TesseractDocument) WithUserPatterns(patterns *File) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:112:1)
	assertNotNil("patterns", patterns)
	q := r.query.Select("withUserPatterns")
	q = q.Arg("patterns", patterns)

	return &TesseractDocument{
		query: q,
	}
}

// WithUserWords supplies a word list (`--user-words`): one word per line,
// which recognition then favours. Useful for jargon and proper nouns the
// packaged dictionary does not know.
func (r *TesseractDocument) WithUserWords(words *File) *TesseractDocument { // tesseract (../../../../../daggerverse/tesseract/document.go:104:1)
	assertNotNil("words", words)
	q := r.query.Select("withUserWords")
	q = q.Arg("words", words)

	return &TesseractDocument{
		query: q,
	}
}

// AsNode returns this TesseractDocument as a Node.
// This is a local type conversion — no GraphQL call.
func (r *TesseractDocument) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// EngineMode is the OCR engine tesseract recognises with (`--oem`).
//
// All four modes are usable here because Alpine packages the *combined*
// tesseract-ocr/tessdata models, which carry legacy data alongside LSTM. A
// build against tessdata_fast or tessdata_best would leave LEGACY and
// LEGACY_LSTM failing at runtime.
type TesseractEngineMode string // tesseract (../../../../../daggerverse/tesseract/enums.go:86:6)

func (TesseractEngineMode) IsEnum() {}

func (v TesseractEngineMode) Name() string {
	switch v {
	case TesseractEngineModeDefault:
		return "DEFAULT"
	case TesseractEngineModeLegacy:
		return "LEGACY"
	case TesseractEngineModeLegacyLstm:
		return "LEGACY_LSTM"
	case TesseractEngineModeLstm:
		return "LSTM"
	default:
		return ""
	}
}

func (v TesseractEngineMode) Value() string {
	return string(v)
}

func (v *TesseractEngineMode) MarshalJSON() ([]byte, error) {
	if *v == "" {
		return []byte(`""`), nil
	}
	name := v.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", *v)
	}
	return json.Marshal(name)
}

func (v *TesseractEngineMode) UnmarshalJSON(dt []byte) error {
	var s string
	if err := json.Unmarshal(dt, &s); err != nil {
		return err
	}
	switch s {
	case "":
		*v = ""
	case "DEFAULT":
		*v = TesseractEngineModeDefault
	case "LEGACY":
		*v = TesseractEngineModeLegacy
	case "LEGACY_LSTM":
		*v = TesseractEngineModeLegacyLstm
	case "LSTM":
		*v = TesseractEngineModeLstm
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

const (
	// EngineModeDefault lets tesseract pick based on what the language data
	// provides, and is what an unset `--oem` gets.
	TesseractEngineModeDefault TesseractEngineMode = "DEFAULT" // tesseract (../../../../../daggerverse/tesseract/enums.go:97:2)

	// EngineModeLegacy uses the pre-4.0 pattern-matching engine only.
	TesseractEngineModeLegacy TesseractEngineMode = "LEGACY" // tesseract (../../../../../daggerverse/tesseract/enums.go:90:2)

	// EngineModeLegacyLstm runs both engines and combines their results.
	TesseractEngineModeLegacyLstm TesseractEngineMode = "LEGACY_LSTM" // tesseract (../../../../../daggerverse/tesseract/enums.go:94:2)

	// EngineModeLstm uses the LSTM neural-network engine only.
	TesseractEngineModeLstm TesseractEngineMode = "LSTM" // tesseract (../../../../../daggerverse/tesseract/enums.go:92:2)

)

// Format is an output renderer, which tesseract selects with a trailing
// CONFIGFILE word rather than a flag. Export takes a set of these because one
// recognition pass can drive several renderers at once.
type TesseractFormat string // tesseract (../../../../../daggerverse/tesseract/enums.go:118:6)

func (TesseractFormat) IsEnum() {}

func (v TesseractFormat) Name() string {
	switch v {
	case TesseractFormatAlto:
		return "ALTO"
	case TesseractFormatHocr:
		return "HOCR"
	case TesseractFormatPage:
		return "PAGE"
	case TesseractFormatPdf:
		return "PDF"
	case TesseractFormatTsv:
		return "TSV"
	case TesseractFormatTxt:
		return "TXT"
	default:
		return ""
	}
}

func (v TesseractFormat) Value() string {
	return string(v)
}

func (v *TesseractFormat) MarshalJSON() ([]byte, error) {
	if *v == "" {
		return []byte(`""`), nil
	}
	name := v.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", *v)
	}
	return json.Marshal(name)
}

func (v *TesseractFormat) UnmarshalJSON(dt []byte) error {
	var s string
	if err := json.Unmarshal(dt, &s); err != nil {
		return err
	}
	switch s {
	case "":
		*v = ""
	case "ALTO":
		*v = TesseractFormatAlto
	case "HOCR":
		*v = TesseractFormatHocr
	case "PAGE":
		*v = TesseractFormatPage
	case "PDF":
		*v = TesseractFormatPdf
	case "TSV":
		*v = TesseractFormatTsv
	case "TXT":
		*v = TesseractFormatTxt
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

const (
	// FormatAlto is ALTO XML, the library-and-archive layout schema.
	TesseractFormatAlto TesseractFormat = "ALTO" // tesseract (../../../../../daggerverse/tesseract/enums.go:127:2)

	// FormatHocr is hOCR: HTML carrying per-word bounding boxes and
	// confidences.
	TesseractFormatHocr TesseractFormat = "HOCR" // tesseract (../../../../../daggerverse/tesseract/enums.go:125:2)

	// FormatPage is PAGE XML, the PRImA layout-analysis schema.
	TesseractFormatPage TesseractFormat = "PAGE" // tesseract (../../../../../daggerverse/tesseract/enums.go:135:2)

	// FormatPdf is a searchable PDF: the source image with an invisible text
	// layer behind it.
	TesseractFormatPdf TesseractFormat = "PDF" // tesseract (../../../../../daggerverse/tesseract/enums.go:133:2)

	// FormatTsv is tab-separated rows, one per layout element, ending in the
	// word level.
	TesseractFormatTsv TesseractFormat = "TSV" // tesseract (../../../../../daggerverse/tesseract/enums.go:130:2)

	// FormatTxt is plain UTF-8 text, one line per recognised text line.
	TesseractFormatTxt TesseractFormat = "TXT" // tesseract (../../../../../daggerverse/tesseract/enums.go:122:2)

)

// PageSegMode is tesseract's page-segmentation mode (`--psm`): how much layout
// analysis to do before recognising anything. The enum value maps to the CLI's
// number internally, so an out-of-range mode is unrepresentable through the SDK.
//
// Mode 2 ("automatic page segmentation, but no OSD or OCR") is deliberately
// absent: upstream never implemented it, so it would ship as an always-useless
// member.
//
// Note on rendered names: the Dagger Go SDK derives each GraphQL enum member
// from the *constant identifier* in SCREAMING_SNAKE_CASE, so these surface as
// `OSD_ONLY`, `SINGLE_BLOCK_VERT_TEXT`, and so on.
type TesseractPageSegMode string // tesseract (../../../../../daggerverse/tesseract/enums.go:16:6)

func (TesseractPageSegMode) IsEnum() {}

func (v TesseractPageSegMode) Name() string {
	switch v {
	case TesseractPageSegModeAuto:
		return "AUTO"
	case TesseractPageSegModeAutoOsd:
		return "AUTO_OSD"
	case TesseractPageSegModeCircleWord:
		return "CIRCLE_WORD"
	case TesseractPageSegModeOsdOnly:
		return "OSD_ONLY"
	case TesseractPageSegModeRawLine:
		return "RAW_LINE"
	case TesseractPageSegModeSingleBlock:
		return "SINGLE_BLOCK"
	case TesseractPageSegModeSingleBlockVertText:
		return "SINGLE_BLOCK_VERT_TEXT"
	case TesseractPageSegModeSingleChar:
		return "SINGLE_CHAR"
	case TesseractPageSegModeSingleColumn:
		return "SINGLE_COLUMN"
	case TesseractPageSegModeSingleLine:
		return "SINGLE_LINE"
	case TesseractPageSegModeSingleWord:
		return "SINGLE_WORD"
	case TesseractPageSegModeSparseText:
		return "SPARSE_TEXT"
	case TesseractPageSegModeSparseTextOsd:
		return "SPARSE_TEXT_OSD"
	default:
		return ""
	}
}

func (v TesseractPageSegMode) Value() string {
	return string(v)
}

func (v *TesseractPageSegMode) MarshalJSON() ([]byte, error) {
	if *v == "" {
		return []byte(`""`), nil
	}
	name := v.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", *v)
	}
	return json.Marshal(name)
}

func (v *TesseractPageSegMode) UnmarshalJSON(dt []byte) error {
	var s string
	if err := json.Unmarshal(dt, &s); err != nil {
		return err
	}
	switch s {
	case "":
		*v = ""
	case "AUTO":
		*v = TesseractPageSegModeAuto
	case "AUTO_OSD":
		*v = TesseractPageSegModeAutoOsd
	case "CIRCLE_WORD":
		*v = TesseractPageSegModeCircleWord
	case "OSD_ONLY":
		*v = TesseractPageSegModeOsdOnly
	case "RAW_LINE":
		*v = TesseractPageSegModeRawLine
	case "SINGLE_BLOCK":
		*v = TesseractPageSegModeSingleBlock
	case "SINGLE_BLOCK_VERT_TEXT":
		*v = TesseractPageSegModeSingleBlockVertText
	case "SINGLE_CHAR":
		*v = TesseractPageSegModeSingleChar
	case "SINGLE_COLUMN":
		*v = TesseractPageSegModeSingleColumn
	case "SINGLE_LINE":
		*v = TesseractPageSegModeSingleLine
	case "SINGLE_WORD":
		*v = TesseractPageSegModeSingleWord
	case "SPARSE_TEXT":
		*v = TesseractPageSegModeSparseText
	case "SPARSE_TEXT_OSD":
		*v = TesseractPageSegModeSparseTextOsd
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

const (
	// PageSegModeAuto is full automatic segmentation without OSD, and is
	// tesseract's default.
	TesseractPageSegModeAuto TesseractPageSegMode = "AUTO" // tesseract (../../../../../daggerverse/tesseract/enums.go:28:2)

	// PageSegModeAutoOsd is full automatic segmentation with orientation and
	// script detection.
	TesseractPageSegModeAutoOsd TesseractPageSegMode = "AUTO_OSD" // tesseract (../../../../../daggerverse/tesseract/enums.go:25:2)

	// PageSegModeCircleWord treats the image as a single word in a circle.
	TesseractPageSegModeCircleWord TesseractPageSegMode = "CIRCLE_WORD" // tesseract (../../../../../daggerverse/tesseract/enums.go:42:2)

	// PageSegModeOsdOnly detects orientation and script and recognises
	// nothing. Osd is the ergonomic path to this mode; selecting it here
	// makes the text outputs return the OSD report instead of recognised text.
	TesseractPageSegModeOsdOnly TesseractPageSegMode = "OSD_ONLY" // tesseract (../../../../../daggerverse/tesseract/enums.go:22:2)

	// PageSegModeRawLine treats the image as a single text line, bypassing
	// tesseract-specific hacks.
	TesseractPageSegModeRawLine TesseractPageSegMode = "RAW_LINE" // tesseract (../../../../../daggerverse/tesseract/enums.go:53:2)

	// PageSegModeSingleBlock assumes a single uniform block of text.
	TesseractPageSegModeSingleBlock TesseractPageSegMode = "SINGLE_BLOCK" // tesseract (../../../../../daggerverse/tesseract/enums.go:36:2)

	// PageSegModeSingleBlockVertText assumes a single uniform block of
	// vertically aligned text.
	TesseractPageSegModeSingleBlockVertText TesseractPageSegMode = "SINGLE_BLOCK_VERT_TEXT" // tesseract (../../../../../daggerverse/tesseract/enums.go:34:2)

	// PageSegModeSingleChar treats the image as a single character.
	TesseractPageSegModeSingleChar TesseractPageSegMode = "SINGLE_CHAR" // tesseract (../../../../../daggerverse/tesseract/enums.go:44:2)

	// PageSegModeSingleColumn assumes a single column of text of variable
	// sizes.
	TesseractPageSegModeSingleColumn TesseractPageSegMode = "SINGLE_COLUMN" // tesseract (../../../../../daggerverse/tesseract/enums.go:31:2)

	// PageSegModeSingleLine treats the image as a single text line.
	TesseractPageSegModeSingleLine TesseractPageSegMode = "SINGLE_LINE" // tesseract (../../../../../daggerverse/tesseract/enums.go:38:2)

	// PageSegModeSingleWord treats the image as a single word.
	TesseractPageSegModeSingleWord TesseractPageSegMode = "SINGLE_WORD" // tesseract (../../../../../daggerverse/tesseract/enums.go:40:2)

	// PageSegModeSparseText finds as much text as possible in no particular
	// order.
	TesseractPageSegModeSparseText TesseractPageSegMode = "SPARSE_TEXT" // tesseract (../../../../../daggerverse/tesseract/enums.go:47:2)

	// PageSegModeSparseTextOsd is sparse text with orientation and script
	// detection.
	TesseractPageSegModeSparseTextOsd TesseractPageSegMode = "SPARSE_TEXT_OSD" // tesseract (../../../../../daggerverse/tesseract/enums.go:50:2)

)
