// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/tests/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Tests) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Tests) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Tests":
		switch fnName {
		case "All":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).All(&parent, ctx, parallel)
		case "BareMetal":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).BareMetal(&parent, ctx, parallel)
		case "BareMetalBootsAndCapturesSerial":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).BareMetalBootsAndCapturesSerial(&parent, ctx)
		case "BareMetalExitCodeNonZeroOnFail":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).BareMetalExitCodeNonZeroOnFail(&parent, ctx)
		case "BareMetalExitCodeZeroOnPass":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).BareMetalExitCodeZeroOnPass(&parent, ctx)
		case "BareMetalRejectsNilFirmware":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).BareMetalRejectsNilFirmware(&parent, ctx)
		case "BareMetalRejectsUnknownArch":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).BareMetalRejectsUnknownArch(&parent, ctx)
		case "Boot":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).Boot(&parent, ctx, parallel)
		case "DefaultsBootArm64Kernel":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).DefaultsBootArm64Kernel(&parent, ctx)
		case "DiskRejectsNilImage":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).DiskRejectsNilImage(&parent, ctx)
		case "EndpointRejectsUnforwardedPort":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).EndpointRejectsUnforwardedPort(&parent, ctx)
		case "EndpointReturnsForwardedHostPort":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).EndpointReturnsForwardedHostPort(&parent, ctx)
		case "Firmware":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).Firmware(&parent, ctx, parallel)
		case "LinuxBootReachesUserspace":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).LinuxBootReachesUserspace(&parent, ctx)
		case "LinuxRejectsNilKernel":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).LinuxRejectsNilKernel(&parent, ctx)
		case "Networking":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).Networking(&parent, ctx, parallel)
		case "RunCapturesFirmwareSerial":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).RunCapturesFirmwareSerial(&parent, ctx)
		case "RunShouldNotBeCached":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).RunShouldNotBeCached(&parent, ctx)
		case "SerialLogMaterializesFile":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).SerialLogMaterializesFile(&parent, ctx)
		case "ServiceForwardedPortReachable":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).ServiceForwardedPortReachable(&parent, ctx)
		case "StopHaltsService":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).StopHaltsService(&parent, ctx)
		case "Validation":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var parallel int
			if inputArgs["parallel"] != nil {
				err = json.Unmarshal([]byte(inputArgs["parallel"]), &parallel)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg parallel", err))
				}
			}
			return nil, (*Tests).Validation(&parent, ctx, parallel)
		case "WaitForLineMatchesFirmwareSerial":
			var parent Tests
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Tests).WaitForLineMatchesFirmwareSerial(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("Tests for the qemu daggerverse module. Each test is exposed as a standalone\ndagger function so it can be invoked individually during TDD; All wires them\nup for parallel execution under `dagger call all`. The four sub-aggregators\n(Validation, Firmware, Boot, Networking) each carry `+check` so CI schedules\nthem onto their own runners.\n").
			WithObject(
				dag.TypeDef().WithObject("Tests", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 19, 6)}).
					WithFunction(
						dag.Function("All",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("All runs every qemu test as a convenience for local `dagger call all`\ninvocations. CI does NOT call All: each sub-aggregator below carries its own\n`+check` directive, so GH Actions schedules each onto its own runner in\nparallel — running All on top would double-bill the same work.").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("main.go", 27, 1)).
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 30, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("BareMetal",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetal runs the bare-metal firmware + semihosting tests: boot a tiny\nfreestanding Cortex-M3 firmware (built reproducibly via the zig module) on\nthe MCU-class lm3s6965evb machine and assert that semihosting SYS_WRITE0\nreaches the serial console and SYS_EXIT surfaces as a guest exit code. These\nare fast TCG boots (the firmware writes a marker and exits immediately).").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("baremetal.go", 21, 1)).
							WithCheck().
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("baremetal.go", 24, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("BareMetalBootsAndCapturesSerial",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetalBootsAndCapturesSerial verifies a semihosting firmware's SYS_WRITE0\nmarker reaches the serial console through RunStatus, Run, and WaitForLine.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("baremetal.go", 59, 1))).
					WithFunction(
						dag.Function("BareMetalExitCodeNonZeroOnFail",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetalExitCodeNonZeroOnFail verifies a firmware that calls SYS_EXIT with a\nnon-zero code yields the corresponding non-zero RunStatus().ExitCode.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("baremetal.go", 125, 1))).
					WithFunction(
						dag.Function("BareMetalExitCodeZeroOnPass",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetalExitCodeZeroOnPass verifies a firmware that calls SYS_EXIT(0) yields\nRunStatus().ExitCode == 0.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("baremetal.go", 99, 1))).
					WithFunction(
						dag.Function("BareMetalRejectsNilFirmware",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetalRejectsNilFirmware verifies a nil firmware is rejected. The Dagger\nSDK binding panics via assertNotNil before the call leaves the test module;\nrecover and assert the panic mentions the rejected argument.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("baremetal.go", 153, 1))).
					WithFunction(
						dag.Function("BareMetalRejectsUnknownArch",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("BareMetalRejectsUnknownArch verifies BareMetal errors for an arch with no\nbare-metal (MCU) profile — e.g. a SoC arch like X86_64 that Linux/Disk\naccept but BareMetal does not.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("baremetal.go", 174, 1))).
					WithFunction(
						dag.Function("Boot",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Boot runs the real-kernel boot tests against the Alpine aarch64 netboot\nkernel (slow TCG boots).").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("main.go", 97, 1)).
							WithCheck().
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 100, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("DefaultsBootArm64Kernel",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("DefaultsBootArm64Kernel verifies the documented defaults boot a working VM:\narch=AARCH64 with empty machine/cpu must resolve to virt + cortex-a53 and\nreach userspace.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 432, 1))).
					WithFunction(
						dag.Function("DiskRejectsNilImage",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("DiskRejectsNilImage verifies a nil disk image is rejected (assertNotNil\npanic, as above).").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 251, 1))).
					WithFunction(
						dag.Function("EndpointRejectsUnforwardedPort",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("EndpointRejectsUnforwardedPort verifies Endpoint errors for a port that was\nnot in the machine's tcpPorts.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 271, 1))).
					WithFunction(
						dag.Function("EndpointReturnsForwardedHostPort",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("EndpointReturnsForwardedHostPort verifies Endpoint returns host:port for a\nforwarded port.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 292, 1))).
					WithFunction(
						dag.Function("Firmware",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Firmware runs the run-to-completion serial-capture tests against a tiny\ncustom-init initramfs (fast under TCG).").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("main.go", 74, 1)).
							WithCheck().
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 77, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("LinuxBootReachesUserspace",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("LinuxBootReachesUserspace verifies a real Alpine aarch64 kernel hands off to\nPID 1 in userspace: the kernel logs the /init handoff and userspace then runs\na working `uname` syscall.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 459, 1))).
					WithFunction(
						dag.Function("LinuxRejectsNilKernel",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("LinuxRejectsNilKernel verifies a nil kernel is rejected. The Dagger SDK\nbinding panics via assertNotNil before the call leaves the test module;\nrecover and assert the panic mentions the rejected argument.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 231, 1))).
					WithFunction(
						dag.Function("Networking",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Networking runs the service-bind end-to-end tests: boot a guest that brings up\nnetworking and serves a forwarded port, then prove reachability and teardown\nthrough WithServiceBinding. These are slow TCG boots plus real networking.").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("main.go", 119, 1)).
							WithCheck().
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 122, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("RunCapturesFirmwareSerial",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("RunCapturesFirmwareSerial verifies Run boots the firmware to completion and\nreturns its serial console.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 340, 1))).
					WithFunction(
						dag.Function("RunShouldNotBeCached",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("RunShouldNotBeCached verifies two Run calls on one Machine re-execute QEMU\nrather than cache-hitting: each boot emits fresh /dev/urandom bytes, so the\ntwo serial consoles must differ.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 401, 1))).
					WithFunction(
						dag.Function("SerialLogMaterializesFile",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("SerialLogMaterializesFile verifies SerialLog stages the serial console as a\nreadable *dagger.File.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 381, 1))).
					WithFunction(
						dag.Function("ServiceForwardedPortReachable",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("ServiceForwardedPortReachable boots a guest that brings up networking and\nlistens on a runtime-minted port, forwards it over slirp hostfwd, binds the\nmachine into a fresh consumer container, and asserts the port is reachable —\nproving hostfwd + slirp + WithServiceBinding wiring end-to-end.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 487, 1))).
					WithFunction(
						dag.Function("StopHaltsService",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("StopHaltsService proves Stop'sbacking service (the postgres EndpointShouldNotBeCached lifecycle analog).\nThe guest serves a per-boot identity token. We pin the service up with an\nexplicit Start so it stays one instance across reads, read the token, Stop\nthe machine, then read again — the second read re-binds and, because Stop\nkilled the original VM, gets a *fresh* boot with a different token. A no-op\nStop would leave the pinned instance serving the same token, so an unchanged\ntoken fails the test. This is robust to fast TCG boots (it relies on the\nrestart, not on out-racing it); the per-read nonce keeps the two reads from\ncache-colliding.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 522, 1))).
					WithFunction(
						dag.Function("Validation",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Validation runs the pure input-rejection and accessor tests. None boot a\nguest, so they're fast and safe to fan out unbounded.").
							WithCachePolicy(dagger.FunctionCachePolicyPerSession).
							WithSourceMap(dag.SourceMap("main.go", 51, 1)).
							WithCheck().
							WithArg("parallel", dag.TypeDef().WithKind(dagger.TypeDefKindIntegerKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 54, 2), DefaultValue: dagger.JSON("0")})).
					WithFunction(
						dag.Function("WaitForLineMatchesFirmwareSerial",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("WaitForLineMatchesFirmwareSerial verifies WaitForLine returns the console\nonce the marker line appears.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 362, 1)))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
