// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Tests() *Tests { // tests (../../../../../:0:0)
	q := r.query.Select("tests")

	return &Tests{
		query: q,
	}
}

type Tests struct { // tests (../../../../../:0:0)
	query *querybuilder.Selection

	all                                  *Void
	buildCrossTargetProducesBinary       *Void
	buildExeProducesExecutable           *Void
	buildExeRejectsEmptyRoot             *Void
	buildHelloProducesBinary             *Void
	buildOptimizeReleaseSmall            *Void
	buildRejectsInvalidOptimize          *Void
	ccCompilesHelloC                     *Void
	ccCrossWindowsProducesExe            *Void
	ccRejectsEmptyFiles                  *Void
	ccRejectsPathOutputName              *Void
	ciCheckWithBuildCatchesCompileError  *Void
	ciCheckWithBuildPassesOnCleanProject *Void
	ciCheckWithoutBuildIsFmtOnly         *Void
	ciRunAggregatesFailures              *Void
	ciRunAllStagesProducesBinary         *Void
	ciWithFmtPasses                      *Void
	ciWithTestPasses                     *Void
	containerHasZigToolchain             *Void
	containerInfersVersionFromZon        *Void
	cxxCompilesHelloCpp                  *Void
	envContainsVersionKey                *Void
	fmtHelloIsClean                      *Void
	fmtUnformattedReportsFile            *Void
	id                                   *ID
	objCopyProducesBinary                *Void
	objCopyProducesIntelHex              *Void
	objCopyRejectsUnknownFormat          *Void
	runHelloPrintsHello                  *Void
	sizeRejectsNonElf                    *Void
	sizeReportsSections                  *Void
	targetsListsKnownArch                *Void
	testDirectFilePasses                 *Void
	testHelloBuildStepPasses             *Void
	toolVersionReturnsVersion            *Void
}

func (r *Tests) WithGraphQLQuery(q *querybuilder.Selection) *Tests {
	return &Tests{
		query: q,
	}
}

// TestsAllOpts contains options for Tests.All
type TestsAllOpts struct {
	Parallel int
}

// All runs every zig-module test in parallel.
//
// parallel caps how many tests run concurrently inside this suite. Defaults to
// 0 (unbounded fan-out) — each `dagger check` job runs on its own GH Actions
// runner, so in-runner parallelism is bounded by the VM's CPU/memory, not by
// the scheduler. Pass any positive integer to opt into a specific cap.
func (r *Tests) All(ctx context.Context, opts ...TestsAllOpts) error {
	if r.all != nil {
		return nil
	}
	q := r.query.Select("all")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// BuildCrossTargetProducesBinary cross-compiles the hello fixture for
// aarch64-linux and asserts an artifact is produced. The binary is not
// host-runnable, so only its size is checked.
func (r *Tests) BuildCrossTargetProducesBinary(ctx context.Context) error {
	if r.buildCrossTargetProducesBinary != nil {
		return nil
	}
	q := r.query.Select("buildCrossTargetProducesBinary")

	return q.Execute(ctx)
}

// BuildExeProducesExecutable builds the single-file fixture via build-exe and
// asserts the produced file is named "main" and non-empty.
func (r *Tests) BuildExeProducesExecutable(ctx context.Context) error {
	if r.buildExeProducesExecutable != nil {
		return nil
	}
	q := r.query.Select("buildExeProducesExecutable")

	return q.Execute(ctx)
}

// BuildExeRejectsEmptyRoot asserts BuildExe rejects an empty root. BuildExe
// returns a lazy file, so the error surfaces on resolve.
func (r *Tests) BuildExeRejectsEmptyRoot(ctx context.Context) error {
	if r.buildExeRejectsEmptyRoot != nil {
		return nil
	}
	q := r.query.Select("buildExeRejectsEmptyRoot")

	return q.Execute(ctx)
}

// BuildHelloProducesBinary builds the hello fixture for the host and asserts
// the installed executable (zig-out/bin/hello) is non-empty.
func (r *Tests) BuildHelloProducesBinary(ctx context.Context) error {
	if r.buildHelloProducesBinary != nil {
		return nil
	}
	q := r.query.Select("buildHelloProducesBinary")

	return q.Execute(ctx)
}

// BuildOptimizeReleaseSmall builds the hello fixture with
// -Doptimize=ReleaseSmall and asserts an executable is produced.
func (r *Tests) BuildOptimizeReleaseSmall(ctx context.Context) error {
	if r.buildOptimizeReleaseSmall != nil {
		return nil
	}
	q := r.query.Select("buildOptimizeReleaseSmall")

	return q.Execute(ctx)
}

// BuildRejectsInvalidOptimize asserts Build rejects an invalid optimize value.
// Build returns a lazy directory, so the validation error surfaces on resolve.
func (r *Tests) BuildRejectsInvalidOptimize(ctx context.Context) error {
	if r.buildRejectsInvalidOptimize != nil {
		return nil
	}
	q := r.query.Select("buildRejectsInvalidOptimize")

	return q.Execute(ctx)
}

// CcCompilesHelloC compiles the C fixture for the host with `zig cc` and
// asserts the produced artifact is non-empty.
func (r *Tests) CcCompilesHelloC(ctx context.Context) error {
	if r.ccCompilesHelloC != nil {
		return nil
	}
	q := r.query.Select("ccCompilesHelloC")

	return q.Execute(ctx)
}

// CcCrossWindowsProducesExe cross-compiles the C fixture for
// x86_64-windows-gnu and asserts the artifact carries the requested output
// name. Resolving .Name runs the cross-compile, so a successful Name read also
// proves the cross build succeeded.
func (r *Tests) CcCrossWindowsProducesExe(ctx context.Context) error {
	if r.ccCrossWindowsProducesExe != nil {
		return nil
	}
	q := r.query.Select("ccCrossWindowsProducesExe")

	return q.Execute(ctx)
}

// CcRejectsEmptyFiles asserts Cc rejects an empty files slice. Cc returns a
// lazy file, so the validation error surfaces on resolve.
func (r *Tests) CcRejectsEmptyFiles(ctx context.Context) error {
	if r.ccRejectsEmptyFiles != nil {
		return nil
	}
	q := r.query.Select("ccRejectsEmptyFiles")

	return q.Execute(ctx)
}

// CcRejectsPathOutputName asserts Cc rejects a path-like outputName (the
// parameter is a bare filename, not a path). The validation error surfaces on
// resolve, before any zig exec runs.
func (r *Tests) CcRejectsPathOutputName(ctx context.Context) error {
	if r.ccRejectsPathOutputName != nil {
		return nil
	}
	q := r.query.Select("ccRejectsPathOutputName")

	return q.Execute(ctx)
}

// CiCheckWithBuildCatchesCompileError is the core regression test for issue
// #161: Ci.Check must compile when WithBuild was requested. The no-compile
// fixture is fmt-clean but does not type-check, so with only Fmt enabled Check
// reports a false green (see CiCheckWithoutBuildIsFmtOnly). Adding WithBuild
// must make Check run the build stage and surface the compile error.
func (r *Tests) CiCheckWithBuildCatchesCompileError(ctx context.Context) error {
	if r.ciCheckWithBuildCatchesCompileError != nil {
		return nil
	}
	q := r.query.Select("ciCheckWithBuildCatchesCompileError")

	return q.Execute(ctx)
}

// CiCheckWithBuildPassesOnCleanProject configures every stage against the clean
// hello fixture and calls Check (not Run), asserting no error. With WithBuild
// enabled, Check runs fmt, test, and the build stage; a nil return proves all
// three passed. Together with CiCheckWithBuildCatchesCompileError (build catches
// a compile error) this proves the build stage genuinely runs under Check when
// requested, rather than being silently skipped.
func (r *Tests) CiCheckWithBuildPassesOnCleanProject(ctx context.Context) error {
	if r.ciCheckWithBuildPassesOnCleanProject != nil {
		return nil
	}
	q := r.query.Select("ciCheckWithBuildPassesOnCleanProject")

	return q.Execute(ctx)
}

// CiCheckWithoutBuildIsFmtOnly is the counterpart to
// CiCheckWithBuildCatchesCompileError and pins the opt-in semantics: without
// WithBuild, Check runs only the enabled static checks and never compiles. The
// no-compile fixture is fmt-clean, so Fmt-only Check passes even though the
// project does not build. This preserves the documented build-free Check for
// multi-target pipelines that share one check run across N target builds.
func (r *Tests) CiCheckWithoutBuildIsFmtOnly(ctx context.Context) error {
	if r.ciCheckWithoutBuildIsFmtOnly != nil {
		return nil
	}
	q := r.query.Select("ciCheckWithoutBuildIsFmtOnly")

	return q.Execute(ctx)
}

// CiRunAggregatesFailures runs Ci against the ci-bad fixture with both Fmt and
// Test enabled and asserts stage-1 aggregated BOTH job failures rather than
// short-circuiting on the first. Fmt fails with the "unformatted files" message
// and Test fails with a withExec "exit code" error; the parallel aggregator
// concatenates both, so requiring both signatures in the message proves both
// jobs ran and both errors propagated (and the build was skipped).
func (r *Tests) CiRunAggregatesFailures(ctx context.Context) error {
	if r.ciRunAggregatesFailures != nil {
		return nil
	}
	q := r.query.Select("ciRunAggregatesFailures")

	return q.Execute(ctx)
}

// CiRunAllStagesProducesBinary runs Ci with every stage enabled against the
// hello fixture and asserts a non-empty binary is produced.
func (r *Tests) CiRunAllStagesProducesBinary(ctx context.Context) error {
	if r.ciRunAllStagesProducesBinary != nil {
		return nil
	}
	q := r.query.Select("ciRunAllStagesProducesBinary")

	return q.Execute(ctx)
}

// CiWithFmtPasses runs Ci with only the Fmt check enabled against the
// fmt-clean hello fixture and asserts the build stage still produces a
// non-empty binary.
func (r *Tests) CiWithFmtPasses(ctx context.Context) error {
	if r.ciWithFmtPasses != nil {
		return nil
	}
	q := r.query.Select("ciWithFmtPasses")

	return q.Execute(ctx)
}

// CiWithTestPasses runs Ci with only the Test check enabled (zig build test)
// against the hello fixture and asserts a non-empty binary is produced.
func (r *Tests) CiWithTestPasses(ctx context.Context) error {
	if r.ciWithTestPasses != nil {
		return nil
	}
	q := r.query.Select("ciWithTestPasses")

	return q.Execute(ctx)
}

// ContainerHasZigToolchain proves the base container is reachable, the
// downloaded toolchain is on PATH, the source is mounted at /src, and `zig`
// runs. This is the canary for every other test — if it fails, the rest can't
// possibly pass.
func (r *Tests) ContainerHasZigToolchain(ctx context.Context) error {
	if r.containerHasZigToolchain != nil {
		return nil
	}
	q := r.query.Select("containerHasZigToolchain")

	return q.Execute(ctx)
}

// ContainerInfersVersionFromZon asserts that constructing the module with
// New("") and a fixture whose build.zig.zon declares
// minimum_zig_version = zonVersion actually downloads the matching toolchain —
// i.e. resolveVersion + ZON parsing wire through to toolchain selection.
// zonVersion is a different patch than the pinned default, so a match proves
// inference rather than the fallback.
func (r *Tests) ContainerInfersVersionFromZon(ctx context.Context) error {
	if r.containerInfersVersionFromZon != nil {
		return nil
	}
	q := r.query.Select("containerInfersVersionFromZon")

	return q.Execute(ctx)
}

// CxxCompilesHelloCpp compiles the C++ fixture for the host with `zig c++` and
// asserts the produced artifact is non-empty.
func (r *Tests) CxxCompilesHelloCpp(ctx context.Context) error {
	if r.cxxCompilesHelloCpp != nil {
		return nil
	}
	q := r.query.Select("cxxCompilesHelloCpp")

	return q.Execute(ctx)
}

// EnvContainsVersionKey calls the source-less Env and asserts the `zig env`
// JSON contains the version key.
func (r *Tests) EnvContainsVersionKey(ctx context.Context) error {
	if r.envContainsVersionKey != nil {
		return nil
	}
	q := r.query.Select("envContainsVersionKey")

	return q.Execute(ctx)
}

// FmtHelloIsClean runs Fmt against the fmt-clean hello fixture and asserts no
// error is returned.
func (r *Tests) FmtHelloIsClean(ctx context.Context) error {
	if r.fmtHelloIsClean != nil {
		return nil
	}
	q := r.query.Select("fmtHelloIsClean")

	return q.Execute(ctx)
}

// FmtUnformattedReportsFile runs Fmt against the unformatted fixture and
// asserts it returns an error naming the offending file. Fmt surfaces the
// offending paths only via the error (it returns error alone, since a Dagger
// function's non-error return value is dropped at the GraphQL boundary when it
// also returns a non-nil error).
func (r *Tests) FmtUnformattedReportsFile(ctx context.Context) error {
	if r.fmtUnformattedReportsFile != nil {
		return nil
	}
	q := r.query.Select("fmtUnformattedReportsFile")

	return q.Execute(ctx)
}

// A unique identifier for this Tests.
func (r *Tests) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Tests) XXX_GraphQLType() string {
	return "Tests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Tests) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Tests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Tests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Tests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Tests{query: selectNode(dag.query, id, "Tests")}
	return nil
}

// ObjCopyProducesBinary converts the BuildExe ELF to a raw .bin and asserts the
// result is non-empty and no longer carries the ELF magic.
func (r *Tests) ObjCopyProducesBinary(ctx context.Context) error {
	if r.objCopyProducesBinary != nil {
		return nil
	}
	q := r.query.Select("objCopyProducesBinary")

	return q.Execute(ctx)
}

// ObjCopyProducesIntelHex converts the BuildExe ELF to Intel HEX and asserts the
// first record begins with ':' (the Intel HEX record start code).
func (r *Tests) ObjCopyProducesIntelHex(ctx context.Context) error {
	if r.objCopyProducesIntelHex != nil {
		return nil
	}
	q := r.query.Select("objCopyProducesIntelHex")

	return q.Execute(ctx)
}

// ObjCopyRejectsUnknownFormat asserts ObjCopy rejects an unsupported format
// (e.g. "uf2"). ObjCopy returns a lazy file, so the error surfaces on resolve.
func (r *Tests) ObjCopyRejectsUnknownFormat(ctx context.Context) error {
	if r.objCopyRejectsUnknownFormat != nil {
		return nil
	}
	q := r.query.Select("objCopyRejectsUnknownFormat")

	return q.Execute(ctx)
}

// RunHelloPrintsHello runs the hello fixture and asserts its stdout contains
// "hello".
func (r *Tests) RunHelloPrintsHello(ctx context.Context) error {
	if r.runHelloPrintsHello != nil {
		return nil
	}
	q := r.query.Select("runHelloPrintsHello")

	return q.Execute(ctx)
}

// SizeRejectsNonElf feeds a raw .bin (produced by ObjCopy) into Size and asserts
// a clear non-ELF error.
func (r *Tests) SizeRejectsNonElf(ctx context.Context) error {
	if r.sizeRejectsNonElf != nil {
		return nil
	}
	q := r.query.Select("sizeRejectsNonElf")

	return q.Execute(ctx)
}

// SizeReportsSections asserts Size on the BuildExe host ELF returns Text > 0 and
// internally consistent Flash/Ram rollups.
func (r *Tests) SizeReportsSections(ctx context.Context) error {
	if r.sizeReportsSections != nil {
		return nil
	}
	q := r.query.Select("sizeReportsSections")

	return q.Execute(ctx)
}

// TargetsListsKnownArch calls the source-less Targets and asserts a known
// architecture appears in the output.
func (r *Tests) TargetsListsKnownArch(ctx context.Context) error {
	if r.targetsListsKnownArch != nil {
		return nil
	}
	q := r.query.Select("targetsListsKnownArch")

	return q.Execute(ctx)
}

// TestDirectFilePasses runs `zig test main.zig` against the single-file
// fixture and asserts it succeeds.
func (r *Tests) TestDirectFilePasses(ctx context.Context) error {
	if r.testDirectFilePasses != nil {
		return nil
	}
	q := r.query.Select("testDirectFilePasses")

	return q.Execute(ctx)
}

// TestHelloBuildStepPasses runs `zig build test` against the hello fixture and
// asserts it succeeds.
func (r *Tests) TestHelloBuildStepPasses(ctx context.Context) error {
	if r.testHelloBuildStepPasses != nil {
		return nil
	}
	q := r.query.Select("testHelloBuildStepPasses")

	return q.Execute(ctx)
}

// ToolVersionReturnsVersion calls the source-less ToolVersion and asserts it
// returns a dotted version string.
func (r *Tests) ToolVersionReturnsVersion(ctx context.Context) error {
	if r.toolVersionReturnsVersion != nil {
		return nil
	}
	q := r.query.Select("toolVersionReturnsVersion")

	return q.Execute(ctx)
}
