package main

import (
	"context"
	"fmt"
	"strings"

	"dagger/tests/internal/dagger"
)

// sdkModule and sdkModuleSource are the Go SDK module a migrated workspace
// installs, under the name `dagger workspace migrate` gives it.
const (
	sdkModule       = "dagger-go-sdk"
	sdkModuleSource = "github.com/dagger/go-sdk"
)

// sdkWorkspaceConfig renders a dagger.toml that installs the Go SDK and has it
// manage the module in each of scopes.
func sdkWorkspaceConfig(scopes ...string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "[modules.%q]\nsource = %q\n\n[sdks.go]\nmodule = %q\n", sdkModule, sdkModuleSource, sdkModule)
	for _, s := range scopes {
		fmt.Fprintf(&b, "\n[sdks.go.scopes.%q]\nis-module = true\n", s)
	}
	return b.String()
}

// PlanRunsTheChecksOfModulesTheWorkspaceInstalls proves a plan reaches the checks
// of a module the workspace's dagger.toml installs from outside the repository —
// the Go SDK, whose `stale` check is what keeps committed bindings honest in a
// migrated workspace. No module directory declares those checks, so before this a
// plan never ran them while `dagger check -l` at the root listed them.
//
// The leg must run from the workspace root without -m (the module has no
// directory), select by the installed name, and never be memoized. And a module
// the workspace installs from one of its own directories must not get a second
// leg: the root module, installed as ".", already has its own.
func (t *Tests) PlanRunsTheChecksOfModulesTheWorkspaceInstalls(ctx context.Context) error {
	tree := configShapeTrees()["all dagger-module.toml"]
	dir := tree.dir.WithNewFile("dagger.toml",
		"[modules.root]\nsource = \".\"\nentrypoint = true\n\n"+sdkWorkspaceConfig(".", "mods/x"))

	got, err := explainRange(ctx, dag.WorkspaceCi(), fixture{dir: dir}, "", "", "")
	if err != nil {
		return err
	}
	installed := sdkModule + " (workspace)"
	if err := wantLegs(got, fxRoot, "mods/x", installed); err != nil {
		return err
	}
	l, err := find(got, installed)
	if err != nil {
		return err
	}
	if l.Module != "" || l.ModuleName != sdkModule || l.Filter != "" || l.Hash != "" {
		return fmt.Errorf("the installed module's leg is %+v, want no module, module name %q, no filter and no hash", l, sdkModule)
	}
	if len(got.LoadedModules) != 0 {
		return fmt.Errorf("planning an installed module's leg built %v", got.LoadedModules)
	}
	return nil
}

// sdkGeneratedTree is a migrated workspace whose one module is managed by the Go
// SDK and generated by it, so the SDK's own staleness check passes on it.
func sdkGeneratedTree() *dagger.Directory {
	src := dag.Directory().
		WithNewFile("dagger.toml", sdkWorkspaceConfig("mods/x")).
		WithNewFile("mods/x/dagger-module.toml", tomlModuleConfig("x", "")).
		WithNewFile("mods/x/main.go", checkSource("X", "Ok"))
	ws := src.AsWorkspace()
	return ws.WithChanges(ws.SDK("go").Generate()).Directory("/")
}

// GeneratedProvesTheSdkStalenessCheck runs Generated against
// a workspace that installs the Go SDK. There the comparison belongs to the SDK's
// own `stale` check, which a plan runs as a leg of its own, and Generated is left
// with proving that check worth trusting: that the SDK manages every module with
// generated files, and that the check fails on a module made stale on purpose.
//
// So it must pass on a freshly generated workspace — the proof runs inside it —
// and must fail, naming the file, once a module the SDK does not manage commits
// generated code.
func (t *Tests) GeneratedProvesTheSdkStalenessCheck(ctx context.Context) error {
	fresh := sdkGeneratedTree()
	if err := checkErr(ctx, dag.WorkspaceCi().Generated(fresh.AsWorkspace())); err != nil {
		return fmt.Errorf("Generated failed on a freshly generated, SDK-managed workspace: %w", err)
	}

	const unmanaged = "mods/y/dagger.gen.go"
	outside := fresh.
		WithNewFile("mods/y/dagger-module.toml", tomlModuleConfig("y", "")).
		WithNewFile("mods/y/main.go", checkSource("Y", "Ok")).
		WithNewFile(unmanaged, "package main\n")
	err := checkErr(ctx, dag.WorkspaceCi().Generated(outside.AsWorkspace()))
	if err == nil {
		return fmt.Errorf("a module no SDK manages committed %s and Generated passed", unmanaged)
	}
	if msg := err.Error(); !strings.Contains(msg, unmanaged) || !strings.Contains(msg, "scopes") {
		return fmt.Errorf("Generated failed, but not by reporting %s as outside every SDK scope: %v", unmanaged, err)
	}
	if strings.Contains(err.Error(), "mods/x/") {
		return fmt.Errorf("Generated reported the SDK-managed module as unswept: %v", err)
	}
	return nil
}
