// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Postgres
func (r *Binding) AsPostgres() *Postgres { // postgres (../../../../../daggerverse/postgres/main.go:29:6)
	q := r.query.Select("asPostgres")

	return &Postgres{
		query: q,
	}
}

// Retrieve the binding value, as type PostgresClient
func (r *Binding) AsPostgresClient() *PostgresClient { // postgres (../../../../../daggerverse/postgres/client.go:24:6)
	q := r.query.Select("asPostgresClient")

	return &PostgresClient{
		query: q,
	}
}

// Retrieve the binding value, as type PostgresClientSecurity
func (r *Binding) AsPostgresClientSecurity() *PostgresClientSecurity { // postgres (../../../../../daggerverse/postgres/security.go:36:6)
	q := r.query.Select("asPostgresClientSecurity")

	return &PostgresClientSecurity{
		query: q,
	}
}

// Retrieve the binding value, as type PostgresCluster
func (r *Binding) AsPostgresCluster() *PostgresCluster { // postgres (../../../../../daggerverse/postgres/cluster.go:17:6)
	q := r.query.Select("asPostgresCluster")

	return &PostgresCluster{
		query: q,
	}
}

// Retrieve the binding value, as type PostgresServerSecurity
func (r *Binding) AsPostgresServerSecurity() *PostgresServerSecurity { // postgres (../../../../../daggerverse/postgres/security.go:20:6)
	q := r.query.Select("asPostgresServerSecurity")

	return &PostgresServerSecurity{
		query: q,
	}
}

// Create or update a binding of type PostgresClient in the environment
func (r *Env) WithPostgresClientInput(name string, value *PostgresClient, description string) *Env { // postgres (../../../../../daggerverse/postgres/client.go:24:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresClientInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PostgresClient output to be assigned in the environment
func (r *Env) WithPostgresClientOutput(name string, description string) *Env { // postgres (../../../../../daggerverse/postgres/client.go:24:6)
	q := r.query.Select("withPostgresClientOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PostgresClientSecurity in the environment
func (r *Env) WithPostgresClientSecurityInput(name string, value *PostgresClientSecurity, description string) *Env { // postgres (../../../../../daggerverse/postgres/security.go:36:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresClientSecurityInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PostgresClientSecurity output to be assigned in the environment
func (r *Env) WithPostgresClientSecurityOutput(name string, description string) *Env { // postgres (../../../../../daggerverse/postgres/security.go:36:6)
	q := r.query.Select("withPostgresClientSecurityOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PostgresCluster in the environment
func (r *Env) WithPostgresClusterInput(name string, value *PostgresCluster, description string) *Env { // postgres (../../../../../daggerverse/postgres/cluster.go:17:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresClusterInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PostgresCluster output to be assigned in the environment
func (r *Env) WithPostgresClusterOutput(name string, description string) *Env { // postgres (../../../../../daggerverse/postgres/cluster.go:17:6)
	q := r.query.Select("withPostgresClusterOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Postgres in the environment
func (r *Env) WithPostgresInput(name string, value *Postgres, description string) *Env { // postgres (../../../../../daggerverse/postgres/main.go:29:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Postgres output to be assigned in the environment
func (r *Env) WithPostgresOutput(name string, description string) *Env { // postgres (../../../../../daggerverse/postgres/main.go:29:6)
	q := r.query.Select("withPostgresOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type PostgresServerSecurity in the environment
func (r *Env) WithPostgresServerSecurityInput(name string, value *PostgresServerSecurity, description string) *Env { // postgres (../../../../../daggerverse/postgres/security.go:20:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresServerSecurityInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PostgresServerSecurity output to be assigned in the environment
func (r *Env) WithPostgresServerSecurityOutput(name string, description string) *Env { // postgres (../../../../../daggerverse/postgres/security.go:20:6)
	q := r.query.Select("withPostgresServerSecurityOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Postgres is the root namespace for every exported function in this
// module. All cluster constructors, security helpers, and the
// remote-client factory hang off *Postgres so the generated Dagger SDK
// surfaces them under `dag.Postgres().<Func>(...)`.
type Postgres struct { // postgres (../../../../../daggerverse/postgres/main.go:29:6)
	query *querybuilder.Selection

	id *ID
}

func (r *Postgres) WithGraphQLQuery(q *querybuilder.Selection) *Postgres {
	return &Postgres{
		query: q,
	}
}

// PostgresClientOpts contains options for Postgres.Client
type PostgresClientOpts struct {

	// Default: 5432
	Port int // postgres (../../../../../daggerverse/postgres/client.go:56:2)
}

// Client constructs a pgx-backed PostgreSQL client targeting host:port
// with the given role, database, and password. No I/O happens at
// construction time. Works against the local Cluster() topology or any
// reachable remote PostgreSQL — AWS RDS, Cloud SQL, an existing
// self-hosted primary, anything that speaks the PostgreSQL wire
// protocol with scram-sha-256 password auth.
func (r *Postgres) Client(host string, user string, db string, password *Secret, security *PostgresClientSecurity, opts ...PostgresClientOpts) *PostgresClient { // postgres (../../../../../daggerverse/postgres/client.go:53:1)
	assertNotNil("password", password)
	assertNotNil("security", security)
	q := r.query.Select("client")
	for i := len(opts) - 1; i >= 0; i-- {
		// `port` optional argument
		if !querybuilder.IsZeroValue(opts[i].Port) {
			q = q.Arg("port", opts[i].Port)
		}
	}
	q = q.Arg("host", host)
	q = q.Arg("user", user)
	q = q.Arg("db", db)
	q = q.Arg("password", password)
	q = q.Arg("security", security)

	return &PostgresClient{
		query: q,
	}
}

// PostgresClusterOpts contains options for Postgres.Cluster
type PostgresClusterOpts struct {
	Name string // postgres (../../../../../daggerverse/postgres/cluster.go:71:2)

	// Default: "docker.io"
	Registry string // postgres (../../../../../daggerverse/postgres/cluster.go:73:2)

	// Default: "17"
	Tag string // postgres (../../../../../daggerverse/postgres/cluster.go:75:2)

	// Default: "postgres"
	User string // postgres (../../../../../daggerverse/postgres/cluster.go:77:2)

	// Default: "postgres"
	Db string // postgres (../../../../../daggerverse/postgres/cluster.go:79:2)
}

// Cluster spins up a single-node PostgreSQL primary listening on 5432
// with scram-sha-256 password auth over a plaintext TCP listener (the
// only security mode in this story).
//
// Image: `<registry>/library/postgres:<tag>` — the `library/postgres`
// portion is fixed; only `registry` and `tag` are caller-overridable.
// The default tag `"17"` pins this story to PostgreSQL 17.
//
// Rejected inputs (each surfaces a descriptive error rather than
// booting a half-broken cluster):
//
//   - `password == nil` — the primary refuses to start without a
//     superuser password and a plaintext-password cluster needs one.
//   - `clientListenerSecurity == nil` or a non-PLAINTEXT mode —
//     plaintext must be a deliberate caller choice so a future TLS
//     upgrade stays explicit.
//   - `user == ""` / `db == ""` — the postgres image needs both to
//     provision the superuser role and the default database.
//
// Session-cached so that repeated chained method calls on the returned
// cluster (e.g. Client.Exec → Client.Scalar across two Cluster.Client()
// calls in `exec-scalar-round-trip`) observe the SAME underlying
// service — and therefore the same on-disk state. Every method on
// *Cluster and *Client is independently marked never-cache, so any
// data-returning call re-executes per invocation.
//
// `name` is a caller-supplied discriminator that folds into the session
// cache key. Parallel test suites should pass a unique value per test
// so each test gets its own backing service — without it, every
// same-shape call collapses to one cached cluster and concurrent tests
// race on shared tables and storage. Same name + same shape still
// cache-hits, which is what a single test's chained Client.Exec →
// Client.Scalar sequence needs. Leaving the default empty is fine for
// ad-hoc `dagger call` use where only one cluster is in play.
func (r *Postgres) Cluster(password *Secret, clientListenerSecurity *PostgresServerSecurity, opts ...PostgresClusterOpts) *PostgresCluster { // postgres (../../../../../daggerverse/postgres/cluster.go:68:1)
	assertNotNil("password", password)
	assertNotNil("clientListenerSecurity", clientListenerSecurity)
	q := r.query.Select("cluster")
	for i := len(opts) - 1; i >= 0; i-- {
		// `name` optional argument
		if !querybuilder.IsZeroValue(opts[i].Name) {
			q = q.Arg("name", opts[i].Name)
		}
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `user` optional argument
		if !querybuilder.IsZeroValue(opts[i].User) {
			q = q.Arg("user", opts[i].User)
		}
		// `db` optional argument
		if !querybuilder.IsZeroValue(opts[i].Db) {
			q = q.Arg("db", opts[i].Db)
		}
	}
	q = q.Arg("password", password)
	q = q.Arg("clientListenerSecurity", clientListenerSecurity)

	return &PostgresCluster{
		query: q,
	}
}

// A unique identifier for this Postgres.
func (r *Postgres) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Postgres) XXX_GraphQLType() string {
	return "Postgres"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Postgres) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Postgres) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Postgres) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Postgres) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Postgres{query: selectNode(dag.query, id, "Postgres")}
	return nil
}

// MtlsClientSecurity returns a ClientSecurity profile that opens a
// mutual-TLS connection: the server is verified against serverCa and the
// client presents clientCert + clientKey to satisfy the primary's
// clientcert=verify-full requirement.
func (r *Postgres) MtlsClientSecurity(serverCa *File, clientCert *File, clientKey *Secret) *PostgresClientSecurity { // postgres (../../../../../daggerverse/postgres/security.go:101:1)
	assertNotNil("serverCa", serverCa)
	assertNotNil("clientCert", clientCert)
	assertNotNil("clientKey", clientKey)
	q := r.query.Select("mtlsClientSecurity")
	q = q.Arg("serverCa", serverCa)
	q = q.Arg("clientCert", clientCert)
	q = q.Arg("clientKey", clientKey)

	return &PostgresClientSecurity{
		query: q,
	}
}

// MtlsServerSecurity returns a ServerSecurity profile that terminates
// mutual TLS. In addition to the server leaf (serverCert and serverKey),
// clientCa is mounted as ssl_ca_file and the pg_hba.conf line carries
// `clientcert=verify-full`, so connecting clients must present a cert
// signed by clientCa AND the correct password.
func (r *Postgres) MtlsServerSecurity(serverCert *File, serverKey *Secret, clientCa *File) *PostgresServerSecurity { // postgres (../../../../../daggerverse/postgres/security.go:72:1)
	assertNotNil("serverCert", serverCert)
	assertNotNil("serverKey", serverKey)
	assertNotNil("clientCa", clientCa)
	q := r.query.Select("mtlsServerSecurity")
	q = q.Arg("serverCert", serverCert)
	q = q.Arg("serverKey", serverKey)
	q = q.Arg("clientCa", clientCa)

	return &PostgresServerSecurity{
		query: q,
	}
}

// PlaintextClientSecurity returns a ClientSecurity profile configured
// for scram-sha-256 password auth over an unencrypted TCP connection.
func (r *Postgres) PlaintextClientSecurity() *PostgresClientSecurity { // postgres (../../../../../daggerverse/postgres/security.go:83:1)
	q := r.query.Select("plaintextClientSecurity")

	return &PostgresClientSecurity{
		query: q,
	}
}

// PlaintextServerSecurity returns a ServerSecurity profile configured
// for scram-sha-256 password auth over an unencrypted TCP listener.
func (r *Postgres) PlaintextServerSecurity() *PostgresServerSecurity { // postgres (../../../../../daggerverse/postgres/security.go:49:1)
	q := r.query.Select("plaintextServerSecurity")

	return &PostgresServerSecurity{
		query: q,
	}
}

// TlsClientSecurity returns a ClientSecurity profile that opens a
// one-way TLS connection and verifies the server against serverCa
// (sslmode=verify-full with the supplied root).
func (r *Postgres) TLSClientSecurity(serverCa *File) *PostgresClientSecurity { // postgres (../../../../../daggerverse/postgres/security.go:90:1)
	assertNotNil("serverCa", serverCa)
	q := r.query.Select("tlsClientSecurity")
	q = q.Arg("serverCa", serverCa)

	return &PostgresClientSecurity{
		query: q,
	}
}

// TlsServerSecurity returns a ServerSecurity profile that terminates
// one-way TLS on the primary's :5432 listener. serverCert is the PEM
// leaf certificate (its SAN must cover the cluster hostname the client
// dials) and serverKey is the matching PEM PKCS#8 private key. The
// primary starts with `ssl=on` and a pg_hba.conf that accepts only
// `hostssl … scram-sha-256` — plaintext TCP is refused.
func (r *Postgres) TLSServerSecurity(serverCert *File, serverKey *Secret) *PostgresServerSecurity { // postgres (../../../../../daggerverse/postgres/security.go:59:1)
	assertNotNil("serverCert", serverCert)
	assertNotNil("serverKey", serverKey)
	q := r.query.Select("tlsServerSecurity")
	q = q.Arg("serverCert", serverCert)
	q = q.Arg("serverKey", serverKey)

	return &PostgresServerSecurity{
		query: q,
	}
}

// AsNode returns this Postgres as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Postgres) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Client is a pgx-backed PostgreSQL client. Each method opens a fresh
// connection so the function call is stateless from Dagger's
// perspective; ApplyFile is the exception — it runs every statement on
// one connection.
type PostgresClient struct { // postgres (../../../../../daggerverse/postgres/client.go:24:6)
	query *querybuilder.Selection

	applyFile *Void
	exec      *int
	id        *ID
	ping      *Void
	scalar    *string
}

func (r *PostgresClient) WithGraphQLQuery(q *querybuilder.Selection) *PostgresClient {
	return &PostgresClient{
		query: q,
	}
}

// ApplyFile reads a `.sql` file and runs its statements on a single
// connection, in order. Statements are split on `;` outside of single-
// and double-quoted strings, line (`--`) and block (`/* */`) comments,
// and dollar-quoted strings (`$$ ... $$` / `$tag$ ... $tag$`).
func (r *PostgresClient) ApplyFile(ctx context.Context, file *File) error { // postgres (../../../../../daggerverse/postgres/client.go:283:1)
	assertNotNil("file", file)
	if r.applyFile != nil {
		return nil
	}
	q := r.query.Select("applyFile")
	q = q.Arg("file", file)

	return q.Execute(ctx)
}

// Exec runs a SQL statement and returns the affected-row count
// (INSERT/UPDATE/DELETE rows, or 0 for DDL).
func (r *PostgresClient) Exec(ctx context.Context, sql string) (int, error) { // postgres (../../../../../daggerverse/postgres/client.go:226:1)
	if r.exec != nil {
		return *r.exec, nil
	}
	q := r.query.Select("exec")
	q = q.Arg("sql", sql)

	var response int

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this PostgresClient.
func (r *PostgresClient) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PostgresClient) XXX_GraphQLType() string {
	return "PostgresClient"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PostgresClient) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PostgresClient) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PostgresClient) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PostgresClient) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PostgresClient{query: selectNode(dag.query, id, "PostgresClient")}
	return nil
}

// Ping opens a connection and verifies the server is reachable and
// accepting authenticated queries.
func (r *PostgresClient) Ping(ctx context.Context) error { // postgres (../../../../../daggerverse/postgres/client.go:213:1)
	if r.ping != nil {
		return nil
	}
	q := r.query.Select("ping")

	return q.Execute(ctx)
}

// QueryJSON runs a query and returns the result set as a *dagger.File
// containing a JSON array of objects — one per row, keyed by column
// name.
func (r *PostgresClient) QueryJSON(sql string) *File { // postgres (../../../../../daggerverse/postgres/client.go:308:1)
	q := r.query.Select("queryJson")
	q = q.Arg("sql", sql)

	return &File{
		query: q,
	}
}

// Scalar runs a query and returns the first column of the first row as
// a string. Errors if the query returns zero rows, or if that first
// column is SQL NULL (rather than silently returning the string
// "<nil>").
func (r *PostgresClient) Scalar(ctx context.Context, sql string) (string, error) { // postgres (../../../../../daggerverse/postgres/client.go:245:1)
	if r.scalar != nil {
		return *r.scalar, nil
	}
	q := r.query.Select("scalar")
	q = q.Arg("sql", sql)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this PostgresClient as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PostgresClient) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// ClientSecurity describes how a pgx client authenticates to a Postgres
// primary. PLAINTEXT connects over an unencrypted TCP listener; TLS pins
// the server CA (sslmode=verify-full); MTLS additionally presents a
// client certificate + key. The client builds a *tls.Config from this
// PEM material and hands it to pgx via pgconn.Config.TLSConfig.
type PostgresClientSecurity struct { // postgres (../../../../../daggerverse/postgres/security.go:36:6)
	query *querybuilder.Selection

	id *ID
}

func (r *PostgresClientSecurity) WithGraphQLQuery(q *querybuilder.Selection) *PostgresClientSecurity {
	return &PostgresClientSecurity{
		query: q,
	}
}

// A unique identifier for this PostgresClientSecurity.
func (r *PostgresClientSecurity) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PostgresClientSecurity) XXX_GraphQLType() string {
	return "PostgresClientSecurity"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PostgresClientSecurity) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PostgresClientSecurity) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PostgresClientSecurity) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PostgresClientSecurity) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PostgresClientSecurity{query: selectNode(dag.query, id, "PostgresClientSecurity")}
	return nil
}

// AsNode returns this PostgresClientSecurity as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PostgresClientSecurity) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Cluster represents a running single-node PostgreSQL primary plus the
// connection metadata callers need to reach it. Holds a reference to
// the backing service so callers can bind it into their own containers
// or open a pgx Client against it.
type PostgresCluster struct { // postgres (../../../../../daggerverse/postgres/cluster.go:17:6)
	query *querybuilder.Selection

	database *string
	endpoint *string
	id       *ID
	stop     *Void
	user     *string
}

func (r *PostgresCluster) WithGraphQLQuery(q *querybuilder.Selection) *PostgresCluster {
	return &PostgresCluster{
		query: q,
	}
}

// BindPrimary attaches the primary service to the given container under
// the same hostname Endpoint reports, so the container can dial the
// primary at `Endpoint()` (e.g. `pg_isready -h <host>`).
func (r *PostgresCluster) BindPrimary(ctr *Container) *Container { // postgres (../../../../../daggerverse/postgres/cluster.go:205:1)
	assertNotNil("ctr", ctr)
	q := r.query.Select("bindPrimary")
	q = q.Arg("ctr", ctr)

	return &Container{
		query: q,
	}
}

// Client starts the primary and returns a pgx Client wired with its
// endpoint, superuser role, default database, and password.
//
// The supplied ClientSecurity mode must match the cluster's listener
// mode (PLAINTEXT/TLS/MTLS); a mismatch returns an error naming both
// modes rather than failing opaquely at the wire. Readiness is then
// probed with the client itself, so a TLS / mTLS listener is polled over
// TLS using the caller's own cert material — the only way to
// authenticate the probe against an mTLS listener.
func (r *PostgresCluster) Client(security *PostgresClientSecurity) *PostgresClient { // postgres (../../../../../daggerverse/postgres/cluster.go:220:1)
	assertNotNil("security", security)
	q := r.query.Select("client")
	q = q.Arg("security", security)

	return &PostgresClient{
		query: q,
	}
}

// Database returns the default database name the cluster was
// provisioned with.
func (r *PostgresCluster) Database(ctx context.Context) (string, error) { // postgres (../../../../../daggerverse/postgres/cluster.go:187:1)
	if r.database != nil {
		return *r.database, nil
	}
	q := r.query.Select("database")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Endpoint returns the primary's `host:5432` address. It does NOT start
// the service: it is a pure accessor, mirroring kafka's BootstrapServers.
// BindPrimary is what makes that address reachable from a consumer
// container (WithServiceBinding starts the service as the consumer's
// dependency and wires its IP into /etc/hosts). For module-runtime
// access use Cluster.Client, which starts the service itself.
//
// Pre-starting the service from this module before a consumer binds it
// would register the service in the module's DNS domain, which the
// binding's host-file lookup can't resolve from a session-domain
// consumer — so the start must be driven by the binding, not here.
func (r *PostgresCluster) Endpoint(ctx context.Context) (string, error) { // postgres (../../../../../daggerverse/postgres/cluster.go:171:1)
	if r.endpoint != nil {
		return *r.endpoint, nil
	}
	q := r.query.Select("endpoint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this PostgresCluster.
func (r *PostgresCluster) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PostgresCluster) XXX_GraphQLType() string {
	return "PostgresCluster"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PostgresCluster) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PostgresCluster) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PostgresCluster) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PostgresCluster) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PostgresCluster{query: selectNode(dag.query, id, "PostgresCluster")}
	return nil
}

// Password returns the superuser password secret the cluster was
// provisioned with, so callers can re-use it via Postgres.Client
// against the same endpoint.
func (r *PostgresCluster) Password() *Secret { // postgres (../../../../../daggerverse/postgres/cluster.go:196:1)
	q := r.query.Select("password")

	return &Secret{
		query: q,
	}
}

// Stop tears down the service container backing this cluster. Tests
// should call this in a defer so the service span closes when the test
// returns. SIGKILL skips graceful shutdown — Postgres' checkpoint-on-
// shutdown path is wasted work for a torn-down test cluster.
func (r *PostgresCluster) Stop(ctx context.Context) error { // postgres (../../../../../daggerverse/postgres/cluster.go:271:1)
	if r.stop != nil {
		return nil
	}
	q := r.query.Select("stop")

	return q.Execute(ctx)
}

// User returns the superuser role name the cluster was provisioned
// with.
func (r *PostgresCluster) User(ctx context.Context) (string, error) { // postgres (../../../../../daggerverse/postgres/cluster.go:179:1)
	if r.user != nil {
		return *r.user, nil
	}
	q := r.query.Select("user")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this PostgresCluster as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PostgresCluster) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// ServerSecurity describes how a Postgres cluster's client-facing
// listener authenticates and encrypts traffic. Three modes are
// supported:
//
//   - PLAINTEXT — scram-sha-256 password auth over an unencrypted TCP
//     listener.
//   - TLS — one-way TLS: the primary presents a server certificate and
//     clients still authenticate with scram-sha-256. Plaintext TCP is
//     refused.
//   - MTLS — mutual TLS: connecting clients must additionally present a
//     certificate signed by ClientCa (clientcert=verify-full) on top of
//     the password.
//
// The cert material is caller-supplied PEM: PostgreSQL reads it natively
// via ssl_cert_file / ssl_key_file / ssl_ca_file.
type PostgresServerSecurity struct { // postgres (../../../../../daggerverse/postgres/security.go:20:6)
	query *querybuilder.Selection

	id *ID
}

func (r *PostgresServerSecurity) WithGraphQLQuery(q *querybuilder.Selection) *PostgresServerSecurity {
	return &PostgresServerSecurity{
		query: q,
	}
}

// A unique identifier for this PostgresServerSecurity.
func (r *PostgresServerSecurity) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PostgresServerSecurity) XXX_GraphQLType() string {
	return "PostgresServerSecurity"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PostgresServerSecurity) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PostgresServerSecurity) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PostgresServerSecurity) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PostgresServerSecurity) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = PostgresServerSecurity{query: selectNode(dag.query, id, "PostgresServerSecurity")}
	return nil
}

// AsNode returns this PostgresServerSecurity as a Node.
// This is a local type conversion — no GraphQL call.
func (r *PostgresServerSecurity) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Postgres is the root namespace for every exported function in this
// module. All cluster constructors, security helpers, and the
// remote-client factory hang off *Postgres so the generated Dagger SDK
// surfaces them under `dag.Postgres().<Func>(...)`.
func (r *Query) Postgres() *Postgres { // postgres (../../../../../daggerverse/postgres/main.go:29:6)
	q := r.query.Select("postgres")

	return &Postgres{
		query: q,
	}
}
