// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Tests() *Tests { // tests (../../../../../:0:0)
	q := r.query.Select("tests")

	return &Tests{
		query: q,
	}
}

type Tests struct { // tests (../../../../../:0:0)
	query *querybuilder.Selection

	all                                                   *Void
	apkAuthInstallsFromAuthenticatedRepository            *Void
	apkRepositoryAssemblesWorkingToolchainFromMirror      *Void
	apkRepositoryReplacesImageDefaults                    *Void
	attachmentsReportsPopplersRefusalOfPathBearingNames   *Void
	attachmentsReturnsEveryEmbeddedFileOrSaysThereAreNone *Void
	authenticatedRepositoryIsRejectedWithoutApkAuth       *Void
	bboxCarriesOneBoxPerWord                              *Void
	bboxWithLayoutAddsBlockAndLineBoxes                   *Void
	colorModesProduceDifferentPixels                      *Void
	containerCarriesEveryPopplerBinaryAndTheFont          *Void
	defaultApkConfigurationIsUntouched                    *Void
	disablePageBreaksControlsFormFeeds                    *Void
	dpiDefaultsToOneFiftyAndScalesWithTheSetting          *Void
	embeddedImagesKeepsTheOriginalEncoding                *Void
	embeddedImagesNamesEveryImageAndNarrowsToThePageRange *Void
	embeddedImagesReturnsTheStoredImageNotTheRenderedPage *Void
	encryptedDocumentNeedsThePassword                     *Void
	epsWritesEveryPageOfTheDocument                       *Void
	extractionsOpenAnEncryptedDocumentWithThePassword     *Void
	fontsNarrowsToThePageRange                            *Void
	fontsReportsWhetherEachFaceIsEmbedded                 *Void
	geometryOfAnImageOnlyPdfReportsPagesWithoutWords      *Void
	htmlCarriesPageMarkupAndItsImages                     *Void
	id                                                    *ID
	infoReportsPageCountAndSize                           *Void
	jpegAndTiffFollowTheSameContract                      *Void
	layoutModesProduceDifferentOrderings                  *Void
	mergePreservesTheOrderOfItsSources                    *Void
	mergeRejectsWhatItCannotMerge                         *Void
	metadataReturnsTheXmpPacketOrSaysThereIsNone          *Void
	pageRangeNarrowsEveryPerPageFormat                    *Void
	pageRangeNarrowsText                                  *Void
	pageRangeNarrowsTheGeometryOutputs                    *Void
	pageRangeOpenEndedRunsToTheLastPage                   *Void
	pageRangeRejectsInvalidBounds                         *Void
	pngNamesEveryPageWithFourDigits                       *Void
	pngNarrowedRangeKeepsFourDigitNames                   *Void
	pngSinglePageIsStillNumbered                          *Void
	psHoldsEveryPageInOneFile                             *Void
	renderConcurrencyAppliesToEveryPerPageFormat          *Void
	renderConcurrencyMatchesSerialOutput                  *Void
	renderSettingsRejectNonPositiveValues                 *Void
	reportsOpenAnEncryptedDocumentWithThePassword         *Void
	scaleToOverridesDpi                                   *Void
	signaturesReportsAnUnsignedDocumentInsteadOfFailing   *Void
	splitAndMergeCannotOpenAnEncryptedDocument            *Void
	splitNarrowsToThePageRange                            *Void
	splitThenMergeRoundTripsTheDocument                   *Void
	splitWritesOnePdfPerPage                              *Void
	svgWritesOneVectorFilePerPage                         *Void
	textOnImageOnlyPdfReturnsNothing                      *Void
	textReproducesTextLayerExactly                        *Void
	tsvRowsCarryPageNumbersAndWordGeometry                *Void
	txtMatchesText                                        *Void
	untrustedIndexIsRejectedWithoutApkKey                 *Void
	vectorFormatsIgnoreRasterOnlySettings                 *Void
	versionReportsPopplerRelease                          *Void
	withFontsPutsFaceWhereFontconfigFindsIt               *Void
	withoutAnnotationsRemovesTheAnnotationLayer           *Void
}

func (r *Tests) WithGraphQLQuery(q *querybuilder.Selection) *Tests {
	return &Tests{
		query: q,
	}
}

// TestsAllOpts contains options for Tests.All
type TestsAllOpts struct {
	// Maximum number of tests to run concurrently. Zero fans out unbounded.
	Parallel int
}

// All runs every pdf-module test in parallel.
//
// The fan-out is unbounded by default. Unlike the tesseract suite, which had to
// be capped because an unbounded tesseract sizes its OpenMP teams by CPU count
// and multiplied the concurrency rather than sharing it (#226), poppler's tools
// are single-threaded: twenty of them contend for cores the way any other
// oversubscribed workload does. The cap stays available for a host that wants a
// narrower slice.
func (r *Tests) All(ctx context.Context, opts ...TestsAllOpts) error {
	if r.all != nil {
		return nil
	}
	q := r.query.Select("all")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// ApkAuthInstallsFromAuthenticatedRepository asserts credentials reach the
// fetch, and that they reach it without becoming part of the image.
//
// The second half is the reason the option takes a Secret. A mirror password
// spelled into a repository URL would land in /etc/apk/repositories, in every
// apk message quoting it, and in the layer a caller exports — so all three
// places are searched for it here, and the message is checked to be one that
// names the repository at all, or its silence about the password would prove
// nothing.
func (r *Tests) ApkAuthInstallsFromAuthenticatedRepository(ctx context.Context) error {
	if r.apkAuthInstallsFromAuthenticatedRepository != nil {
		return nil
	}
	q := r.query.Select("apkAuthInstallsFromAuthenticatedRepository")

	return q.Execute(ctx)
}

// ApkRepositoryAssemblesWorkingToolchainFromMirror asserts the image can be built
// entirely out of a caller-supplied repository and that what comes out of it
// works, which is the whole point of the option.
//
// Three things are checked rather than one, because this module's packages fail
// in three different ways. A missing poppler fails the build outright, so
// Version covers it. A poppler that installed but cannot run fails the
// conversion, so the text of the ledger covers that. And a missing font fails
// nothing at all — poppler substitutes what fontconfig offers, which with no
// family installed is nothing, and the page renders blank and exits 0. Only the
// pixels say so.
func (r *Tests) ApkRepositoryAssemblesWorkingToolchainFromMirror(ctx context.Context) error {
	if r.apkRepositoryAssemblesWorkingToolchainFromMirror != nil {
		return nil
	}
	q := r.query.Select("apkRepositoryAssemblesWorkingToolchainFromMirror")

	return q.Execute(ctx)
}

// ApkRepositoryReplacesImageDefaults asserts the first WithApkRepository
// replaces the image's repository list rather than appending to it, which is
// what makes every other test here mean what it says: with the CDN still in the
// file, an install that quietly came from dl-cdn.alpinelinux.org is
// indistinguishable from one that came from the mirror.
//
// It is also the assertion the air-gapped network needs on its own terms. A
// surviving default there is not a harmless second choice — it is a repository
// apk consults and waits on until it times out. So the assertion is on the
// file, and it is that the CDN is *gone*.
func (r *Tests) ApkRepositoryReplacesImageDefaults(ctx context.Context) error {
	if r.apkRepositoryReplacesImageDefaults != nil {
		return nil
	}
	q := r.query.Select("apkRepositoryReplacesImageDefaults")

	return q.Execute(ctx)
}

// AttachmentsReportsPopplersRefusalOfPathBearingNames asserts what happens to a
// document that names an attachment with a path in it, and asserts the failure
// carries what a caller needs to get the rest of the attachments anyway.
//
// The behaviour is poppler's and it is coarse: one such name makes `-saveall`
// refuse the *whole* extraction with `Preventing directory traversal`, so the
// perfectly ordinary second attachment in this fixture comes back not at all. The
// module cannot fix that — the name is the document's — so what it can do is say
// which document did it, list the names, and point at the tool that fetches them
// one at a time. The names are asserted for that reason: they are the argument
// `pdfdetach -savefile` needs, and without them the message is a dead end.
func (r *Tests) AttachmentsReportsPopplersRefusalOfPathBearingNames(ctx context.Context) error {
	if r.attachmentsReportsPopplersRefusalOfPathBearingNames != nil {
		return nil
	}
	q := r.query.Select("attachmentsReportsPopplersRefusalOfPathBearingNames")

	return q.Execute(ctx)
}

// AttachmentsReturnsEveryEmbeddedFileOrSaysThereAreNone asserts both halves of
// what the function promises: every file the document attached, under the name
// the document gave it, and an answer a caller can act on for a document that
// attached nothing.
//
// Two attachments is the minimum that tests "every" — one would be satisfied by
// an implementation that saved the first and stopped — and their contents are
// read rather than their names counted, because a name is not evidence the right
// bytes landed under it.
//
// The names are the fixture's own and are deliberately *not* the page-style
// contract the rest of this module's directories honour. An attachment's name is
// data: it is what the producer called the file and what a consumer looks for, so
// `invoice.xml` staying `invoice.xml` is the assertion, not a defect in the
// naming discipline.
//
// The empty case is refused rather than returned as an empty directory. pdfdetach
// exits 0 for a document with no attachments, so the directory would say nothing
// about which of the two happened, and the message names `pdfdetach -list` as the
// way to ask without failing.
func (r *Tests) AttachmentsReturnsEveryEmbeddedFileOrSaysThereAreNone(ctx context.Context) error {
	if r.attachmentsReturnsEveryEmbeddedFileOrSaysThereAreNone != nil {
		return nil
	}
	q := r.query.Select("attachmentsReturnsEveryEmbeddedFileOrSaysThereAreNone")

	return q.Execute(ctx)
}

// AuthenticatedRepositoryIsRejectedWithoutApkAuth asserts the authenticated
// mirror really is authenticated — that the test above passes because the
// credentials were supplied and used, and not because the server never asked
// for any. Both installs run against the one mirror, so WithApkAuth is the
// only difference between them.
func (r *Tests) AuthenticatedRepositoryIsRejectedWithoutApkAuth(ctx context.Context) error {
	if r.authenticatedRepositoryIsRejectedWithoutApkAuth != nil {
		return nil
	}
	q := r.query.Select("authenticatedRepositoryIsRejectedWithoutApkAuth")

	return q.Execute(ctx)
}

// BboxCarriesOneBoxPerWord asserts Bbox reports the page's size and one box per
// word, at the coordinates the document itself draws the words at.
//
// The coordinates are the whole point of the function, so they are checked and
// not merely counted. ledgerPdf sets its pages with `/F1 24 Tf`, `72 680 Td` and
// `40 TL`, so every number poppler can print here is derivable from the fixture:
// the first word of a line starts at x=72, and a line's box runs from the
// baseline less Helvetica's ascender to the baseline plus its descender, measured
// down from the top of the 792-point page. A test that asserted the boxes were
// non-empty would pass just as well on boxes that were all the same.
//
// The absence of layout boxes is asserted too, because that is what `withLayout`
// is the difference between: a plain -bbox report carries words directly under
// the page, with no flow, block or line around them.
func (r *Tests) BboxCarriesOneBoxPerWord(ctx context.Context) error {
	if r.bboxCarriesOneBoxPerWord != nil {
		return nil
	}
	q := r.query.Select("bboxCarriesOneBoxPerWord")

	return q.Execute(ctx)
}

// BboxWithLayoutAddsBlockAndLineBoxes asserts withLayout wraps the same word
// boxes in the block and line boxes poppler groups them into.
//
// Both halves matter. The words have to be the same words at the same
// coordinates, because the layout report is meant to be the plain one with more
// structure and not a differently measured one — so the two reports' words are
// compared box for box. And the boxes that were added have to mean something:
// each line's box is asserted to be exactly the union of the words under it, and
// each block's the union of its lines. A test that only counted `block` elements
// would pass on boxes that were all the page.
//
// ledgerPdf is the fixture for it because its two lines land in two blocks: the
// 40-point leading against a 22.2-point line is a gap poppler reads as a
// paragraph break, so the block grouping is observable rather than degenerate.
func (r *Tests) BboxWithLayoutAddsBlockAndLineBoxes(ctx context.Context) error {
	if r.bboxWithLayoutAddsBlockAndLineBoxes != nil {
		return nil
	}
	q := r.query.Select("bboxWithLayoutAddsBlockAndLineBoxes")

	return q.Execute(ctx)
}

// ColorModesProduceDifferentPixels asserts the three colour modes render three
// different images.
//
// It measures pixels rather than the PNG header, because the header does not
// move: poppler's PNG writer emits 8-bit RGB for all three modes, so a grayscale
// render is an RGB image whose channels happen to be equal and a monochrome one
// an RGB image whose pixels happen to be pure black or white. Asserting on bit
// depth would pass identically for all three and prove nothing.
//
// The three properties are mutually exclusive by construction: colour keeps
// chroma, grey drops chroma but keeps mid-tones, and mono drops both — flat tones
// are dithered into black and white rather than averaged into grey.
func (r *Tests) ColorModesProduceDifferentPixels(ctx context.Context) error {
	if r.colorModesProduceDifferentPixels != nil {
		return nil
	}
	q := r.query.Select("colorModesProduceDifferentPixels")

	return q.Execute(ctx)
}

// ContainerCarriesEveryPopplerBinaryAndTheFont asserts the assembled image is
// the escape hatch it claims to be: all thirteen poppler binaries on PATH, and
// the substitute font family installed.
//
// The font half is not a packaging detail. Without a font installed poppler has
// nothing to substitute for a PDF that names a base-14 face without embedding
// it, and renders the page blank while exiting 0 — a silent wrong answer, which
// is the failure mode this assertion exists to keep out.
func (r *Tests) ContainerCarriesEveryPopplerBinaryAndTheFont(ctx context.Context) error {
	if r.containerCarriesEveryPopplerBinaryAndTheFont != nil {
		return nil
	}
	q := r.query.Select("containerCarriesEveryPopplerBinaryAndTheFont")

	return q.Execute(ctx)
}

// DefaultApkConfigurationIsUntouched asserts an image built without any of
// these options is the image this module built before they existed: the stock
// repository list, and no credential plumbing at all.
//
// It is the guard against the cheap implementation of all of the above —
// writing a repositories file, or setting the credential variable,
// unconditionally — which would work for the mirror and rebuild the world for
// every existing caller.
func (r *Tests) DefaultApkConfigurationIsUntouched(ctx context.Context) error {
	if r.defaultApkConfigurationIsUntouched != nil {
		return nil
	}
	q := r.query.Select("defaultApkConfigurationIsUntouched")

	return q.Execute(ctx)
}

// DisablePageBreaksControlsFormFeeds asserts the page break is there by default
// and gone when asked for.
//
// The option is spelled as a disable rather than as a `pageBreaks bool`
// defaulting to true because a `Go SDK — the zero value is dropped before it reaches the API — so the
// affirmative spelling would have produced an option no caller could turn off.
// That makes the second half of this test the one that would have caught it.
func (r *Tests) DisablePageBreaksControlsFormFeeds(ctx context.Context) error {
	if r.disablePageBreaksControlsFormFeeds != nil {
		return nil
	}
	q := r.query.Select("disablePageBreaksControlsFormFeeds")

	return q.Execute(ctx)
}

// DpiDefaultsToOneFiftyAndScalesWithTheSetting asserts the default resolution is
// the documented 150 and that WithDpi multiplies the pixels accordingly.
//
// The default is asserted against the page's own geometry rather than against a
// remembered pixel count, so the assertion says "150 dpi of a US Letter page"
// rather than "1275 by 1650" — which is the claim the documentation actually
// makes.
func (r *Tests) DpiDefaultsToOneFiftyAndScalesWithTheSetting(ctx context.Context) error {
	if r.dpiDefaultsToOneFiftyAndScalesWithTheSetting != nil {
		return nil
	}
	q := r.query.Select("dpiDefaultsToOneFiftyAndScalesWithTheSetting")

	return q.Execute(ctx)
}

// EmbeddedImagesKeepsTheOriginalEncoding asserts what each ImageFormat member
// does to an image that already has an encoding, and asserts the one that keeps
// it does so byte for byte.
//
// Byte equality is the only assertion that actually says "kept". A `.jpg` that
// decodes to the right dimensions would also come out of a re-encode, and a
// re-encode is precisely what ORIGINAL exists to avoid — so the expectation here
// is read out of the fixture itself: gallery.pdf's photograph is JPEG bytes
// hex-armored inside the file, and hex-decoding them gives exactly what poppler
// should have written.
//
// The extensions carry the rest of the claim. ORIGINAL falls back to netpbm for
// the two unencoded strips, which is the part of that member most likely to
// surprise a caller and therefore the part most worth pinning; ALL is the same
// member with PNG as the fallback instead, which is the whole difference between
// the two; and PNG and TIFF re-encode everything, the photograph included.
func (r *Tests) EmbeddedImagesKeepsTheOriginalEncoding(ctx context.Context) error {
	if r.embeddedImagesKeepsTheOriginalEncoding != nil {
		return nil
	}
	q := r.query.Select("embeddedImagesKeepsTheOriginalEncoding")

	return q.Execute(ctx)
}

// EmbeddedImagesNamesEveryImageAndNarrowsToThePageRange asserts both numbers in
// an extracted image's name mean what the contract says, and asserts a document
// with nothing to extract is told so rather than handed an empty directory.
//
// The names are checked against the images' *dimensions*, not merely counted.
// gallery.pdf's three images are three different sizes on purpose, so decoding
// each one says which image landed under which name — an assertion a numbering
// that shuffled or off-by-oned the files would fail and an entry-count assertion
// would not.
//
// The page range is where the two numbers part company. The page number is the
// source document's, like everywhere else in this module, so page two's image
// stays `page-0002` when page two is all that was asked for. The image index is
// not: it is poppler's count for the run, so it restarts at zero. That is
// asserted rather than worked around because it is the surprising half of the
// contract, and a caller cross-referencing `pdfimages -list` needs to know which
// number moved.
func (r *Tests) EmbeddedImagesNamesEveryImageAndNarrowsToThePageRange(ctx context.Context) error {
	if r.embeddedImagesNamesEveryImageAndNarrowsToThePageRange != nil {
		return nil
	}
	q := r.query.Select("embeddedImagesNamesEveryImageAndNarrowsToThePageRange")

	return q.Execute(ctx)
}

// EmbeddedImagesReturnsTheStoredImageNotTheRenderedPage asserts the distinction the
// function is named for: what comes back is the image object the document
// carries, not a rasterization of the page it sits on.
//
// The proof is the pixel dimensions, and it is only a proof because the two
// numbers cannot be confused. scanPdf's image is 16x16; the US Letter page it is
// drawn across covers 1275x1650 at the module's default resolution. A function
// that quietly rasterized the page would return an image 79 times wider, and a
// dimension assertion catches that where an entry-count assertion would not — one
// page carrying one image produces one file either way.
//
// The render is fetched here rather than hardcoded so the comparison is against
// what this module actually produces, which is the thing a caller would otherwise
// mistake this for.
func (r *Tests) EmbeddedImagesReturnsTheStoredImageNotTheRenderedPage(ctx context.Context) error {
	if r.embeddedImagesReturnsTheStoredImageNotTheRenderedPage != nil {
		return nil
	}
	q := r.query.Select("embeddedImagesReturnsTheStoredImageNotTheRenderedPage")

	return q.Execute(ctx)
}

// EncryptedDocumentNeedsThePassword asserts an encrypted document opens with the
// password it was encrypted under, fails without one, and says so by naming the
// encryption.
//
// The message matters as much as the failure. poppler reports every wrong
// password identically — `Incorrect password`, whether one was supplied or not,
// because it tries the empty password when given none — so passing that through
// would tell a caller who supplied nothing that what they supplied was wrong.
// Both branches are asserted here for that reason.
//
// The passwords are generated per run with dag.Random().Sha256 rather than
// written down, so no password literal ever enters git, and reach qpdf and
// poppler alike through the environment rather than argv: a password in argv is
// visible in every Dagger trace, which is exactly what the module's own posture
// avoids.
func (r *Tests) EncryptedDocumentNeedsThePassword(ctx context.Context) error {
	if r.encryptedDocumentNeedsThePassword != nil {
		return nil
	}
	q := r.query.Select("encryptedDocumentNeedsThePassword")

	return q.Execute(ctx)
}

// EpsWritesEveryPageOfTheDocument asserts Eps turns a twelve-page
// document into twelve EPS files rather than into a failure.
//
// This is the criterion that a multi-page source never silently loses pages, and
// for EPS the failure it guards is not silent at all: `pdftocairo -eps` handed a
// multi-page document writes nothing and exits 99 with `EPS files can only
// contain one page.` A single invocation would make Eps unusable for every
// document with a second page in it, so the page count here is the assertion
// that the per-page loop is what runs.
//
// Each file is then checked to be an EPS in its own right — the EPSF version
// header, and exactly one page in it — because a loop that wrote twelve copies
// of page one would satisfy the names alone.
func (r *Tests) EpsWritesEveryPageOfTheDocument(ctx context.Context) error {
	if r.epsWritesEveryPageOfTheDocument != nil {
		return nil
	}
	q := r.query.Select("epsWritesEveryPageOfTheDocument")

	return q.Execute(ctx)
}

// ExtractionsOpenAnEncryptedDocumentWithThePassword asserts the passwords reach
// both extractions, which is the property that separates them from Split and
// Merge.
//
// It is worth an assertion of its own precisely because the module already has
// two functions where it is false. pdfseparate and pdfunite take no password at
// all, so `WithUserPassword(...).Split()` is a call that cannot be made to work
// and says so; pdfimages and pdfdetach both take `-upw` and `-opw`, so the same
// document that Split refuses these two open. Nothing about the two families
// looks different from the outside, and only a test says which is which.
//
// Both branches are asserted for each: refused by naming the encryption when no
// password was supplied — poppler says `Incorrect password` whether one was given
// or not — and the full result when it was.
func (r *Tests) ExtractionsOpenAnEncryptedDocumentWithThePassword(ctx context.Context) error {
	if r.extractionsOpenAnEncryptedDocumentWithThePassword != nil {
		return nil
	}
	q := r.query.Select("extractionsOpenAnEncryptedDocumentWithThePassword")

	return q.Execute(ctx)
}

// FontsNarrowsToThePageRange asserts WithPageRange reaches pdffonts, and that a
// range it cannot honour is refused the way every other one is.
//
// Which faces a document needs is a question about pages, so this is not a
// cosmetic option: a report of pages 1 through 3 that listed a face used only on
// page 40 would say the render depends on a font it does not, and one that
// dropped a face used on page 2 would say the opposite. fontsPdf is built for
// it, its two pages naming different faces, because narrowing a report of
// ledgerPdf — every page of which names the same Helvetica — changes nothing at
// all and would pass against a module that ignored the bounds entirely.
func (r *Tests) FontsNarrowsToThePageRange(ctx context.Context) error {
	if r.fontsNarrowsToThePageRange != nil {
		return nil
	}
	q := r.query.Select("fontsNarrowsToThePageRange")

	return q.Execute(ctx)
}

// FontsReportsWhetherEachFaceIsEmbedded asserts Fonts surfaces pdffonts' table
// and that the `emb` column in it says what it is supposed to say.
//
// ledgerPdf is the shape the module's font install exists for: its pages name
// Helvetica without embedding it, so poppler has to ask fontconfig for a
// substitute, and with no font installed there is nothing to substitute — the
// page renders blank and the command exits 0. `Helvetica … no` is what that
// silent failure looks like before it happens, which is the whole reason a
// pipeline asks for this report.
//
// fontsPdf carries the other half of the column. Its Type 3 font is embedded by
// construction, so the report has to read `yes` for it; without that contrast
// the assertion would pass just as well on a report that said `no` about
// everything, including one produced by a module that had hardcoded the answer.
func (r *Tests) FontsReportsWhetherEachFaceIsEmbedded(ctx context.Context) error {
	if r.fontsReportsWhetherEachFaceIsEmbedded != nil {
		return nil
	}
	q := r.query.Select("fontsReportsWhetherEachFaceIsEmbedded")

	return q.Execute(ctx)
}

// GeometryOfAnImageOnlyPdfReportsPagesWithoutWords asserts a PDF with no text
// layer produces a well-formed report of a page with nothing on it, and does not
// fail.
//
// It is the same boundary with the tesseract module that TextOnImageOnlyPdfReturnsNothing
// draws, and it needs its own assertion because the failure mode here is louder:
// poppler writes `no word list` to *stderr* for such a page and exits 0, having
// written a perfectly good report to the output file. A module that read stderr as
// a diagnostic, or that treated the absence of words as a document it could not
// open, would turn the signal to go and rasterize this document into an error.
//
// The page element still has to be there and still has to state its size, because
// that is what distinguishes a page carrying no text from a document that was
// never read.
func (r *Tests) GeometryOfAnImageOnlyPdfReportsPagesWithoutWords(ctx context.Context) error {
	if r.geometryOfAnImageOnlyPdfReportsPagesWithoutWords != nil {
		return nil
	}
	q := r.query.Select("geometryOfAnImageOnlyPdfReportsPagesWithoutWords")

	return q.Execute(ctx)
}

// HtmlCarriesPageMarkupAndItsImages asserts both halves of what Html promises:
// the page's text as markup, and the images the page carries extracted beside it
// and referenced by a path that resolves.
//
// The relative reference is the half that is easy to get wrong and impossible to
// notice. pdftohtml writes the output name it was given straight into every `img
// src`, so an absolute output base — the obvious way to write into a staging
// directory — produces markup whose images resolve only on the machine that
// rendered them, and which still passes every assertion about entry names. The
// conversion runs with the output directory as its working directory for exactly
// this reason, and the `src` check here is what holds it there.
//
// Two fixtures are needed because no one page is both: ledger.pdf is text and no
// images, scan.pdf is one image and no text.
func (r *Tests) HTMLCarriesPageMarkupAndItsImages(ctx context.Context) error {
	if r.htmlCarriesPageMarkupAndItsImages != nil {
		return nil
	}
	q := r.query.Select("htmlCarriesPageMarkupAndItsImages")

	return q.Execute(ctx)
}

// A unique identifier for this Tests.
func (r *Tests) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Tests) XXX_GraphQLType() string {
	return "Tests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Tests) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Tests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Tests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Tests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Tests{query: selectNode(dag.query, id, "Tests")}
	return nil
}

// InfoReportsPageCountAndSize asserts Info surfaces what pdfinfo knows, and
// PageCount reads the page count back out of it.
//
// They are asserted together because the second is defined in terms of the
// first: PageCount parses Info's `Pages:` line, so a change to how Info is
// captured that broke the parse would otherwise show up only in whatever used
// PageCount next.
func (r *Tests) InfoReportsPageCountAndSize(ctx context.Context) error {
	if r.infoReportsPageCountAndSize != nil {
		return nil
	}
	q := r.query.Select("infoReportsPageCountAndSize")

	return q.Execute(ctx)
}

// JpegAndTiffFollowTheSameContract asserts the other two raster formats honour
// the naming contract and the geometry PNG does, differing only in the extension
// poppler chose for them.
//
// `-jpeg` writes `.jpg` and `-tiff` writes `.tif`, which are poppler's spellings
// and not this module's: a caller building a path from the function's name would
// get them wrong, so they are part of the documented contract.
func (r *Tests) JpegAndTiffFollowTheSameContract(ctx context.Context) error {
	if r.jpegAndTiffFollowTheSameContract != nil {
		return nil
	}
	q := r.query.Select("jpegAndTiffFollowTheSameContract")

	return q.Execute(ctx)
}

// LayoutModesProduceDifferentOrderings asserts the three layout modes are three
// different answers rather than degrees of one, on a page where they have to
// disagree.
//
// columns.pdf is built so they cannot coincide: two columns of prose, with the
// content stream written row-major — left cell, right cell, next row — while the
// page reads column-major. So reading order visits the whole left column first,
// content-stream order alternates between the columns from the first line, and
// physical layout puts the two columns side by side on one output line. A fixture
// whose stream order matched its reading order would let two of these three pass
// on the same output.
func (r *Tests) LayoutModesProduceDifferentOrderings(ctx context.Context) error {
	if r.layoutModesProduceDifferentOrderings != nil {
		return nil
	}
	q := r.query.Select("layoutModesProduceDifferentOrderings")

	return q.Execute(ctx)
}

// MergePreservesTheOrderOfItsSources asserts the merged document's pages come
// out in the order the slice named them, which is the whole reason Merge takes
// an ordered slice rather than a directory.
//
// The sources are deliberately handed over out of page order — 3, 1, 2 — because
// any order-preserving implementation and any order-losing one agree on a slice
// that was already sorted. Reading the text back is what says the pages landed
// where they were put: the page count alone would pass on a merge that shuffled
// them.
func (r *Tests) MergePreservesTheOrderOfItsSources(ctx context.Context) error {
	if r.mergePreservesTheOrderOfItsSources != nil {
		return nil
	}
	q := r.query.Select("mergePreservesTheOrderOfItsSources")

	return q.Execute(ctx)
}

// MergeRejectsWhatItCannotMerge asserts the two ways a merge goes wrong are
// reported by naming the argument that was wrong.
//
// The empty slice is a caller error with no useful answer — there is no document
// to return and no empty PDF worth inventing — and pdfunite's own answer to it is
// its usage text, which describes a command line the caller never wrote. The
// module refuses it before the container starts, for that reason.
//
// The unreadable source is the case the mount legend exists for. pdfunite names
// the file it could not read, and the name it uses is this module's mount path,
// so without the legend the one piece of information identifying which argument
// was at fault is a path the caller has never seen.
func (r *Tests) MergeRejectsWhatItCannotMerge(ctx context.Context) error {
	if r.mergeRejectsWhatItCannotMerge != nil {
		return nil
	}
	q := r.query.Select("mergeRejectsWhatItCannotMerge")

	return q.Execute(ctx)
}

// MetadataReturnsTheXmpPacketOrSaysThereIsNone asserts both halves of what
// Metadata answers, because the interesting one is the absence.
//
// The packet is asserted to be the packet and not pdfinfo's ordinary report of
// the same document: `pdfinfo -meta` prints the XMP alone, so a module that
// dropped the flag would return a report that still mentions a title and still
// looks like metadata. metadataPdf's Info dictionary carries a deliberately
// different title for exactly that reason — the wrong one showing up is what
// makes the substitution visible.
//
// The absence is the half that needs a decision. poppler prints nothing at all
// and exits 0 for a document with no XMP, and an empty string is
// indistinguishable from a function that did not run, so the module answers with
// a line naming the absence and pointing at the report that does carry the
// document's metadata.
func (r *Tests) MetadataReturnsTheXmpPacketOrSaysThereIsNone(ctx context.Context) error {
	if r.metadataReturnsTheXmpPacketOrSaysThereIsNone != nil {
		return nil
	}
	q := r.query.Select("metadataReturnsTheXmpPacketOrSaysThereIsNone")

	return q.Execute(ctx)
}

// PageRangeNarrowsEveryPerPageFormat asserts the page bounds reach Svg, Eps and
// Html, in all three of the shapes a range comes in.
//
// The per-page loop resolves the bounds itself rather than handing poppler `-f`
// and `-l`, so none of this follows from the raster path already honouring them.
// The open-ended case is the one that exercises the resolution: a zero last is
// the document's page count read inside the same exec that renders, and a loop
// that mishandled it would render nothing at all and return an empty directory
// rather than fail.
//
// The numbers are the source document's page numbers and not positions within
// the range, which is why pages 4 through 6 come out `page-0004` through
// `page-0006` — the same promise the raster contract makes, so a page stays
// traceable to the page it came from whichever format it was rendered to.
func (r *Tests) PageRangeNarrowsEveryPerPageFormat(ctx context.Context) error {
	if r.pageRangeNarrowsEveryPerPageFormat != nil {
		return nil
	}
	q := r.query.Select("pageRangeNarrowsEveryPerPageFormat")

	return q.Execute(ctx)
}

// PageRangeNarrowsText asserts WithPageRange narrows extraction to the pages it
// names, and that the bounds are the 1-based inclusive ones poppler uses rather
// than an offset and a length.
func (r *Tests) PageRangeNarrowsText(ctx context.Context) error {
	if r.pageRangeNarrowsText != nil {
		return nil
	}
	q := r.query.Select("pageRangeNarrowsText")

	return q.Execute(ctx)
}

// PageRangeNarrowsTheGeometryOutputs asserts WithPageRange narrows Bbox and Tsv
// to the pages it names, in all three shapes the two functions come in.
//
// The two formats answer "which page is this" differently, and that difference is
// the reason this test checks the narrowing on both rather than trusting one. A
// `-bbox` page element carries a width and a height and no number at all, so the
// only thing that ties a narrowed report back to the document is the order of its
// pages and the words on them — which is what the marker words are checked for
// here. A TSV row names its page outright, and names it with the page's number in
// the *whole* document rather than its position in the range: pages 4 through 6
// come back as 4, 5 and 6, not as 1, 2 and 3.
func (r *Tests) PageRangeNarrowsTheGeometryOutputs(ctx context.Context) error {
	if r.pageRangeNarrowsTheGeometryOutputs != nil {
		return nil
	}
	q := r.query.Select("pageRangeNarrowsTheGeometryOutputs")

	return q.Execute(ctx)
}

// PageRangeOpenEndedRunsToTheLastPage asserts a zero last means "to the end",
// which is the only way to name an open-ended range without first asking how
// many pages the document has.
func (r *Tests) PageRangeOpenEndedRunsToTheLastPage(ctx context.Context) error {
	if r.pageRangeOpenEndedRunsToTheLastPage != nil {
		return nil
	}
	q := r.query.Select("pageRangeOpenEndedRunsToTheLastPage")

	return q.Execute(ctx)
}

// PageRangeRejectsInvalidBounds asserts every way of getting a range wrong is
// reported by naming the bound that was wrong.
//
// The out-of-document cases are the ones that justify checking at all: poppler
// renders nothing for them and exits 0, so a caller who asked for page 20 of a
// 12-page document would otherwise get an empty result indistinguishable from a
// document with no text in it.
func (r *Tests) PageRangeRejectsInvalidBounds(ctx context.Context) error {
	if r.pageRangeRejectsInvalidBounds != nil {
		return nil
	}
	q := r.query.Select("pageRangeRejectsInvalidBounds")

	return q.Execute(ctx)
}

// PngNamesEveryPageWithFourDigits asserts the page-naming contract on a
// document long enough for pdftoppm to disagree with it.
//
// pdftoppm pads a page number to the width of the document's page count, so a
// twelve-page document is named `page-01.png` through `page-12.png` and a
// one-page one `page-1.png`. Neither shape is the contract, and the widths are
// what make a bare sort across two documents' output wrong while a sort within
// either one is right — the tesseract module's Batch sorts what it is handed and
// has no way to know which width it is holding. Asserting the full ordered list
// covers both halves of the promise: the names, and that lexicographic order is
// page order.
func (r *Tests) PngNamesEveryPageWithFourDigits(ctx context.Context) error {
	if r.pngNamesEveryPageWithFourDigits != nil {
		return nil
	}
	q := r.query.Select("pngNamesEveryPageWithFourDigits")

	return q.Execute(ctx)
}

// PngNarrowedRangeKeepsFourDigitNames asserts a page range narrows the render
// and leaves the naming alone.
//
// Nine pages is the interesting count: pdftoppm would name a nine-page
// *document* `page-1.png`, and the same nine pages taken out of this twelve-page
// one `page-01.png`, so the width it chose depends on the document rather than on
// what was rendered. Both normalize to the same four digits.
//
// The numbers are the source document's page numbers and not positions within
// the range, which is why the second case starts at `page-0004.png`. That keeps a
// rendered page traceable back to the page it came from.
func (r *Tests) PngNarrowedRangeKeepsFourDigitNames(ctx context.Context) error {
	if r.pngNarrowedRangeKeepsFourDigitNames != nil {
		return nil
	}
	q := r.query.Select("pngNarrowedRangeKeepsFourDigitNames")

	return q.Execute(ctx)
}

// PngSinglePageIsStillNumbered asserts a render of one page is `page-0001.png`
// and not `page.png`.
//
// Both routes to a single page are checked, because pdftoppm treats them
// differently: a one-page document is where it drops to a single-digit number,
// and historically to no number at all, while a one-page range of a longer
// document keeps the longer document's width. A consumer globbing for
// `page-*.png` finds nothing in the first case and a caller indexing by name
// finds the wrong file in the second.
func (r *Tests) PngSinglePageIsStillNumbered(ctx context.Context) error {
	if r.pngSinglePageIsStillNumbered != nil {
		return nil
	}
	q := r.query.Select("pngSinglePageIsStillNumbered")

	return q.Execute(ctx)
}

// PsHoldsEveryPageInOneFile asserts Ps returns one PostScript document carrying
// every page, and that the page range narrows it.
//
// The return type is the claim under test. PostScript is a multi-page format
// with a document-level `%%Pages:` count and a `%%Page:` marker per page, so a
// directory of one-page fragments would be the wrong answer even though it would
// look tidier beside Svg and Eps. Counting the markers is what says the pages
// reached the file rather than only the header saying they did.
func (r *Tests) PsHoldsEveryPageInOneFile(ctx context.Context) error {
	if r.psHoldsEveryPageInOneFile != nil {
		return nil
	}
	q := r.query.Select("psHoldsEveryPageInOneFile")

	return q.Execute(ctx)
}

// RenderConcurrencyAppliesToEveryPerPageFormat asserts the bound reaches the
// vector family too, and that the pages those formats write are assembled the
// same way whatever the scheduling did.
//
// Html is the one worth checking rather than assuming. Its pages are not the
// only thing in the directory — a page carrying images gets them beside its
// markup under pdftohtml's own names — so it is the format whose assembly takes
// the whole of each render's output rather than one named file, and the format
// where a fan-out could plausibly lose or collide a file.
//
// Eps is compared file by file rather than by digest, and that is not a weaker
// assertion — it is the only one that has ever meant anything here. **Cairo
// stamps a wall clock into every EPS and PS it writes**, as a `%%CreationDate`
// DSC comment on line three, and it honours neither `SOURCE_DATE_EPOCH` nor any
// pdftocairo flag (measured against the pinned cairo 1.18.4). Until #370 the two
// bounds produced *literally the same* Dagger query — one exec per page at every
// bound — so the digests matched because they were one cache entry, and this case
// asserted nothing about scheduling at all. Now that the bound decides the
// slicing, the two renders are different execs at different wall-clock instants,
// and the digests cannot match however deterministic the rendering is. Comparing
// the bytes with that one line held aside is what actually tests the claim: same
// names, same rendered content, one field that is a timestamp by construction.
//
// Svg and Html keep the digest comparison, cairo's SVG surface and pdftohtml
// writing no date.
func (r *Tests) RenderConcurrencyAppliesToEveryPerPageFormat(ctx context.Context) error {
	if r.renderConcurrencyAppliesToEveryPerPageFormat != nil {
		return nil
	}
	q := r.query.Select("renderConcurrencyAppliesToEveryPerPageFormat")

	return q.Execute(ctx)
}

// RenderConcurrencyMatchesSerialOutput asserts a document rendered several pages
// at a time produces exactly what the same document produces one page at a time,
// and that a bound that would render nothing is refused.
//
// Byte equality is the whole promise of the knob: concurrency is allowed to
// change how long a render takes and nothing else. What it pins now that the
// bound also decides how the pages are *sliced* into execs is that the slicing
// is invisible in the answer — the same twelve pages come back whether they were
// rendered by one exec, four, five or twelve, assembled from directories that
// finished in whatever order they finished in. The digest covers the names and
// the bytes together.
//
// Five is in the list because twelve does not divide by it: the slices come out
// 3, 3, 2, 2, 2, which is the shape an off-by-one in the partition drops a page
// from. A bound wider than the document is there because it is the ordinary case
// for a short document on a large machine — the default is one page per CPU, and
// most documents are shorter than the core count — and it is the shape that must
// not produce empty execs.
func (r *Tests) RenderConcurrencyMatchesSerialOutput(ctx context.Context) error {
	if r.renderConcurrencyMatchesSerialOutput != nil {
		return nil
	}
	q := r.query.Select("renderConcurrencyMatchesSerialOutput")

	return q.Execute(ctx)
}

// RenderSettingsRejectNonPositiveValues asserts a resolution or a pixel bound
// that cannot mean anything is refused by naming the argument.
//
// Left to poppler these arrive much later as a complaint about `-r` or
// `-scale-to`, which names a flag the caller never wrote.
func (r *Tests) RenderSettingsRejectNonPositiveValues(ctx context.Context) error {
	if r.renderSettingsRejectNonPositiveValues != nil {
		return nil
	}
	q := r.query.Select("renderSettingsRejectNonPositiveValues")

	return q.Execute(ctx)
}

// ReportsOpenAnEncryptedDocumentWithThePassword asserts the document's password
// reaches all three reporting tools, and that each says the same thing without
// one.
//
// Each tool opens the document itself, so none of this follows from extraction
// or rendering already working: a password threaded into pdftotext's invocation
// and not into pdffonts' produces a module where a report on an encrypted
// document fails while everything else about it succeeds. Both branches are
// asserted for each, because the refusal is the half a caller reads — poppler
// reports every wrong password as `Incorrect password` whether one was supplied
// or not, so the message has to distinguish what the module knows and poppler
// does not.
func (r *Tests) ReportsOpenAnEncryptedDocumentWithThePassword(ctx context.Context) error {
	if r.reportsOpenAnEncryptedDocumentWithThePassword != nil {
		return nil
	}
	q := r.query.Select("reportsOpenAnEncryptedDocumentWithThePassword")

	return q.Execute(ctx)
}

// ScaleToOverridesDpi asserts WithScaleTo fixes the output's pixel size and wins
// over a resolution set alongside it.
//
// Both are set here on purpose: the override is implemented by leaving the
// resolution flag off the command line rather than by relying on poppler's own
// precedence, so this is the assertion that would catch the two being emitted
// together and whichever poppler happened to prefer winning silently.
func (r *Tests) ScaleToOverridesDpi(ctx context.Context) error {
	if r.scaleToOverridesDpi != nil {
		return nil
	}
	q := r.query.Select("scaleToOverridesDpi")

	return q.Execute(ctx)
}

// SignaturesReportsAnUnsignedDocumentInsteadOfFailing asserts the case almost
// every document is: no signatures, reported as a result.
//
// It is the assertion the function's exit-code handling exists for. pdfsig exits
// 2 for a document carrying no signatures, having printed exactly what it found,
// and the module's usual treatment of a non-zero exit — an error naming the
// failure — would turn the ordinary answer to an ordinary question into a broken
// pipeline. Reserving failure for the runs that failed is what makes this
// callable on documents whose signing status is what the caller is asking about.
//
// The NSS check is the other half. pdfsig writes `NSS_Init failed` to stderr in
// an image carrying no certificate database, which is every image this module
// builds, and a report assembled from both streams would carry that line into
// every caller's output as though it were something the document said.
func (r *Tests) SignaturesReportsAnUnsignedDocumentInsteadOfFailing(ctx context.Context) error {
	if r.signaturesReportsAnUnsignedDocumentInsteadOfFailing != nil {
		return nil
	}
	q := r.query.Select("signaturesReportsAnUnsignedDocumentInsteadOfFailing")

	return q.Execute(ctx)
}

// SplitAndMergeCannotOpenAnEncryptedDocument asserts the limitation these two
// carry that nothing else in the module does, and asserts it is reported as that
// rather than as a wrong password.
//
// pdfseparate and pdfunite take no `-upw` and no `-opw` — passing one is a usage
// error, not a wrong password — so an encrypted document is one they cannot be
// made to open. What poppler says about it is `Incorrect password`, the same
// sentence every other tool in the suite produces for a password that did not
// work, and the module's usual reading of that line names WithUserPassword. Here
// that would send a caller to a builder that changes nothing, which is why the
// password case is asserted alongside the passwordless one: both have to arrive
// at the same message.
func (r *Tests) SplitAndMergeCannotOpenAnEncryptedDocument(ctx context.Context) error {
	if r.splitAndMergeCannotOpenAnEncryptedDocument != nil {
		return nil
	}
	q := r.query.Select("splitAndMergeCannotOpenAnEncryptedDocument")

	return q.Execute(ctx)
}

// SplitNarrowsToThePageRange asserts the page bounds reach pdfseparate in all
// three of the shapes a range comes in, and that a range it cannot honour is
// refused before it runs.
//
// The refusal is the half worth asserting. Left to pdfseparate, a last bound past
// the end of the document is not caught up front at all: it separates every page
// it can and *then* fails with `Internal Error: Illegal pageNo: 13(12)`, so the
// caller gets a message about poppler's internals attached to a directory that
// was half written. Checking the bounds against the document first is what turns
// that into a sentence naming the builder and the page count.
func (r *Tests) SplitNarrowsToThePageRange(ctx context.Context) error {
	if r.splitNarrowsToThePageRange != nil {
		return nil
	}
	q := r.query.Select("splitNarrowsToThePageRange")

	return q.Execute(ctx)
}

// SplitThenMergeRoundTripsTheDocument asserts the two halves of this pair
// compose back into the document they started from.
//
// It is the assertion that says these are structural operations rather than
// conversions. Each one alone could pass its own tests while quietly dropping
// what it does not understand — a page's annotations, its size, the text layer
// under it — and the round trip is where that shows up: twelve separated pages
// put back together have to extract to the same text, in the same order, on
// pages of the same size.
//
// The names the split wrote are what the merge is driven by, in page order, which
// is also the practical shape of the pair: split, do something to the pages,
// merge the ones that survived.
func (r *Tests) SplitThenMergeRoundTripsTheDocument(ctx context.Context) error {
	if r.splitThenMergeRoundTripsTheDocument != nil {
		return nil
	}
	q := r.query.Select("splitThenMergeRoundTripsTheDocument")

	return q.Execute(ctx)
}

// SplitWritesOnePdfPerPage asserts Split turns a twelve-page document into
// twelve one-page PDFs named to the same contract every render family member
// honours.
//
// The names alone would pass against a splitter that wrote twelve copies of page
// one, so each file is opened and read: one page in it, and that page's own
// marker in the text. ledgerPdf's markers are what make that check possible —
// twelve pages of identical text would extract the same however they were
// shuffled.
//
// pdfseparate numbers with the width the caller's pattern asks for rather than
// with the document's page count, so the four-digit contract here is this
// module's and not a coincidence of the fixture's length.
func (r *Tests) SplitWritesOnePdfPerPage(ctx context.Context) error {
	if r.splitWritesOnePdfPerPage != nil {
		return nil
	}
	q := r.query.Select("splitWritesOnePdfPerPage")

	return q.Execute(ctx)
}

// SvgWritesOneVectorFilePerPage asserts Svg renders a multi-page document to one
// SVG per page, named to the page contract, carrying vector geometry.
//
// The per-page invocation is the whole point. `pdftocairo -svg` run once over a
// twelve-page document writes a single file — no page is dropped, but they are
// wrapped in the SVG 1.2 `<pageSet>`/`<page>` elements that essentially no
// renderer implements, so a browser, Inkscape or librsvg shows page one and
// silently discards the other eleven. The `<pageSet>` assertion is what would
// catch a return to the single invocation: it passes an entry-count check and
// fails here.
//
// Vectorness is asserted as drawing operators present and no raster image
// anywhere. Poppler converts text to glyph outlines rather than to `<text>`, so
// the marker words are not in the file at all — a Contains check for one would
// fail on a perfectly good SVG.
func (r *Tests) SvgWritesOneVectorFilePerPage(ctx context.Context) error {
	if r.svgWritesOneVectorFilePerPage != nil {
		return nil
	}
	q := r.query.Select("svgWritesOneVectorFilePerPage")

	return q.Execute(ctx)
}

// TextOnImageOnlyPdfReturnsNothing asserts the boundary with the tesseract
// module: a PDF carrying an image and no text layer extracts to nothing, and
// does not fail.
//
// This is the whole reason both modules exist. From poppler's point of view a
// page with no text is not an error — there is nothing wrong with the document
// and nothing wrong with the extraction — so the empty result is the only signal
// a caller gets that this document needs rasterizing and handing to OCR. A
// module that failed here instead would make the two paths impossible to choose
// between programmatically.
func (r *Tests) TextOnImageOnlyPdfReturnsNothing(ctx context.Context) error {
	if r.textOnImageOnlyPdfReturnsNothing != nil {
		return nil
	}
	q := r.query.Select("textOnImageOnlyPdfReturnsNothing")

	return q.Execute(ctx)
}

// TextReproducesTextLayerExactly asserts Text returns the document's text
// layer byte for byte, in page order, with a form feed between pages.
//
// The comparison is against the whole string rather than a per-page Contains
// sweep on purpose. Extraction has no tolerance to spend: the text is already in
// the file, and anything this module does to it — a lost page break, a stray
// leading newline, pages in the wrong order — is a defect and not a recognition
// error. A fixture whose content streams are readable is what makes an exact
// expectation writable at all.
func (r *Tests) TextReproducesTextLayerExactly(ctx context.Context) error {
	if r.textReproducesTextLayerExactly != nil {
		return nil
	}
	q := r.query.Select("textReproducesTextLayerExactly")

	return q.Execute(ctx)
}

// TsvRowsCarryPageNumbersAndWordGeometry asserts Tsv reports one row per layout
// element, each naming the page it came from and the box it occupies.
//
// The page number is the half that makes the format worth having next to Bbox: a
// `-bbox` page element carries a size and no number, so a report of a multi-page
// document is traceable back to its pages only positionally, while every TSV row
// names its page outright. This asserts the numbers run 1..12 in order on the page
// rows, and that each page's word rows carry that page's marker word — so a row
// attributed to the wrong page fails here.
//
// The geometry is the other half, and is checked against the fixture's own
// content stream rather than asserted non-empty: a word row's `left` is the text
// origin for the first word of a line, its `top` is the baseline measured down
// from the top of the page less the font's ascender, and its `height` is the
// ascender-to-descender span — 22.2 points at 24pt Helvetica, the same for a
// one-glyph word as for a seven-glyph one.
func (r *Tests) TsvRowsCarryPageNumbersAndWordGeometry(ctx context.Context) error {
	if r.tsvRowsCarryPageNumbersAndWordGeometry != nil {
		return nil
	}
	q := r.query.Select("tsvRowsCarryPageNumbersAndWordGeometry")

	return q.Execute(ctx)
}

// TxtMatchesText asserts the file Txt returns carries exactly the bytes Text
// returns, so choosing between them is a plumbing decision and nothing more.
//
// The file is round-tripped through the module's own workdir rather than read
// straight off the handle: the point of Txt is that the bytes reach a filesystem
// intact, and File.Contents would confirm the engine's copy while saying nothing
// about the export a real consumer performs.
func (r *Tests) TxtMatchesText(ctx context.Context) error {
	if r.txtMatchesText != nil {
		return nil
	}
	q := r.query.Select("txtMatchesText")

	return q.Execute(ctx)
}

// UntrustedIndexIsRejectedWithoutApkKey asserts a repository whose index is
// signed by a key the image does not trust is refused rather than installed
// from, so WithApkKey is doing verification and not decoration. It is also what
// says `--allow-untrusted` is genuinely not on offer: a module that quietly
// installed from an unverifiable index would make the air-gapped path the least
// trustworthy one.
//
// The failing half is the suite's proof that nothing falls back to the CDN
// either. The two installs differ only in the key, so if a rejected index sent
// apk to dl-cdn.alpinelinux.org for the same packages the build would succeed
// and this test would fail.
//
// Asserting on apk's own wording (it says `UNTRUSTED signature`) is not
// available: an exec failure crosses the module boundary as its exit status,
// with the output left in the logs.
func (r *Tests) UntrustedIndexIsRejectedWithoutApkKey(ctx context.Context) error {
	if r.untrustedIndexIsRejectedWithoutApkKey != nil {
		return nil
	}
	q := r.query.Select("untrustedIndexIsRejectedWithoutApkKey")

	return q.Execute(ctx)
}

// VectorFormatsIgnoreRasterOnlySettings asserts a conversion configured for the
// raster outputs still converts when it is asked for a vector one.
//
// Forwarding those flags is not a no-op, which is what makes this worth an
// assertion of its own: pdftocairo rejects both of the ones it recognises —
// `-mono may only be used with the -png, -jpeg, or -tiff output options` — and
// exits 99 having written nothing, and `-hide-annotations` is not a pdftocairo
// option at all. So the natural shape of "render this document as PNG for OCR
// and as SVG for the web view" would fail on its second half unless the module
// drops what it cannot honour.
//
// WithDpi is the one setting that does reach pdftocairo, and it is set here too
// so this is not accidentally asserting that no flags are passed at all.
func (r *Tests) VectorFormatsIgnoreRasterOnlySettings(ctx context.Context) error {
	if r.vectorFormatsIgnoreRasterOnlySettings != nil {
		return nil
	}
	q := r.query.Select("vectorFormatsIgnoreRasterOnlySettings")

	return q.Execute(ctx)
}

// VersionReportsPopplerRelease asserts Version reports the poppler release the
// pinned Alpine tag ships, as a bare version number.
//
// poppler's tools print their banner on stderr and still exit 0, so a module
// reading stdout would return the empty string here for every image it ever
// built. The assertion is on the shape and the major release rather than the
// exact patch: Alpine may rebuild poppler-utils within the v3.24 branch, and a
// test that pins the patch level would fail on a change this module has no
// opinion about.
func (r *Tests) VersionReportsPopplerRelease(ctx context.Context) error {
	if r.versionReportsPopplerRelease != nil {
		return nil
	}
	q := r.query.Select("versionReportsPopplerRelease")

	return q.Execute(ctx)
}

// WithFontsPutsFaceWhereFontconfigFindsIt asserts a supplied face is one
// fontconfig reports, which is the only thing that matters: poppler asks
// fontconfig for a substitute and draws nothing at all when the answer is
// nothing.
//
// DejaVu is the face because Alpine packages it separately from the family this
// module installs, so the negative control is real — the plain image genuinely
// cannot see it, and the assertion is not passing on something the base image
// already had.
func (r *Tests) WithFontsPutsFaceWhereFontconfigFindsIt(ctx context.Context) error {
	if r.withFontsPutsFaceWhereFontconfigFindsIt != nil {
		return nil
	}
	q := r.query.Select("withFontsPutsFaceWhereFontconfigFindsIt")

	return q.Execute(ctx)
}

// WithoutAnnotationsRemovesTheAnnotationLayer asserts the annotation layer is
// drawn by default and gone when asked for.
//
// annotated.pdf's page draws nothing but black text, so every chromatic pixel in
// a render of it is the annotation's appearance stream and nothing else. Without
// that separation the assertion could not tell an annotation that was not drawn
// from one that was drawn somewhere else on the page.
func (r *Tests) WithoutAnnotationsRemovesTheAnnotationLayer(ctx context.Context) error {
	if r.withoutAnnotationsRemovesTheAnnotationLayer != nil {
		return nil
	}
	q := r.query.Select("withoutAnnotationsRemovesTheAnnotationLayer")

	return q.Execute(ctx)
}
