// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/tesseract/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Tesseract) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Registry       string
		AlpineTag      string
		Languages      []string
		OmpThreadLimit int
		Tessdata       *dagger.Directory
	}
	concrete.Registry = r.Registry
	concrete.AlpineTag = r.AlpineTag
	concrete.Languages = r.Languages
	concrete.OmpThreadLimit = r.OmpThreadLimit
	concrete.Tessdata = r.Tessdata
	return json.Marshal(&concrete)
}

func (r *Tesseract) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Registry       string
		AlpineTag      string
		Languages      []string
		OmpThreadLimit int
		Tessdata       *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Registry = concrete.Registry
	r.AlpineTag = concrete.AlpineTag
	r.Languages = concrete.Languages
	r.OmpThreadLimit = concrete.OmpThreadLimit
	r.Tessdata = concrete.Tessdata
	return nil
}

func (r Batch) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Tesseract *Tesseract
		Source    *dagger.Directory
		Glob      string
		Options   options
	}
	concrete.Tesseract = r.Tesseract
	concrete.Source = r.Source
	concrete.Glob = r.Glob
	concrete.Options = r.Options
	return json.Marshal(&concrete)
}

func (r *Batch) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Tesseract *Tesseract
		Source    *dagger.Directory
		Glob      string
		Options   options
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Tesseract = concrete.Tesseract
	r.Source = concrete.Source
	r.Glob = concrete.Glob
	r.Options = concrete.Options
	return nil
}

func (r Ci) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Batch            *Batch
		Formats          []Format
		MinConfidence    int
		HasMinConfidence bool
	}
	concrete.Batch = r.Batch
	concrete.Formats = r.Formats
	concrete.MinConfidence = r.MinConfidence
	concrete.HasMinConfidence = r.HasMinConfidence
	return json.Marshal(&concrete)
}

func (r *Ci) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Batch            *Batch
		Formats          []Format
		MinConfidence    int
		HasMinConfidence bool
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Batch = concrete.Batch
	r.Formats = concrete.Formats
	r.MinConfidence = concrete.MinConfidence
	r.HasMinConfidence = concrete.HasMinConfidence
	return nil
}

func (r Document) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Tesseract *Tesseract
		Source    *dagger.File
		Pages     *dagger.Directory
		PdfDpi    int
		Options   options
	}
	concrete.Tesseract = r.Tesseract
	concrete.Source = r.Source
	concrete.Pages = r.Pages
	concrete.PdfDpi = r.PdfDpi
	concrete.Options = r.Options
	return json.Marshal(&concrete)
}

func (r *Document) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Tesseract *Tesseract
		Source    *dagger.File
		Pages     *dagger.Directory
		PdfDpi    int
		Options   options
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Tesseract = concrete.Tesseract
	r.Source = concrete.Source
	r.Pages = concrete.Pages
	r.PdfDpi = concrete.PdfDpi
	r.Options = concrete.Options
	return nil
}

func (r Training) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Tesseract  *Tesseract
		Source     *dagger.Directory
		BaseModel  string
		Iterations int
	}
	concrete.Tesseract = r.Tesseract
	concrete.Source = r.Source
	concrete.BaseModel = r.BaseModel
	concrete.Iterations = r.Iterations
	return json.Marshal(&concrete)
}

func (r *Training) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Tesseract  *Tesseract
		Source     *dagger.Directory
		BaseModel  string
		Iterations int
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Tesseract = concrete.Tesseract
	r.Source = concrete.Source
	r.BaseModel = concrete.BaseModel
	r.Iterations = concrete.Iterations
	return nil
}

func (r Format) IsEnum() {}

func (r Format) Name() string {
	switch r {
	case FormatAlto:
		return "Alto"
	case FormatHocr:
		return "Hocr"
	case FormatPage:
		return "Page"
	case FormatPdf:
		return "Pdf"
	case FormatTsv:
		return "Tsv"
	case FormatTxt:
		return "Txt"
	}
	return ""
}

func (r Format) Value() string {
	return string(r)
}

func (r Format) MarshalJSON() ([]byte, error) {
	if r == "" {
		return []byte("\"\""), nil
	}
	name := r.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", r)
	}
	return json.Marshal(name)
}

func (r *Format) UnmarshalJSON(bs []byte) error {
	var s string
	err := json.Unmarshal(bs, &s)
	if err != nil {
		return err
	}
	switch s {
	case "":
		*r = ""
	case "Alto":
		*r = FormatAlto
	case "Hocr":
		*r = FormatHocr
	case "Page":
		*r = FormatPage
	case "Pdf":
		*r = FormatPdf
	case "Tsv":
		*r = FormatTsv
	case "Txt":
		*r = FormatTxt
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

func (r EngineMode) IsEnum() {}

func (r EngineMode) Name() string {
	switch r {
	case EngineModeDefault:
		return "Default"
	case EngineModeLegacy:
		return "Legacy"
	case EngineModeLegacyLstm:
		return "LegacyLstm"
	case EngineModeLstm:
		return "Lstm"
	}
	return ""
}

func (r EngineMode) Value() string {
	return string(r)
}

func (r EngineMode) MarshalJSON() ([]byte, error) {
	if r == "" {
		return []byte("\"\""), nil
	}
	name := r.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", r)
	}
	return json.Marshal(name)
}

func (r *EngineMode) UnmarshalJSON(bs []byte) error {
	var s string
	err := json.Unmarshal(bs, &s)
	if err != nil {
		return err
	}
	switch s {
	case "":
		*r = ""
	case "Default":
		*r = EngineModeDefault
	case "Legacy":
		*r = EngineModeLegacy
	case "LegacyLstm":
		*r = EngineModeLegacyLstm
	case "Lstm":
		*r = EngineModeLstm
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

func (r PageSegMode) IsEnum() {}

func (r PageSegMode) Name() string {
	switch r {
	case PageSegModeAuto:
		return "Auto"
	case PageSegModeAutoOsd:
		return "AutoOsd"
	case PageSegModeCircleWord:
		return "CircleWord"
	case PageSegModeOsdOnly:
		return "OsdOnly"
	case PageSegModeRawLine:
		return "RawLine"
	case PageSegModeSingleBlock:
		return "SingleBlock"
	case PageSegModeSingleBlockVertText:
		return "SingleBlockVertText"
	case PageSegModeSingleChar:
		return "SingleChar"
	case PageSegModeSingleColumn:
		return "SingleColumn"
	case PageSegModeSingleLine:
		return "SingleLine"
	case PageSegModeSingleWord:
		return "SingleWord"
	case PageSegModeSparseText:
		return "SparseText"
	case PageSegModeSparseTextOsd:
		return "SparseTextOsd"
	}
	return ""
}

func (r PageSegMode) Value() string {
	return string(r)
}

func (r PageSegMode) MarshalJSON() ([]byte, error) {
	if r == "" {
		return []byte("\"\""), nil
	}
	name := r.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", r)
	}
	return json.Marshal(name)
}

func (r *PageSegMode) UnmarshalJSON(bs []byte) error {
	var s string
	err := json.Unmarshal(bs, &s)
	if err != nil {
		return err
	}
	switch s {
	case "":
		*r = ""
	case "Auto":
		*r = PageSegModeAuto
	case "AutoOsd":
		*r = PageSegModeAutoOsd
	case "CircleWord":
		*r = PageSegModeCircleWord
	case "OsdOnly":
		*r = PageSegModeOsdOnly
	case "RawLine":
		*r = PageSegModeRawLine
	case "SingleBlock":
		*r = PageSegModeSingleBlock
	case "SingleBlockVertText":
		*r = PageSegModeSingleBlockVertText
	case "SingleChar":
		*r = PageSegModeSingleChar
	case "SingleColumn":
		*r = PageSegModeSingleColumn
	case "SingleLine":
		*r = PageSegModeSingleLine
	case "SingleWord":
		*r = PageSegModeSingleWord
	case "SparseText":
		*r = PageSegModeSparseText
	case "SparseTextOsd":
		*r = PageSegModeSparseTextOsd
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Batch":
		switch fnName {
		case "Export":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var formats []Format
			if inputArgs["formats"] != nil {
				err = json.Unmarshal([]byte(inputArgs["formats"]), &formats)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg formats", err))
				}
			}
			return (*Batch).Export(&parent, ctx, formats)
		case "Files":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Batch).Files(&parent, ctx)
		case "WithDpi":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dpi int
			if inputArgs["dpi"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dpi"]), &dpi)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dpi", err))
				}
			}
			return (*Batch).WithDpi(&parent, dpi), nil
		case "WithEngine":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var mode EngineMode
			if inputArgs["mode"] != nil {
				err = json.Unmarshal([]byte(inputArgs["mode"]), &mode)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg mode", err))
				}
			}
			return (*Batch).WithEngine(&parent, mode), nil
		case "WithGlob":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pattern string
			if inputArgs["pattern"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pattern"]), &pattern)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pattern", err))
				}
			}
			return (*Batch).WithGlob(&parent, pattern), nil
		case "WithLanguage":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var lang string
			if inputArgs["lang"] != nil {
				err = json.Unmarshal([]byte(inputArgs["lang"]), &lang)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg lang", err))
				}
			}
			return (*Batch).WithLanguage(&parent, lang), nil
		case "WithPageSegmentation":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var mode PageSegMode
			if inputArgs["mode"] != nil {
				err = json.Unmarshal([]byte(inputArgs["mode"]), &mode)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg mode", err))
				}
			}
			return (*Batch).WithPageSegmentation(&parent, mode), nil
		case "WithParameter":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*Batch).WithParameter(&parent, name, value), nil
		case "WithUserPatterns":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var patterns *dagger.File
			if inputArgs["patterns"] != nil {
				err = json.Unmarshal([]byte(inputArgs["patterns"]), &patterns)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg patterns", err))
				}
			}
			return (*Batch).WithUserPatterns(&parent, patterns), nil
		case "WithUserWords":
			var parent Batch
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var words *dagger.File
			if inputArgs["words"] != nil {
				err = json.Unmarshal([]byte(inputArgs["words"]), &words)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg words", err))
				}
			}
			return (*Batch).WithUserWords(&parent, words), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Ci":
		switch fnName {
		case "Check":
			var parent Ci
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Ci).Check(&parent, ctx)
		case "Run":
			var parent Ci
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Ci).Run(&parent, ctx)
		case "WithFormats":
			var parent Ci
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var formats []Format
			if inputArgs["formats"] != nil {
				err = json.Unmarshal([]byte(inputArgs["formats"]), &formats)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg formats", err))
				}
			}
			return (*Ci).WithFormats(&parent, formats), nil
		case "WithLanguage":
			var parent Ci
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var lang string
			if inputArgs["lang"] != nil {
				err = json.Unmarshal([]byte(inputArgs["lang"]), &lang)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg lang", err))
				}
			}
			return (*Ci).WithLanguage(&parent, lang), nil
		case "WithMinConfidence":
			var parent Ci
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var percent int
			if inputArgs["percent"] != nil {
				err = json.Unmarshal([]byte(inputArgs["percent"]), &percent)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg percent", err))
				}
			}
			return (*Ci).WithMinConfidence(&parent, percent), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Document":
		switch fnName {
		case "Alto":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Alto(&parent, ctx)
		case "Box":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Box(&parent, ctx)
		case "Export":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var formats []Format
			if inputArgs["formats"] != nil {
				err = json.Unmarshal([]byte(inputArgs["formats"]), &formats)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg formats", err))
				}
			}
			return (*Document).Export(&parent, ctx, formats)
		case "Hocr":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Hocr(&parent, ctx)
		case "LstmTrain":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var groundTruth string
			if inputArgs["groundTruth"] != nil {
				err = json.Unmarshal([]byte(inputArgs["groundTruth"]), &groundTruth)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg groundTruth", err))
				}
			}
			return (*Document).LstmTrain(&parent, ctx, groundTruth)
		case "Osd":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Osd(&parent, ctx)
		case "Page":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Page(&parent, ctx)
		case "Pdf":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Pdf(&parent, ctx)
		case "ProcessedImages":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).ProcessedImages(&parent, ctx)
		case "Text":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Text(&parent, ctx)
		case "Tsv":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Tsv(&parent, ctx)
		case "Txt":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Document).Txt(&parent, ctx)
		case "WithDpi":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dpi int
			if inputArgs["dpi"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dpi"]), &dpi)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dpi", err))
				}
			}
			return (*Document).WithDpi(&parent, dpi), nil
		case "WithEngine":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var mode EngineMode
			if inputArgs["mode"] != nil {
				err = json.Unmarshal([]byte(inputArgs["mode"]), &mode)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg mode", err))
				}
			}
			return (*Document).WithEngine(&parent, mode), nil
		case "WithLanguage":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var lang string
			if inputArgs["lang"] != nil {
				err = json.Unmarshal([]byte(inputArgs["lang"]), &lang)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg lang", err))
				}
			}
			return (*Document).WithLanguage(&parent, lang), nil
		case "WithPageSegmentation":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var mode PageSegMode
			if inputArgs["mode"] != nil {
				err = json.Unmarshal([]byte(inputArgs["mode"]), &mode)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg mode", err))
				}
			}
			return (*Document).WithPageSegmentation(&parent, mode), nil
		case "WithParameter":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var value string
			if inputArgs["value"] != nil {
				err = json.Unmarshal([]byte(inputArgs["value"]), &value)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg value", err))
				}
			}
			return (*Document).WithParameter(&parent, name, value), nil
		case "WithUserPatterns":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var patterns *dagger.File
			if inputArgs["patterns"] != nil {
				err = json.Unmarshal([]byte(inputArgs["patterns"]), &patterns)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg patterns", err))
				}
			}
			return (*Document).WithUserPatterns(&parent, patterns), nil
		case "WithUserWords":
			var parent Document
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var words *dagger.File
			if inputArgs["words"] != nil {
				err = json.Unmarshal([]byte(inputArgs["words"]), &words)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg words", err))
				}
			}
			return (*Document).WithUserWords(&parent, words), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Tesseract":
		switch fnName {
		case "Batch":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Tesseract).Batch(&parent, source), nil
		case "Ci":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Tesseract).Ci(&parent, source), nil
		case "Container":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Tesseract).Container(&parent), nil
		case "Document":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.File
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Tesseract).Document(&parent, source), nil
		case "FromPdf":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.File
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var dpi int
			if inputArgs["dpi"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dpi"]), &dpi)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dpi", err))
				}
			}
			return (*Tesseract).FromPdf(&parent, source, dpi), nil
		case "Langs":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Tesseract).Langs(&parent, ctx)
		case "Parameters":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Tesseract).Parameters(&parent, ctx)
		case "Training":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Tesseract).Training(&parent, source), nil
		case "Version":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Tesseract).Version(&parent, ctx)
		case "WithTessdata":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var dir *dagger.Directory
			if inputArgs["dir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dir"]), &dir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dir", err))
				}
			}
			return (*Tesseract).WithTessdata(&parent, dir), nil
		case "":
			var parent Tesseract
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var alpineTag string
			if inputArgs["alpineTag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["alpineTag"]), &alpineTag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg alpineTag", err))
				}
			}
			var languages []string
			if inputArgs["languages"] != nil {
				err = json.Unmarshal([]byte(inputArgs["languages"]), &languages)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg languages", err))
				}
			}
			var ompThreadLimit int
			if inputArgs["ompThreadLimit"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ompThreadLimit"]), &ompThreadLimit)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ompThreadLimit", err))
				}
			}
			return New(registry, alpineTag, languages, ompThreadLimit)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Training":
		switch fnName {
		case "Evaluate":
			var parent Training
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Training).Evaluate(&parent, ctx)
		case "Files":
			var parent Training
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Training).Files(&parent, ctx)
		case "Traineddata":
			var parent Training
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Training).Traineddata(&parent, ctx)
		case "WithBaseModel":
			var parent Training
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var lang string
			if inputArgs["lang"] != nil {
				err = json.Unmarshal([]byte(inputArgs["lang"]), &lang)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg lang", err))
				}
			}
			return (*Training).WithBaseModel(&parent, lang), nil
		case "WithIterations":
			var parent Training
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var n int
			if inputArgs["n"] != nil {
				err = json.Unmarshal([]byte(inputArgs["n"]), &n)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg n", err))
				}
			}
			return (*Training).WithIterations(&parent, n), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
