// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Bruno
func (r *Binding) AsBruno() *Bruno { // bruno (../../../../../daggerverse/bruno/main.go:47:6)
	q := r.query.Select("asBruno")

	return &Bruno{
		query: q,
	}
}

// Retrieve the binding value, as type BrunoCi
func (r *Binding) AsBrunoCi() *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:37:6)
	q := r.query.Select("asBrunoCi")

	return &BrunoCi{
		query: q,
	}
}

// Retrieve the binding value, as type BrunoCollection
func (r *Binding) AsBrunoCollection() *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:86:6)
	q := r.query.Select("asBrunoCollection")

	return &BrunoCollection{
		query: q,
	}
}

// Bruno wraps the Bruno CLI as Dagger functions. Construct via New(); call
// Container() for the raw image, or Collection(source) to bind a collection
// and reach Run/Report.
type Bruno struct { // bruno (../../../../../daggerverse/bruno/main.go:47:6)
	query *querybuilder.Selection

	id      *ID
	version *string
}

func (r *Bruno) WithGraphQLQuery(q *querybuilder.Selection) *Bruno {
	return &Bruno{
		query: q,
	}
}

// Ci returns a new pipeline builder bound to the supplied collection source.
// The input is the collection root, exactly as a bare Collection(source) call
// would take it.
func (r *Bruno) Ci(source *Directory) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:51:1)
	assertNotNil("source", source)
	q := r.query.Select("ci")
	q = q.Arg("source", source)

	return &BrunoCi{
		query: q,
	}
}

// Collection binds a Bruno collection directory to the toolchain.
func (r *Bruno) Collection(source *Directory) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:136:1)
	assertNotNil("source", source)
	q := r.query.Select("collection")
	q = q.Arg("source", source)

	return &BrunoCollection{
		query: q,
	}
}

// Container returns the bare Bruno CLI image. This is the escape hatch for
// every flag this module does not wrap — `bru`'s long tail of proxy, cookie
// and reporter-redaction options stays reachable via `container with-exec`.
func (r *Bruno) Container() *Container { // bruno (../../../../../daggerverse/bruno/main.go:86:1)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// BrunoGenerateOpts contains options for Bruno.Generate
type BrunoGenerateOpts struct {
	//
	// Name stamped into the generated collection's bruno.json.
	//
	//
	// Default: "api"
	Name string // bruno (../../../../../daggerverse/bruno/generate.go:64:2)
	//
	// Output shape: "bru", the tree this module can run, or "opencollection".
	//
	//
	// Default: "bru"
	Format string // bruno (../../../../../daggerverse/bruno/generate.go:67:2)
}

// Generate converts an OpenAPI document into a Bruno collection directory
// (`bru import openapi`), so a collection can be produced in CI rather than
// hand-maintained beside the spec it drifts from.
//
// The spec is a *dagger.File rather than a URL string, so a local document and
// a remote one are the same call: dag.HTTP(url) covers the URL case without a
// second parameter — and without needing bru's `--insecure`, since the fetch
// never happens inside the container.
//
// format defaults to "bru" where upstream defaults to "opencollection". Only
// the bru shape carries the bruno.json and .bru requests that Collection, Run
// and Report read, so the default is the one whose output feeds straight back
// into this module. "opencollection" writes an opencollection.yml instead and
// is not runnable here.
//
// Requests are grouped by OpenAPI tag, which is bru's own default, so they
// land one folder deep and need Run's recursive default to be reached.
//
// It isthe document and touches no live service.
func (r *Bruno) Generate(spec *File, opts ...BrunoGenerateOpts) *Directory { // bruno (../../../../../daggerverse/bruno/generate.go:57:1)
	assertNotNil("spec", spec)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `name` optional argument
		if !querybuilder.IsZeroValue(opts[i].Name) {
			q = q.Arg("name", opts[i].Name)
		}
		// `format` optional argument
		if !querybuilder.IsZeroValue(opts[i].Format) {
			q = q.Arg("format", opts[i].Format)
		}
	}
	q = q.Arg("spec", spec)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Bruno.
func (r *Bruno) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Bruno) XXX_GraphQLType() string {
	return "Bruno"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Bruno) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Bruno) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Bruno) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Bruno) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Bruno{query: selectNode(dag.query, id, "Bruno")}
	return nil
}

// Version returns the Bruno CLI release the pinned image ships, as reported
// by `bru --version`.
func (r *Bruno) Version(ctx context.Context) (string, error) { // bruno (../../../../../daggerverse/bruno/main.go:94:1)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Bruno as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Bruno) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Ci is a chained builder for a standardized Bruno CI pipeline: a collection
// in, a gate and the reports out.
//
// Lint, run and report are three calls plus the glue that decides what fails
// the build, which is the shape every API repo ends up hand-rolling. This
// bundles them so that CI is one declarative `dagger call`.
//
// It composes Collection without adding capability of its own — every stage is
// a call the caller could make by hand. What it adds is the ordering: lint runs
// before the collection, so a {{baseUrl}} that resolves nowhere or a
// credential committed in plaintext is reported without spending a request on
// discovering it, and a collection that could never have passed does not start
// a container's worth of work to say so.
//
// The two terminals split the way Collection's own Run and Report do, and for
// the same reason. Check is the gate: it fails on a lint error, on a failing
// request, test or assertion, and on any of bru's usage errors. Run is the
// artifact: it returns the reports directory, and does not fail a run whose
// requests failed — Dagger drops a function's value when it also returns an
// error, so a gating Run could never hand back the report describing the
// failure, which is exactly when the report matters. CI pairs them.
type BrunoCi struct { // bruno (../../../../../daggerverse/bruno/ci.go:37:6)
	query *querybuilder.Selection

	check *Void
	id    *ID
}
type WithBrunoCiFunc func(r *BrunoCi) *BrunoCi

// With calls the provided function with current BrunoCi.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *BrunoCi) With(f WithBrunoCiFunc) *BrunoCi {
	return f(r)
}

func (r *BrunoCi) WithGraphQLQuery(q *querybuilder.Selection) *BrunoCi {
	return &BrunoCi{
		query: q,
	}
}

// Check runs the pipeline as a gate and produces nothing, for the PR that wants
// to know whether the API is behaving.
//
// The stages are the enabled lint followed by the collection itself. Lint comes
// first so that a structural error costs no request: a collection whose
// variables resolve nowhere fails here rather than against a live service,
// naming the file instead of the response. The collection then fails on bru's
// exit 1 — a failing request, test or assertion — and reports every other
// non-zero exit as the usage error it is.
//
// No report is produced, because a gate that returns nothing can gate: see Run
// for why the terminal that hands back artifacts cannot also be the one that
// fails.
func (r *BrunoCi) Check(ctx context.Context) error { // bruno (../../../../../daggerverse/bruno/ci.go:142:1)
	if r.check != nil {
		return nil
	}
	q := r.query.Select("check")

	return q.Execute(ctx)
}

// A unique identifier for this BrunoCi.
func (r *BrunoCi) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *BrunoCi) XXX_GraphQLType() string {
	return "BrunoCi"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *BrunoCi) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *BrunoCi) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *BrunoCi) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *BrunoCi) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = BrunoCi{query: selectNode(dag.query, id, "BrunoCi")}
	return nil
}

// Run executes the pipeline and returns the requested reports as a directory,
// one file per format: report.json, report.xml for junit, report.html.
//
// It does not fail on a failing request, test or assertion. That is deliberate
// and it is the same reasoning as Collection.Report: a Dagger function that
// returns an error forfeits its value, so a Run that gated would hand back
// nothing on exactly the runs whose reports a pipeline needs — the JUnit file a
// CI system turns into a test report, the HTML page somebody opens to see which
// assertion failed. Pair the two: Run for the artifacts, Check for the gate.
//
// A lint error is still an error here, because then the collection never ran
// and there is no report to return. So is a usage error, for the same reason.
func (r *BrunoCi) Run() *Directory { // bruno (../../../../../daggerverse/bruno/ci.go:167:1)
	q := r.query.Select("run")

	return &Directory{
		query: q,
	}
}

// WithEnvironment selects the environment the pipeline resolves variables from,
// by the name of the file under environments/ without its extension. See
// Collection.WithEnvironment.
//
// It is also what the lint stage checks references against, so the environment
// a pipeline runs under is the one its variables are required to resolve in.
func (r *BrunoCi) WithEnvironment(name string) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:61:1)
	q := r.query.Select("withEnvironment")
	q = q.Arg("name", name)

	return &BrunoCi{
		query: q,
	}
}

// BrunoCiWithLintOpts contains options for BrunoCi.WithLint
type BrunoCiWithLintOpts struct {
	//
	// Treat lint warnings as failures.
	//
	FailOnWarnings bool // bruno (../../../../../daggerverse/bruno/ci.go:100:2)
}

// WithLint adds the lint stage, which runs before the collection and fails the
// pipeline on a structural error without issuing a request. See
// Collection.Lint for the rules.
//
// It is opt-in rather than always-on because linting is an opinion about how a
// collection is written, and a pipeline should not start failing on one the day
// it adopts the builder.
func (r *BrunoCi) WithLint(opts ...BrunoCiWithLintOpts) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:97:1)
	q := r.query.Select("withLint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `failOnWarnings` optional argument
		if !querybuilder.IsZeroValue(opts[i].FailOnWarnings) {
			q = q.Arg("failOnWarnings", opts[i].FailOnWarnings)
		}
	}

	return &BrunoCi{
		query: q,
	}
}

// WithReport adds a reporter format — json, junit or html — to the set Run
// returns. Call it more than once for more than one format.
//
// Every requested format comes out of a single collection pass: bru accepts all
// of its `--reporter-*` flags at once, so asking for both JUnit and HTML costs
// one run and the two artifacts describe the same set of responses rather than
// two different ones.
//
// Like the rest of the builder it has no error return, so an unknown format is
// reported by the terminal that would have written it.
func (r *BrunoCi) WithReport(format string) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:118:1)
	q := r.query.Select("withReport")
	q = q.Arg("format", format)

	return &BrunoCi{
		query: q,
	}
}

// WithSecretVar makes a secret readable from the collection as
// {{process.env.NAME}}, without it ever reaching argv. See
// Collection.WithSecretVar.
//
// A pipeline takes secrets and not plain overrides on purpose: a value worth
// passing into CI by hand is usually a credential, and WithVar would put it on
// the command line. A collection that needs a non-secret override can still be
// assembled through Collection.
func (r *BrunoCi) WithSecretVar(name string, value *Secret) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:84:1)
	assertNotNil("value", value)
	q := r.query.Select("withSecretVar")
	q = q.Arg("name", name)
	q = q.Arg("value", value)

	return &BrunoCi{
		query: q,
	}
}

// WithService binds a service into the pipeline's network under alias, so the
// collection can reach it by that hostname. A collection is inert without a
// target. See Collection.WithService.
func (r *BrunoCi) WithService(alias string, service *Service) *BrunoCi { // bruno (../../../../../daggerverse/bruno/ci.go:70:1)
	assertNotNil("service", service)
	q := r.query.Select("withService")
	q = q.Arg("alias", alias)
	q = q.Arg("service", service)

	return &BrunoCi{
		query: q,
	}
}

// AsNode returns this BrunoCi as a Node.
// This is a local type conversion — no GraphQL call.
func (r *BrunoCi) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Collection is a Bruno collection tree plus the options that apply across
// bru's subcommands. It is immutable: every With* returns a copy.
//
// The input is a directory, not a lone request file: bru exits 4 when invoked
// outside a collection root, and resolves environments/ and .env relative to
// it.
type BrunoCollection struct { // bruno (../../../../../daggerverse/bruno/collection.go:86:6)
	query *querybuilder.Selection

	id   *ID
	lint *Void
	run  *string
}
type WithBrunoCollectionFunc func(r *BrunoCollection) *BrunoCollection

// With calls the provided function with current BrunoCollection.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *BrunoCollection) With(f WithBrunoCollectionFunc) *BrunoCollection {
	return f(r)
}

func (r *BrunoCollection) WithGraphQLQuery(q *querybuilder.Selection) *BrunoCollection {
	return &BrunoCollection{
		query: q,
	}
}

// A unique identifier for this BrunoCollection.
func (r *BrunoCollection) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *BrunoCollection) XXX_GraphQLType() string {
	return "BrunoCollection"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *BrunoCollection) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *BrunoCollection) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *BrunoCollection) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *BrunoCollection) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = BrunoCollection{query: selectNode(dag.query, id, "BrunoCollection")}
	return nil
}

// BrunoCollectionLintOpts contains options for BrunoCollection.Lint
type BrunoCollectionLintOpts struct {
	//
	// Treat warnings as failures.
	//
	FailOnWarnings bool // bruno (../../../../../daggerverse/bruno/lint.go:103:2)
}

// Lint checks a collection's structure without issuing a single request.
//
// Bruno ships no linter, and the failure modes it leaves open are the
// expensive kind: a {{baseUrl}} that resolves nowhere fails at request time in
// CI rather than at review time, and an API key committed as a plaintext value
// under environments/ is a leak nobody notices.
//
// Findings are folded into the returned error rather than returned as a value,
// following kicad's Drc and Erc: Dagger drops a function's value when it also
// returns a non-nil error, so a (findings, error) signature would hide the
// findings on exactly the path that needs them. Warnings that do not fail the
// call are written to stderr instead, so they are still visible in the run's
// logs.
//
// Everything is evaluated in pure Go over the source tree — no container, per
// the module's runtime-I/O convention — which is also why it is
// directory's contents and nothing else.
//
// Scope limit: this reads the collection's block and reference structure, not
// a full .bru parse. Blocks are recognised by their opener at column 0, which
// is where Bruno's own writer puts them.
func (r *BrunoCollection) Lint(ctx context.Context, opts ...BrunoCollectionLintOpts) error { // bruno (../../../../../daggerverse/bruno/lint.go:99:1)
	if r.lint != nil {
		return nil
	}
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `failOnWarnings` optional argument
		if !querybuilder.IsZeroValue(opts[i].FailOnWarnings) {
			q = q.Arg("failOnWarnings", opts[i].FailOnWarnings)
		}
	}

	return q.Execute(ctx)
}

// Report executes the collection and returns the reporter's artifact.
//
// Unlike Run it does not fail on exit 1: a Dagger function that returns an
// error forfeits its value, so a Report that gated would never hand back the
// file describing the failure — which is exactly when the file matters. CI
// pairs the two, taking the artifact from Report and the gate from Run. A
// usage error is still an error, because then there is no report to return.
//
// The run is recursive, matching Run's default, so the artifact describes the
// whole collection.
func (r *BrunoCollection) Report(format string) *File { // bruno (../../../../../daggerverse/bruno/collection.go:322:1)
	q := r.query.Select("report")
	q = q.Arg("format", format)

	return &File{
		query: q,
	}
}

// BrunoCollectionRunOpts contains options for BrunoCollection.Run
type BrunoCollectionRunOpts struct {
	//
	// Descend into the collection's folders. Off, only the requests at the
	// collection root run. Note that a defaulted-true bool cannot be set
	// false from the Go SDK — the zero value is dropped and the default
	// applies — so a non-recursive run is `--recursive=false` from the CLI.
	//
	//
	// Default: true
	Recursive bool // bruno (../../../../../daggerverse/bruno/collection.go:289:2)
}

// Run executes the collection and returns bru's output.
//
// It fails on exit 1 — a failing request, test or assertion — so a collection
// is a gate a pipeline can hang a check on. Every other non-zero exit is a
// usage error reported as itself, so "the environment name is wrong" never
// reads as "your API is broken". Errors carry combined stdout and stderr,
// because bru splits its diagnostics across both.
//
// A failing Run returns no output alongside its error: a Dagger function that
// returns an error forfeits its value. Pair it with Report when the artifact
// matters.
func (r *BrunoCollection) Run(ctx context.Context, opts ...BrunoCollectionRunOpts) (string, error) { // bruno (../../../../../daggerverse/bruno/collection.go:282:1)
	if r.run != nil {
		return *r.run, nil
	}
	q := r.query.Select("run")
	for i := len(opts) - 1; i >= 0; i-- {
		// `recursive` optional argument
		if !querybuilder.IsZeroValue(opts[i].Recursive) {
			q = q.Arg("recursive", opts[i].Recursive)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// WithBail stops the run at the first failing request, test or assertion
// (`--bail`) instead of working through the rest of the collection.
func (r *BrunoCollection) WithBail() *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:255:1)
	q := r.query.Select("withBail")

	return &BrunoCollection{
		query: q,
	}
}

// WithCaCert verifies peers against a custom CA certificate (`--cacert`), for
// the collection whose target presents a certificate signed by a private CA —
// an internal endpoint, or a service stood up for the length of the pipeline.
//
// bru adds the certificate to the default truststore rather than replacing it,
// so a collection that also reaches a public endpoint keeps working. Use
// WithoutTruststore for the private CA exclusively.
//
// This is the control WithInsecure is not: the run still verifies, it just
// verifies against the CA the caller named.
func (r *BrunoCollection) WithCaCert(cert *File) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/tls.go:90:1)
	assertNotNil("cert", cert)
	q := r.query.Select("withCaCert")
	q = q.Arg("cert", cert)

	return &BrunoCollection{
		query: q,
	}
}

// BrunoCollectionWithClientCertOpts contains options for BrunoCollection.WithClientCert
type BrunoCollectionWithClientCertOpts struct {
	//
	// Passphrase the private key is encrypted with, if it is.
	//
	Passphrase *Secret // bruno (../../../../../daggerverse/bruno/tls.go:132:2)
}

// WithClientCert presents a client certificate to hosts matching host
// (`--client-cert-config`), for the collection that has to authenticate to an
// mTLS endpoint. Call it more than once for more than one host.
//
// The key is a *dagger.Secret and not a *dagger.File: it is key material, and a
// file's contents are content-addressed into the build cache and readable from
// a trace. It is mounted as a secret, outside the collection, and named only
// from the rendered config — so it reaches neither argv nor the collection tree.
//
// bru takes this as a JSON document referring to the certificate and key by
// path. That document is rendered at run time against the paths this module
// mounts them under, because a caller writing it by hand would have to name
// paths inside a container they cannot see.
func (r *BrunoCollection) WithClientCert(host string, cert *File, key *Secret, opts ...BrunoCollectionWithClientCertOpts) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/tls.go:121:1)
	assertNotNil("cert", cert)
	assertNotNil("key", key)
	q := r.query.Select("withClientCert")
	for i := len(opts) - 1; i >= 0; i-- {
		// `passphrase` optional argument
		if !querybuilder.IsZeroValue(opts[i].Passphrase) {
			q = q.Arg("passphrase", opts[i].Passphrase)
		}
	}
	q = q.Arg("host", host)
	q = q.Arg("cert", cert)
	q = q.Arg("key", key)

	return &BrunoCollection{
		query: q,
	}
}

// WithDelay waits the given number of milliseconds between requests
// (`--delay`), for a target that rate-limits.
func (r *BrunoCollection) WithDelay(milliseconds int) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:263:1)
	q := r.query.Select("withDelay")
	q = q.Arg("milliseconds", milliseconds)

	return &BrunoCollection{
		query: q,
	}
}

// WithEnvFile supplies an environment file (`--env-file`), a .bru or .json
// file holding the variables for the run. It is mounted outside the
// collection, so it never shadows a file the collection ships.
func (r *BrunoCollection) WithEnvFile(file *File) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:182:1)
	assertNotNil("file", file)
	q := r.query.Select("withEnvFile")
	q = q.Arg("file", file)

	return &BrunoCollection{
		query: q,
	}
}

// WithEnvironment selects the environment bru resolves variables from
// (`--env`), by the name of the file under environments/ without its
// extension. An unknown name is bru's exit 6, reported as a usage error.
func (r *BrunoCollection) WithEnvironment(name string) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:143:1)
	q := r.query.Select("withEnvironment")
	q = q.Arg("name", name)

	return &BrunoCollection{
		query: q,
	}
}

// WithInsecure accepts TLS certificates the run cannot verify
// (`--insecure`) — a self-signed certificate on a service that only exists
// for the length of the pipeline, typically.
//
// It verifies nothing, which is the wrong tool for a target behind a private
// CA: use WithCaCert for that, and WithClientCert to authenticate with a
// certificate of the run's own. bru drops `--cacert` when `--insecure` is set,
// so combining the two is rejected rather than quietly verifying nothing.
func (r *BrunoCollection) WithInsecure() *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:238:1)
	q := r.query.Select("withInsecure")

	return &BrunoCollection{
		query: q,
	}
}

// WithSandbox selects the JavaScript sandbox scripts and assertions run in
// (`--sandbox`): "safe", the QuickJS sandbox bru 3.0 made the default, or
// "developer", the Node one. A collection whose scripts require() a module or
// touch the filesystem needs "developer" — and fails at runtime, not at parse
// time, without it.
//
// A collection that says nothing runs in "safe", matching both bru's default
// and Collection's. Like WithVar, an unknown mode is reported by the run
// rather than here.
func (r *BrunoCollection) WithSandbox(mode string) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:224:1)
	q := r.query.Select("withSandbox")
	q = q.Arg("mode", mode)

	return &BrunoCollection{
		query: q,
	}
}

// WithSecretVar makes a secret readable from the collection as
// {{process.env.NAME}}.
//
// It is a separate function from WithVar rather than an overload because
// `--env-var` places its value on the process command line. A secret is bound
// with WithSecretVariable instead, so it appears in neither argv nor any
// diagnostic this module echoes back.
func (r *BrunoCollection) WithSecretVar(name string, value *Secret) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:172:1)
	assertNotNil("value", value)
	q := r.query.Select("withSecretVar")
	q = q.Arg("name", name)
	q = q.Arg("value", value)

	return &BrunoCollection{
		query: q,
	}
}

// WithService binds a service into the run's network under alias, so the
// collection can reach it by that hostname. A collection is inert without a
// target, which is why this exists at all.
func (r *BrunoCollection) WithService(alias string, service *Service) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:208:1)
	assertNotNil("service", service)
	q := r.query.Select("withService")
	q = q.Arg("alias", alias)
	q = q.Arg("service", service)

	return &BrunoCollection{
		query: q,
	}
}

// WithTags restricts the run to requests carrying any of these tags
// (`--tags`).
func (r *BrunoCollection) WithTags(tags []string) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:190:1)
	q := r.query.Select("withTags")
	q = q.Arg("tags", tags)

	return &BrunoCollection{
		query: q,
	}
}

// WithTestsOnly runs only the requests that carry a test or an active
// assertion (`--tests-only`), skipping the ones that exist to set up state
// for a human.
func (r *BrunoCollection) WithTestsOnly() *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:247:1)
	q := r.query.Select("withTestsOnly")

	return &BrunoCollection{
		query: q,
	}
}

// WithVar overrides a single environment variable (`--env-var name=value`),
// taking precedence over whatever the selected environment declares.
//
// It takes a name and a value rather than a map because Dagger functions
// cannot accept map parameters. The value lands on bru's command line — use
// WithSecretVar for anything that should not.
//
// Validation is deferred to the run: builder methods have no error return, so
// a bad name surfaces on the Run or Report that would have used it.
func (r *BrunoCollection) WithVar(name string, value string) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:158:1)
	q := r.query.Select("withVar")
	q = q.Arg("name", name)
	q = q.Arg("value", value)

	return &BrunoCollection{
		query: q,
	}
}

// WithoutTags excludes requests carrying any of these tags
// (`--exclude-tags`). It composes with WithTags: a request matching both is
// excluded.
func (r *BrunoCollection) WithoutTags(tags []string) *BrunoCollection { // bruno (../../../../../daggerverse/bruno/collection.go:199:1)
	q := r.query.Select("withoutTags")
	q = q.Arg("tags", tags)

	return &BrunoCollection{
		query: q,
	}
}

// WithoutTruststore verifies peers against the WithCaCert certificate alone
// (`--ignore-truststore`), ignoring the CAs the image ships.
//
// It only means anything alongside WithCaCert — bru evaluates the flag in
// combination with `--cacert` only — so on its own it is rejected by the run
// rather than silently doing nothing.
func (r *BrunoCollection) WithoutTruststore() *BrunoCollection { // bruno (../../../../../daggerverse/bruno/tls.go:102:1)
	q := r.query.Select("withoutTruststore")

	return &BrunoCollection{
		query: q,
	}
}

// AsNode returns this BrunoCollection as a Node.
// This is a local type conversion — no GraphQL call.
func (r *BrunoCollection) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Create or update a binding of type BrunoCi in the environment
func (r *Env) WithBrunoCiInput(name string, value *BrunoCi, description string) *Env { // bruno (../../../../../daggerverse/bruno/ci.go:37:6)
	assertNotNil("value", value)
	q := r.query.Select("withBrunoCiInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired BrunoCi output to be assigned in the environment
func (r *Env) WithBrunoCiOutput(name string, description string) *Env { // bruno (../../../../../daggerverse/bruno/ci.go:37:6)
	q := r.query.Select("withBrunoCiOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type BrunoCollection in the environment
func (r *Env) WithBrunoCollectionInput(name string, value *BrunoCollection, description string) *Env { // bruno (../../../../../daggerverse/bruno/collection.go:86:6)
	assertNotNil("value", value)
	q := r.query.Select("withBrunoCollectionInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired BrunoCollection output to be assigned in the environment
func (r *Env) WithBrunoCollectionOutput(name string, description string) *Env { // bruno (../../../../../daggerverse/bruno/collection.go:86:6)
	q := r.query.Select("withBrunoCollectionOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Bruno in the environment
func (r *Env) WithBrunoInput(name string, value *Bruno, description string) *Env { // bruno (../../../../../daggerverse/bruno/main.go:47:6)
	assertNotNil("value", value)
	q := r.query.Select("withBrunoInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Bruno output to be assigned in the environment
func (r *Env) WithBrunoOutput(name string, description string) *Env { // bruno (../../../../../daggerverse/bruno/main.go:47:6)
	q := r.query.Select("withBrunoOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// BrunoOpts contains options for Query.Bruno
type BrunoOpts struct {
	//
	// Container registry hosting the usebruno/cli image. Upstream publishes
	// the same image to docker.io and ghcr.io.
	//
	//
	// Default: "docker.io"
	Registry string // bruno (../../../../../daggerverse/bruno/main.go:61:2)
	//
	// Image tag for usebruno/cli, which is the Bruno CLI release it ships.
	//
	//
	// Default: "3.4.2"
	Version string // bruno (../../../../../daggerverse/bruno/main.go:64:2)
	//
	// Select the Debian variant (node:22-slim) of the image. The suffix is
	// appended to version, so debian=true with the default 3.4.2 resolves
	// 3.4.2-debian. The Alpine default hits musl/OpenSSL failures against
	// some TLS endpoints, which is what this variant is for.
	//
	Debian bool // bruno (../../../../../daggerverse/bruno/main.go:70:2)
}

// New returns a Bruno module backed by <registry>/usebruno/cli:<version>.
func (r *Query) Bruno(opts ...BrunoOpts) *Bruno { // bruno (../../../../../daggerverse/bruno/main.go:57:1)
	q := r.query.Select("bruno")
	for i := len(opts) - 1; i >= 0; i-- {
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `debian` optional argument
		if !querybuilder.IsZeroValue(opts[i].Debian) {
			q = q.Arg("debian", opts[i].Debian)
		}
	}

	return &Bruno{
		query: q,
	}
}
