// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type OtelTests
func (r *Binding) AsOtelTests() *OtelTests { // otel-tests (../../../daggerverse/otel/tests/main.go:15:6)
	q := r.query.Select("asOtelTests")

	return &OtelTests{
		query: q,
	}
}

// Create or update a binding of type OtelTests in the environment
func (r *Env) WithOtelTestsInput(name string, value *OtelTests, description string) *Env { // otel-tests (../../../daggerverse/otel/tests/main.go:15:6)
	assertNotNil("value", value)
	q := r.query.Select("withOtelTestsInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired OtelTests output to be assigned in the environment
func (r *Env) WithOtelTestsOutput(name string, description string) *Env { // otel-tests (../../../daggerverse/otel/tests/main.go:15:6)
	q := r.query.Select("withOtelTestsOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type OtelTests struct { // otel-tests (../../../daggerverse/otel/tests/main.go:15:6)
	query *querybuilder.Selection

	all                                   *Void
	bindsCollectorIntoFreshContainer      *Void
	conflictingComponentBodiesAreRejected *Void
	contrib                               *Void
	contribForwardsLogsToLoki             *Void
	core                                  *Void
	coreForwardsLogsToLoki                *Void
	coreForwardsMetricsToMimir            *Void
	coreForwardsTracesToTempo             *Void
	customComponentBodyIsSpliced          *Void
	debugPipelineAcceptsOtlpPush          *Void
	id                                    *ID
	rejectsInvalidComponentName           *Void
	rejectsUnknownPipelineSignal          *Void
	serviceWithoutPipelinesOrConfigFails  *Void
	sharedReceiverIsDedupedInRenderedYaml *Void
	validation                            *Void
}

func (r *OtelTests) WithGraphQLQuery(q *querybuilder.Selection) *OtelTests {
	return &OtelTests{
		query: q,
	}
}

// OtelTestsAllOpts contains options for OtelTests.All
type OtelTestsAllOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:33:2)

	// Default: "3.4.1"
	LokiTag string // otel-tests (../../../daggerverse/otel/tests/main.go:35:2)

	// Default: "2.7.1"
	TempoTag string // otel-tests (../../../daggerverse/otel/tests/main.go:37:2)

	// Default: "2.15.1"
	MimirTag string // otel-tests (../../../daggerverse/otel/tests/main.go:39:2)

	Parallel int // otel-tests (../../../daggerverse/otel/tests/main.go:41:2)
}

// All runs every otel test inside this suite as a convenience for local
// `dagger call all` invocations. CI does NOT call All: each of the three
// sub-aggregators below (Validation, Core, Contrib) carries its own
// `+check` directive, so GH Actions schedules each onto its own runner
// in parallel — running All on top would double-bill the same work.
//
// collectorTag picks the otel/opentelemetry-collector{,-contrib} tag
// every spawned collector runs against; lokiTag/tempoTag/mimirTag pick
// the grafana/{loki,tempo,mimir} tags for the round-trip backends.
//
// parallel caps how many tests run concurrently. Defaults to 0 (unbounded).
func (r *OtelTests) All(ctx context.Context, opts ...OtelTestsAllOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:30:1)
	if r.all != nil {
		return nil
	}
	q := r.query.Select("all")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `lokiTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].LokiTag) {
			q = q.Arg("lokiTag", opts[i].LokiTag)
		}
		// `tempoTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].TempoTag) {
			q = q.Arg("tempoTag", opts[i].TempoTag)
		}
		// `mimirTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].MimirTag) {
			q = q.Arg("mimirTag", opts[i].MimirTag)
		}
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsBindsCollectorIntoFreshContainerOpts contains options for OtelTests.BindsCollectorIntoFreshContainer
type OtelTestsBindsCollectorIntoFreshContainerOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:277:2)
}

// BindsCollectorIntoFreshContainer asserts that a collector configured
// with the DebugPipeline can be reached on :4317 and :4318 from a
// vanilla alpine container via WithServiceBinding.
func (r *OtelTests) BindsCollectorIntoFreshContainer(ctx context.Context, opts ...OtelTestsBindsCollectorIntoFreshContainerOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:274:1)
	if r.bindsCollectorIntoFreshContainer != nil {
		return nil
	}
	q := r.query.Select("bindsCollectorIntoFreshContainer")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsConflictingComponentBodiesAreRejectedOpts contains options for OtelTests.ConflictingComponentBodiesAreRejected
type OtelTestsConflictingComponentBodiesAreRejectedOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:346:2)
}

// ConflictingComponentBodiesAreRejected asserts that wiring two
// distinct *CustomExporter instances sharing the same <kind>/<name>
// but with different bodies into the pipeline graph surfaces a
// non-nil error from the rendered-config path, rather than silently
// keeping whichever was registered first.
func (r *OtelTests) ConflictingComponentBodiesAreRejected(ctx context.Context, opts ...OtelTestsConflictingComponentBodiesAreRejectedOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:343:1)
	if r.conflictingComponentBodiesAreRejected != nil {
		return nil
	}
	q := r.query.Select("conflictingComponentBodiesAreRejected")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsContribOpts contains options for OtelTests.Contrib
type OtelTestsContribOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:146:2)

	// Default: "3.4.1"
	LokiTag string // otel-tests (../../../daggerverse/otel/tests/main.go:148:2)

	Parallel int // otel-tests (../../../daggerverse/otel/tests/main.go:150:2)
}

// Contrib runs the otel-collector-contrib-image round-trip tests.
func (r *OtelTests) Contrib(ctx context.Context, opts ...OtelTestsContribOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:143:1)
	if r.contrib != nil {
		return nil
	}
	q := r.query.Select("contrib")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `lokiTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].LokiTag) {
			q = q.Arg("lokiTag", opts[i].LokiTag)
		}
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsContribForwardsLogsToLokiOpts contains options for OtelTests.ContribForwardsLogsToLoki
type OtelTestsContribForwardsLogsToLokiOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:604:2)

	// Default: "3.4.1"
	LokiTag string // otel-tests (../../../daggerverse/otel/tests/main.go:606:2)
}

// ContribForwardsLogsToLoki — smoke check on the contrib distribution.
func (r *OtelTests) ContribForwardsLogsToLoki(ctx context.Context, opts ...OtelTestsContribForwardsLogsToLokiOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:601:1)
	if r.contribForwardsLogsToLoki != nil {
		return nil
	}
	q := r.query.Select("contribForwardsLogsToLoki")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `lokiTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].LokiTag) {
			q = q.Arg("lokiTag", opts[i].LokiTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsCoreOpts contains options for OtelTests.Core
type OtelTestsCoreOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:108:2)

	// Default: "3.4.1"
	LokiTag string // otel-tests (../../../daggerverse/otel/tests/main.go:110:2)

	// Default: "2.7.1"
	TempoTag string // otel-tests (../../../daggerverse/otel/tests/main.go:112:2)

	// Default: "2.15.1"
	MimirTag string // otel-tests (../../../daggerverse/otel/tests/main.go:114:2)

	Parallel int // otel-tests (../../../daggerverse/otel/tests/main.go:116:2)
}

// Core runs the otel-collector core-image round-trip tests. Each test
// boots one Loki/Tempo/Mimir alongside the collector, so this group's
// per-runner footprint is the heaviest in the suite.
func (r *OtelTests) Core(ctx context.Context, opts ...OtelTestsCoreOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:105:1)
	if r.core != nil {
		return nil
	}
	q := r.query.Select("core")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `lokiTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].LokiTag) {
			q = q.Arg("lokiTag", opts[i].LokiTag)
		}
		// `tempoTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].TempoTag) {
			q = q.Arg("tempoTag", opts[i].TempoTag)
		}
		// `mimirTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].MimirTag) {
			q = q.Arg("mimirTag", opts[i].MimirTag)
		}
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsCoreForwardsLogsToLokiOpts contains options for OtelTests.CoreForwardsLogsToLoki
type OtelTestsCoreForwardsLogsToLokiOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:580:2)

	// Default: "3.4.1"
	LokiTag string // otel-tests (../../../daggerverse/otel/tests/main.go:582:2)
}

// CoreForwardsLogsToLoki asserts a Core collector forwards an OTLP/HTTP
// log push through to the grafana-stack Loki backend, where it is
// queryable via LogQL.
func (r *OtelTests) CoreForwardsLogsToLoki(ctx context.Context, opts ...OtelTestsCoreForwardsLogsToLokiOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:577:1)
	if r.coreForwardsLogsToLoki != nil {
		return nil
	}
	q := r.query.Select("coreForwardsLogsToLoki")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `lokiTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].LokiTag) {
			q = q.Arg("lokiTag", opts[i].LokiTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsCoreForwardsMetricsToMimirOpts contains options for OtelTests.CoreForwardsMetricsToMimir
type OtelTestsCoreForwardsMetricsToMimirOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:731:2)

	// Default: "2.15.1"
	MimirTag string // otel-tests (../../../daggerverse/otel/tests/main.go:733:2)
}

// CoreForwardsMetricsToMimir asserts an OTLP/HTTP metric pushed to the
// collector lands in Mimir via the OTLP/HTTP exporter and is
// queryable via the Prometheus API.
func (r *OtelTests) CoreForwardsMetricsToMimir(ctx context.Context, opts ...OtelTestsCoreForwardsMetricsToMimirOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:728:1)
	if r.coreForwardsMetricsToMimir != nil {
		return nil
	}
	q := r.query.Select("coreForwardsMetricsToMimir")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `mimirTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].MimirTag) {
			q = q.Arg("mimirTag", opts[i].MimirTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsCoreForwardsTracesToTempoOpts contains options for OtelTests.CoreForwardsTracesToTempo
type OtelTestsCoreForwardsTracesToTempoOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:629:2)

	// Default: "2.7.1"
	TempoTag string // otel-tests (../../../daggerverse/otel/tests/main.go:631:2)
}

// CoreForwardsTracesToTempo asserts an OTLP/HTTP trace pushed to the
// collector lands in Tempo via the OTLP/gRPC exporter.
func (r *OtelTests) CoreForwardsTracesToTempo(ctx context.Context, opts ...OtelTestsCoreForwardsTracesToTempoOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:626:1)
	if r.coreForwardsTracesToTempo != nil {
		return nil
	}
	q := r.query.Select("coreForwardsTracesToTempo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `tempoTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].TempoTag) {
			q = q.Arg("tempoTag", opts[i].TempoTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsCustomComponentBodyIsSplicedOpts contains options for OtelTests.CustomComponentBodyIsSpliced
type OtelTestsCustomComponentBodyIsSplicedOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:369:2)
}

// CustomComponentBodyIsSpliced asserts that a Custom* component's
// caller-supplied YAML body lands structurally under the rendered
// config (not as a quoted scalar).
func (r *OtelTests) CustomComponentBodyIsSpliced(ctx context.Context, opts ...OtelTestsCustomComponentBodyIsSplicedOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:366:1)
	if r.customComponentBodyIsSpliced != nil {
		return nil
	}
	q := r.query.Select("customComponentBodyIsSpliced")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsDebugPipelineAcceptsOtlpPushOpts contains options for OtelTests.DebugPipelineAcceptsOtlpPush
type OtelTestsDebugPipelineAcceptsOtlpPushOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:186:2)
}

// DebugPipelineAcceptsOtlpPush asserts a collector configured with
// DebugPipeline("logs") accepts an OTLP/HTTP log push without
// erroring (HTTP 200/204).
func (r *OtelTests) DebugPipelineAcceptsOtlpPush(ctx context.Context, opts ...OtelTestsDebugPipelineAcceptsOtlpPushOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:183:1)
	if r.debugPipelineAcceptsOtlpPush != nil {
		return nil
	}
	q := r.query.Select("debugPipelineAcceptsOtlpPush")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this OtelTests.
func (r *OtelTests) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *OtelTests) XXX_GraphQLType() string {
	return "OtelTests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *OtelTests) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *OtelTests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *OtelTests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *OtelTests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = OtelTests{query: selectNode(dag.query, id, "OtelTests")}
	return nil
}

// RejectsInvalidComponentName asserts every component factory and the
// Custom* escape hatches reject empty / non-conforming names (and
// non-conforming kinds, where applicable) with a non-nil error.
func (r *OtelTests) RejectsInvalidComponentName(ctx context.Context) error { // otel-tests (../../../daggerverse/otel/tests/main.go:423:1)
	if r.rejectsInvalidComponentName != nil {
		return nil
	}
	q := r.query.Select("rejectsInvalidComponentName")

	return q.Execute(ctx)
}

// RejectsUnknownPipelineSignal asserts Otel.Pipeline rejects signals
// outside {logs, traces, metrics}, and Otel.DebugPipeline does the same.
func (r *OtelTests) RejectsUnknownPipelineSignal(ctx context.Context) error { // otel-tests (../../../daggerverse/otel/tests/main.go:400:1)
	if r.rejectsUnknownPipelineSignal != nil {
		return nil
	}
	q := r.query.Select("rejectsUnknownPipelineSignal")

	return q.Execute(ctx)
}

// OtelTestsServiceWithoutPipelinesOrConfigFailsOpts contains options for OtelTests.ServiceWithoutPipelinesOrConfigFails
type OtelTestsServiceWithoutPipelinesOrConfigFailsOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:294:2)
}

// ServiceWithoutPipelinesOrConfigFails asserts that calling Service()
// on a collector with no pipelines and no override produces a
// container whose exec exits non-zero — the collector binary refuses
// to start without --config.
func (r *OtelTests) ServiceWithoutPipelinesOrConfigFails(ctx context.Context, opts ...OtelTestsServiceWithoutPipelinesOrConfigFailsOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:291:1)
	if r.serviceWithoutPipelinesOrConfigFails != nil {
		return nil
	}
	q := r.query.Select("serviceWithoutPipelinesOrConfigFails")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsSharedReceiverIsDedupedInRenderedYamlOpts contains options for OtelTests.SharedReceiverIsDedupedInRenderedYaml
type OtelTestsSharedReceiverIsDedupedInRenderedYamlOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:309:2)
}

// SharedReceiverIsDedupedInRenderedYaml asserts that wiring one
// receiver into three pipelines emits a single top-level
// receivers.otlp/primary entry rather than three.
func (r *OtelTests) SharedReceiverIsDedupedInRenderedYaml(ctx context.Context, opts ...OtelTestsSharedReceiverIsDedupedInRenderedYamlOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:306:1)
	if r.sharedReceiverIsDedupedInRenderedYaml != nil {
		return nil
	}
	q := r.query.Select("sharedReceiverIsDedupedInRenderedYaml")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
	}

	return q.Execute(ctx)
}

// OtelTestsValidationOpts contains options for OtelTests.Validation
type OtelTestsValidationOpts struct {

	// Default: "0.130.1"
	CollectorTag string // otel-tests (../../../daggerverse/otel/tests/main.go:69:2)

	Parallel int // otel-tests (../../../daggerverse/otel/tests/main.go:71:2)
}

// Validation runs the otel validation + rendering tests that don't need
// a backend service stood up. Pure-unit + collector-only spin-ups.
func (r *OtelTests) Validation(ctx context.Context, opts ...OtelTestsValidationOpts) error { // otel-tests (../../../daggerverse/otel/tests/main.go:66:1)
	if r.validation != nil {
		return nil
	}
	q := r.query.Select("validation")
	for i := len(opts) - 1; i >= 0; i-- {
		// `collectorTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].CollectorTag) {
			q = q.Arg("collectorTag", opts[i].CollectorTag)
		}
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this OtelTests as a Node.
// This is a local type conversion — no GraphQL call.
func (r *OtelTests) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Package main is the otel-tests Dagger module: round-trip and unit
// checks for the otel daggerverse module.
func (r *Query) OtelTests() *OtelTests { // otel-tests (../../../daggerverse/otel/tests/main.go:15:6)
	q := r.query.Select("otelTests")

	return &OtelTests{
		query: q,
	}
}
