// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `PostgresTestsID` scalar type represents an identifier for an object of type PostgresTests.
type PostgresTestsID string // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)

// Retrieve the binding value, as type PostgresTests
func (r *Binding) AsPostgresTests() *PostgresTests { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	q := r.query.Select("asPostgresTests")

	return &PostgresTests{
		query: q,
	}
}

// Create or update a binding of type PostgresTests in the environment
func (r *Env) WithPostgresTestsInput(name string, value *PostgresTests, description string) *Env { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	assertNotNil("value", value)
	q := r.query.Select("withPostgresTestsInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired PostgresTests output to be assigned in the environment
func (r *Env) WithPostgresTestsOutput(name string, description string) *Env { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	q := r.query.Select("withPostgresTestsOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type PostgresTests struct { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	query *querybuilder.Selection

	all                            *Void
	applyFileRoundTrip             *Void
	bindPrimaryReachableFromAlpine *Void
	clientPingWrongPasswordFails   *Void
	cluster                        *Void
	clusterRejectsNilPassword      *Void
	clusterRejectsNilSecurity      *Void
	defaultsProduceHealthyPrimary  *Void
	endpointShouldNotBeCached      *Void
	execScalarRoundTrip            *Void
	id                             *PostgresTestsID
	passwordReusableViaClient      *Void
	queryJsonreturnsRowObjects     *Void
	scalarShouldNotBeCached        *Void
	userDatabaseRoundTrip          *Void
	validation                     *Void
}

func (r *PostgresTests) WithGraphQLQuery(q *querybuilder.Selection) *PostgresTests {
	return &PostgresTests{
		query: q,
	}
}

// PostgresTestsAllOpts contains options for PostgresTests.All
type PostgresTestsAllOpts struct {
	Parallel int // postgres-tests (../../../daggerverse/postgres/tests/main.go:34:2)
}

// All runs every postgres test as a convenience for local `dagger call
// all` invocations. CI does NOT call All: each of the two
// sub-aggregators below (Validation, Cluster) carries its own `directive, so GH Actions schedules each onto its own runner in
// parallel — running All on top would double-bill the same work.
func (r *PostgresTests) All(ctx context.Context, opts ...PostgresTestsAllOpts) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:31:1)
	if r.all != nil {
		return nil
	}
	q := r.query.Select("all")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// ApplyFileRoundTrip runs a multi-statement *dagger.File and confirms
// the resulting rows are readable via Scalar.
func (r *PostgresTests) ApplyFileRoundTrip(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:534:1)
	if r.applyFileRoundTrip != nil {
		return nil
	}
	q := r.query.Select("applyFileRoundTrip")

	return q.Execute(ctx)
}

// BindPrimaryReachableFromAlpine verifies BindPrimary makes the primary
// reachable at Cluster.Endpoint() from a fresh alpine container. Alpine
// lacks pg_isready, so we prove TCP reachability with busybox nc.
func (r *PostgresTests) BindPrimaryReachableFromAlpine(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:424:1)
	if r.bindPrimaryReachableFromAlpine != nil {
		return nil
	}
	q := r.query.Select("bindPrimaryReachableFromAlpine")

	return q.Execute(ctx)
}

// ClientPingWrongPasswordFails verifies a correct-password Ping succeeds
// and a wrong-password Ping fails with an auth error.
func (r *PostgresTests) ClientPingWrongPasswordFails(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:447:1)
	if r.clientPingWrongPasswordFails != nil {
		return nil
	}
	q := r.query.Select("clientPingWrongPasswordFails")

	return q.Execute(ctx)
}

// PostgresTestsClusterOpts contains options for PostgresTests.Cluster
type PostgresTestsClusterOpts struct {
	Parallel int // postgres-tests (../../../daggerverse/postgres/tests/main.go:85:2)
}

// Cluster runs the topology and client round-trip tests. Each test
// passes its own name to bootCluster, which folds into Postgres.Cluster's
// session-cache key so concurrent tests boot independent backing
// services and never share storage.
func (r *PostgresTests) Cluster(ctx context.Context, opts ...PostgresTestsClusterOpts) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:82:1)
	if r.cluster != nil {
		return nil
	}
	q := r.query.Select("cluster")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// ClusterRejectsNilPassword verifies a nil password is rejected.
func (r *PostgresTests) ClusterRejectsNilPassword(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:173:1)
	if r.clusterRejectsNilPassword != nil {
		return nil
	}
	q := r.query.Select("clusterRejectsNilPassword")

	return q.Execute(ctx)
}

// ClusterRejectsNilSecurity verifies a nil clientListenerSecurity is rejected.
func (r *PostgresTests) ClusterRejectsNilSecurity(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:192:1)
	if r.clusterRejectsNilSecurity != nil {
		return nil
	}
	q := r.query.Select("clusterRejectsNilSecurity")

	return q.Execute(ctx)
}

// DefaultsProduceHealthyPrimary boots a default cluster and proves it is
// a healthy primary by running `pg_isready` against it from a container
// running the postgres image (which ships pg_isready), bound via
// BindPrimary.
func (r *PostgresTests) DefaultsProduceHealthyPrimary(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:307:1)
	if r.defaultsProduceHealthyPrimary != nil {
		return nil
	}
	q := r.query.Select("defaultsProduceHealthyPrimary")

	return q.Execute(ctx)
}

// EndpointShouldNotBeCached verifies the chained cluster methods
// re-execute underresult. Endpoint is a pure address getter, so we exercise the
// re-execution that matters: Ping (which starts the service), Stop
// (which kills it), then Ping again — the second Ping must re-start the
// killed service. If Client/start were cached, the service would stay
// dead and the second Ping would dial a hung port. We also assert the
// Endpoint address is stable across the cycle.
func (r *PostgresTests) EndpointShouldNotBeCached(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:228:1)
	if r.endpointShouldNotBeCached != nil {
		return nil
	}
	q := r.query.Select("endpointShouldNotBeCached")

	return q.Execute(ctx)
}

// ExecScalarRoundTrip runs a CREATE TABLE + INSERT + SELECT count(*)
// sequence across chained Cluster.Client() calls, proving the
// Client handles.
func (r *PostgresTests) ExecScalarRoundTrip(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:495:1)
	if r.execScalarRoundTrip != nil {
		return nil
	}
	q := r.query.Select("execScalarRoundTrip")

	return q.Execute(ctx)
}

// A unique identifier for this PostgresTests.
func (r *PostgresTests) ID(ctx context.Context) (PostgresTestsID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response PostgresTestsID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *PostgresTests) XXX_GraphQLType() string {
	return "PostgresTests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *PostgresTests) XXX_GraphQLIDType() string {
	return "PostgresTestsID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *PostgresTests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *PostgresTests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *PostgresTests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadPostgresTestsFromID(PostgresTestsID(id))
	return nil
}

// PasswordReusableViaClient verifies Cluster.Password() returns a secret
// whose plaintext equals the provisioning password: re-using it via
// Postgres.Client against the same endpoint authenticates successfully.
func (r *PostgresTests) PasswordReusableViaClient(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:382:1)
	if r.passwordReusableViaClient != nil {
		return nil
	}
	q := r.query.Select("passwordReusableViaClient")

	return q.Execute(ctx)
}

// QueryJSONReturnsRowObjects verifies QueryJSON returns a *dagger.File
// whose contents parse as a JSON array of row objects keyed by column
// name.
func (r *PostgresTests) QueryJsonreturnsRowObjects(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:570:1)
	if r.queryJsonreturnsRowObjects != nil {
		return nil
	}
	q := r.query.Select("queryJsonreturnsRowObjects")

	return q.Execute(ctx)
}

// ScalarShouldNotBeCached verifies Scalar re-executes on every call. We
// insert one row, read count(*) == "1", insert a second row, then read
// count(*) again: a cached Scalar would still report "1" instead of "2".
func (r *PostgresTests) ScalarShouldNotBeCached(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:261:1)
	if r.scalarShouldNotBeCached != nil {
		return nil
	}
	q := r.query.Select("scalarShouldNotBeCached")

	return q.Execute(ctx)
}

// UserDatabaseRoundTrip verifies Cluster.User()/Database() echo the
// inputs and a pgx round-trip confirms current_user / current_database
// match.
func (r *PostgresTests) UserDatabaseRoundTrip(ctx context.Context) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:342:1)
	if r.userDatabaseRoundTrip != nil {
		return nil
	}
	q := r.query.Select("userDatabaseRoundTrip")

	return q.Execute(ctx)
}

// PostgresTestsValidationOpts contains options for PostgresTests.Validation
type PostgresTestsValidationOpts struct {
	Parallel int // postgres-tests (../../../daggerverse/postgres/tests/main.go:60:2)
}

// Validation runs the input-rejection tests plus the cache-directive
// tests (*ShouldNotBeCached). These don't share session-cached cluster
// state with one another, so they're safe to fan out unbounded.
func (r *PostgresTests) Validation(ctx context.Context, opts ...PostgresTestsValidationOpts) error { // postgres-tests (../../../daggerverse/postgres/tests/main.go:57:1)
	if r.validation != nil {
		return nil
	}
	q := r.query.Select("validation")
	for i := len(opts) - 1; i >= 0; i-- {
		// `parallel` optional argument
		if !querybuilder.IsZeroValue(opts[i].Parallel) {
			q = q.Arg("parallel", opts[i].Parallel)
		}
	}

	return q.Execute(ctx)
}

// Load a PostgresTests from its ID.
func (r *Query) LoadPostgresTestsFromID(id PostgresTestsID) *PostgresTests { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	q := r.query.Select("loadPostgresTestsFromID")
	q = q.Arg("id", id)

	return &PostgresTests{
		query: q,
	}
}

// Tests for the postgres daggerverse module. Each test is exposed as a
// standalone dagger function so it can be invoked individually during
// TDD; All wires them up for parallel execution under
// `dagger call all`.
//
// Every password, cluster name, role, database, and table name is
// minted at runtime via dag.Random().Sha256 — no literals leak into the
// suite.
func (r *Query) PostgresTests() *PostgresTests { // postgres-tests (../../../daggerverse/postgres/tests/main.go:22:6)
	q := r.query.Select("postgresTests")

	return &PostgresTests{
		query: q,
	}
}
