name = "kafka"
engineVersion = "v1.0.0-beta.15"
include = ["!README.md"]

[runtime]
  source = "go"

[[dependencies]]
  name = "certificate-management"
  source = "../certificate-management"

[[dependencies]]
  name = "crypto"
  source = "../crypto"

[[dependencies]]
  name = "random"
  source = "../random"

[codegen]
  automaticGitignore = false
