// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `KubernetesClientID` scalar type represents an identifier for an object of type KubernetesClient.
type KubernetesClientID string // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)

// The `KubernetesClusterID` scalar type represents an identifier for an object of type KubernetesCluster.
type KubernetesClusterID string // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)

// The `KubernetesID` scalar type represents an identifier for an object of type Kubernetes.
type KubernetesID string // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)

// Retrieve the binding value, as type Kubernetes
func (r *Binding) AsKubernetes() *Kubernetes { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	q := r.query.Select("asKubernetes")

	return &Kubernetes{
		query: q,
	}
}

// Retrieve the binding value, as type KubernetesClient
func (r *Binding) AsKubernetesClient() *KubernetesClient { // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)
	q := r.query.Select("asKubernetesClient")

	return &KubernetesClient{
		query: q,
	}
}

// Retrieve the binding value, as type KubernetesCluster
func (r *Binding) AsKubernetesCluster() *KubernetesCluster { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)
	q := r.query.Select("asKubernetesCluster")

	return &KubernetesCluster{
		query: q,
	}
}

// Create or update a binding of type KubernetesClient in the environment
func (r *Env) WithKubernetesClientInput(name string, value *KubernetesClient, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)
	assertNotNil("value", value)
	q := r.query.Select("withKubernetesClientInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired KubernetesClient output to be assigned in the environment
func (r *Env) WithKubernetesClientOutput(name string, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)
	q := r.query.Select("withKubernetesClientOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type KubernetesCluster in the environment
func (r *Env) WithKubernetesClusterInput(name string, value *KubernetesCluster, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)
	assertNotNil("value", value)
	q := r.query.Select("withKubernetesClusterInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired KubernetesCluster output to be assigned in the environment
func (r *Env) WithKubernetesClusterOutput(name string, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)
	q := r.query.Select("withKubernetesClusterOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Kubernetes in the environment
func (r *Env) WithKubernetesInput(name string, value *Kubernetes, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	assertNotNil("value", value)
	q := r.query.Select("withKubernetesInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Kubernetes output to be assigned in the environment
func (r *Env) WithKubernetesOutput(name string, description string) *Env { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	q := r.query.Select("withKubernetesOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Kubernetes is the root namespace for every exported function in
// this module. All cluster constructors and the remote-client factory
// hang off *Kubernetes so the generated Dagger SDK surfaces them
// under `dag.Kubernetes().<Func>(...)`.
type Kubernetes struct { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	query *querybuilder.Selection

	id *KubernetesID
}

func (r *Kubernetes) WithGraphQLQuery(q *querybuilder.Selection) *Kubernetes {
	return &Kubernetes{
		query: q,
	}
}

// Client constructs a client-go-backed Kubernetes client that targets
// the cluster described by the supplied kubeconfig. No I/O happens at
// construction time. Works against a local KindCluster or any
// reachable remote cluster — the kubeconfig is the only handle the
// client needs.
func (r *Kubernetes) Client(kubeconfig *File) *KubernetesClient { // kubernetes (../../../../../daggerverse/kubernetes/client.go:43:1)
	assertNotNil("kubeconfig", kubeconfig)
	q := r.query.Select("client")
	q = q.Arg("kubeconfig", kubeconfig)

	return &KubernetesClient{
		query: q,
	}
}

// A unique identifier for this Kubernetes.
func (r *Kubernetes) ID(ctx context.Context) (KubernetesID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response KubernetesID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Kubernetes) XXX_GraphQLType() string {
	return "Kubernetes"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Kubernetes) XXX_GraphQLIDType() string {
	return "KubernetesID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Kubernetes) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Kubernetes) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Kubernetes) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadKubernetesFromID(KubernetesID(id))
	return nil
}

// KubernetesKindClusterOpts contains options for Kubernetes.KindCluster
type KubernetesKindClusterOpts struct {
	ClusterName string // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:77:2)

	// Default: 1
	ControlPlanes int // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:79:2)

	Workers int // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:81:2)

	// Default: "docker.io"
	Registry string // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:83:2)

	// Default: "v1.31.0"
	Tag string // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:85:2)
}

// KindCluster spins up a Kubernetes cluster of one control-plane node
// plus `workers` worker nodes, each running upstream kindest/node as
// a privileged Dagger Service. Kind always issues TLS internally; the
// auto-generated admin kubeconfig (Cluster.Kubeconfig) is the sole
// security material in this story.
//
// Image: `<registry>/kindest/node:<tag>` — the `kindest/node` portion
// is fixed; only `registry` and `tag` are caller-overridable.
//
// Rejected inputs (each surfaces a descriptive error rather than
// booting a half-broken cluster):
//
//   - `controlPlanes != 1` — HA control-plane requires an HAProxy LB
//     in front of N kube-apiservers; that lands in a follow-up story.
//   - `workers < 0`.
//
// Session-cached so chained method calls on the returned cluster
// (e.g. Client.Apply → Client.Get) observe the SAME underlying
// services. Every method on *Cluster carriesown line so any data-returning call re-executes per invocation.
//
// `clusterName` is a caller-supplied discriminator that folds into
// the session cache key. Parallel test suites should pass a unique
// value per test (e.g. the test function name) so each test gets its
// own backing services.
func (r *Kubernetes) KindCluster(opts ...KubernetesKindClusterOpts) *KubernetesCluster { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:74:1)
	q := r.query.Select("kindCluster")
	for i := len(opts) - 1; i >= 0; i-- {
		// `clusterName` optional argument
		if !querybuilder.IsZeroValue(opts[i].ClusterName) {
			q = q.Arg("clusterName", opts[i].ClusterName)
		}
		// `controlPlanes` optional argument
		if !querybuilder.IsZeroValue(opts[i].ControlPlanes) {
			q = q.Arg("controlPlanes", opts[i].ControlPlanes)
		}
		// `workers` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workers) {
			q = q.Arg("workers", opts[i].Workers)
		}
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
	}

	return &KubernetesCluster{
		query: q,
	}
}

// Client is a client-go-backed Kubernetes client. Each method opens a
// fresh REST + dynamic client per call so the function is stateless
// from Dagger's perspective.
type KubernetesClient struct { // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)
	query *querybuilder.Selection

	apply        *Void
	delete       *Void
	get          *string
	id           *KubernetesClientID
	waitForReady *Void
}

func (r *KubernetesClient) WithGraphQLQuery(q *querybuilder.Selection) *KubernetesClient {
	return &KubernetesClient{
		query: q,
	}
}

// Apply applies every YAML document in the manifest file to the
// cluster via server-side apply. Multi-document YAML is supported —
// the file is split on `---` separators and each document is decoded
// into an `unstructured.Unstructured`, mapped to its GVR via discovery,
// then applied with field manager `devex-kubernetes-module`.
//
// Malformed manifest YAML surfaces a wrapped decode error.
func (r *KubernetesClient) Apply(ctx context.Context, manifest *File) error { // kubernetes (../../../../../daggerverse/kubernetes/client.go:76:1)
	assertNotNil("manifest", manifest)
	if r.apply != nil {
		return nil
	}
	q := r.query.Select("apply")
	q = q.Arg("manifest", manifest)

	return q.Execute(ctx)
}

// Delete deletes every resource named by every YAML document in the
// manifest file. Missing resources (404) are treated as success — the
// post-condition of Delete is "this resource does not exist".
func (r *KubernetesClient) Delete(ctx context.Context, manifest *File) error { // kubernetes (../../../../../daggerverse/kubernetes/client.go:107:1)
	assertNotNil("manifest", manifest)
	if r.delete != nil {
		return nil
	}
	q := r.query.Select("delete")
	q = q.Arg("manifest", manifest)

	return q.Execute(ctx)
}

// KubernetesClientGetOpts contains options for KubernetesClient.Get
type KubernetesClientGetOpts struct {
	Namespace string // kubernetes (../../../../../daggerverse/kubernetes/client.go:145:2)
}

// Get returns the named resource as YAML. `resource` accepts the
// kubectl-style GVR shorthand (`"namespaces"`, `"pods"`,
// `"deployments.apps"`); the discovery RESTMapper resolves it to the
// preferred GVR. Empty `namespace` is meaningful only for cluster-scoped
// resources; namespaced resources require a non-empty namespace.
//
// Unknown resource shorthand returns an explicit "unknown resource"
// error.
func (r *KubernetesClient) Get(ctx context.Context, resource string, name string, opts ...KubernetesClientGetOpts) (string, error) { // kubernetes (../../../../../daggerverse/kubernetes/client.go:143:1)
	if r.get != nil {
		return *r.get, nil
	}
	q := r.query.Select("get")
	for i := len(opts) - 1; i >= 0; i-- {
		// `namespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Namespace) {
			q = q.Arg("namespace", opts[i].Namespace)
		}
	}
	q = q.Arg("resource", resource)
	q = q.Arg("name", name)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this KubernetesClient.
func (r *KubernetesClient) ID(ctx context.Context) (KubernetesClientID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response KubernetesClientID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *KubernetesClient) XXX_GraphQLType() string {
	return "KubernetesClient"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *KubernetesClient) XXX_GraphQLIDType() string {
	return "KubernetesClientID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *KubernetesClient) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *KubernetesClient) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *KubernetesClient) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadKubernetesClientFromID(KubernetesClientID(id))
	return nil
}

// Kubeconfig returns the kubeconfig file this client is configured to use.
func (r *KubernetesClient) Kubeconfig() *File { // kubernetes (../../../../../daggerverse/kubernetes/client.go:63:1)
	q := r.query.Select("kubeconfig")

	return &File{
		query: q,
	}
}

// KubernetesClientListOpts contains options for KubernetesClient.List
type KubernetesClientListOpts struct {
	Namespace string // kubernetes (../../../../../daggerverse/kubernetes/client.go:176:2)
}

// List returns the metadata.name of every resource of the given
// shorthand. Empty `namespace` lists across all namespaces for
// namespaced resources, or returns every cluster-scoped resource for
// cluster-scoped shorthands like `nodes` or `namespaces`.
func (r *KubernetesClient) List(ctx context.Context, resource string, opts ...KubernetesClientListOpts) ([]string, error) { // kubernetes (../../../../../daggerverse/kubernetes/client.go:174:1)
	q := r.query.Select("list")
	for i := len(opts) - 1; i >= 0; i-- {
		// `namespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Namespace) {
			q = q.Arg("namespace", opts[i].Namespace)
		}
	}
	q = q.Arg("resource", resource)

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// KubernetesClientWaitForReadyOpts contains options for KubernetesClient.WaitForReady
type KubernetesClientWaitForReadyOpts struct {
	Namespace string // kubernetes (../../../../../daggerverse/kubernetes/client.go:206:2)

	// Default: "60s"
	Timeout string // kubernetes (../../../../../daggerverse/kubernetes/client.go:209:2)
}

// WaitForReady blocks until the named resource reports a condition
// indicating readiness, or `timeout` elapses. For Deployments the
// `Available: True` condition counts; for everything else the `Ready`
// condition counts. timeout is parsed via time.ParseDuration.
func (r *KubernetesClient) WaitForReady(ctx context.Context, resource string, name string, opts ...KubernetesClientWaitForReadyOpts) error { // kubernetes (../../../../../daggerverse/kubernetes/client.go:204:1)
	if r.waitForReady != nil {
		return nil
	}
	q := r.query.Select("waitForReady")
	for i := len(opts) - 1; i >= 0; i-- {
		// `namespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Namespace) {
			q = q.Arg("namespace", opts[i].Namespace)
		}
		// `timeout` optional argument
		if !querybuilder.IsZeroValue(opts[i].Timeout) {
			q = q.Arg("timeout", opts[i].Timeout)
		}
	}
	q = q.Arg("resource", resource)
	q = q.Arg("name", name)

	return q.Execute(ctx)
}

// Cluster represents a running Kubernetes cluster: a single
// control-plane node plus N worker nodes, each backed by a privileged
// kindest/node Dagger Service. Holds references to every service so
// callers can bind them into their own containers or open a client-go
// Client against them.
type KubernetesCluster struct { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)
	query *querybuilder.Selection

	apiserverEndpoint *string
	healthzResponse   *string
	id                *KubernetesClusterID
	stop              *Void
}

func (r *KubernetesCluster) WithGraphQLQuery(q *querybuilder.Selection) *KubernetesCluster {
	return &KubernetesCluster{
		query: q,
	}
}

// APIServerEndpoint returns the host:port pair the cluster's
// kube-apiserver advertises on its external HTTPS listener (port
// 6443). The hostname is a per-cluster Dagger WithHostname alias,
// reachable from any container in the same engine session.
func (r *KubernetesCluster) ApiserverEndpoint(ctx context.Context) (string, error) { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:201:1)
	if r.apiserverEndpoint != nil {
		return *r.apiserverEndpoint, nil
	}
	q := r.query.Select("apiserverEndpoint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Client returns a client-go Client that targets this cluster. Starts
// the control-plane service if it isn't already running so the client's
// first API call doesn't race with cluster readiness.
func (r *KubernetesCluster) Client() *KubernetesClient { // kubernetes (../../../../../daggerverse/kubernetes/client.go:52:1)
	q := r.query.Select("client")

	return &KubernetesClient{
		query: q,
	}
}

// HealthzResponse curls https://<APIServerEndpoint>/healthz from a
// sidecar container bound to the control-plane service, and returns
// the response body. Useful as an end-to-end probe that the cluster's
// kube-apiserver is up, the WithHostname-registered alias resolves
// in-session, and the auto-generated apiserver cert is valid for the
// hostname (added to certSANs at kubeadm init).
//
// Returns the body (expected `ok`) on a 2xx; surfaces curl's error on
// transport failure or non-2xx status.
//
// Lives inside the kubernetes module because Dagger Service handles
// returned through GraphQL boundaries do not preserve the binding
// state needed for cross-module WithServiceBinding — the binding
// must be applied in the same chain that produces the exec.
func (r *KubernetesCluster) HealthzResponse(ctx context.Context) (string, error) { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:224:1)
	if r.healthzResponse != nil {
		return *r.healthzResponse, nil
	}
	q := r.query.Select("healthzResponse")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this KubernetesCluster.
func (r *KubernetesCluster) ID(ctx context.Context) (KubernetesClusterID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response KubernetesClusterID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *KubernetesCluster) XXX_GraphQLType() string {
	return "KubernetesCluster"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *KubernetesCluster) XXX_GraphQLIDType() string {
	return "KubernetesClusterID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *KubernetesCluster) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *KubernetesCluster) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *KubernetesCluster) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadKubernetesClusterFromID(KubernetesClusterID(id))
	return nil
}

// Kubeconfig returns the admin kubeconfig for this cluster as a
// *dagger.File. The `server:` URL is rewritten to point at the
// control-plane's WithHostname alias on port 6443 — the address
// reachable from any other container in the same engine session.
//
// kubeadm originally writes the kubeconfig with
// `server: https://<container-internal-ip>:6443`, which is reachable
// only from inside the control-plane container. Rewriting to the
// WithHostname alias makes the file usable by sidecar consumers and
// by the kubernetes module runtime alike.
//
// The file is fetched by curl'ing `http://<host>:9999/admin.conf`
// from a sidecar container — the control-plane's bootstrap unit
// publishes /etc/kubernetes/ via python3's builtin http.server so
// kubeadm's output is accessible without docker-exec (Dagger has no
// cross-service exec primitive). The fetched bytes are YAML-parsed,
// the server URL is replaced, and the result is written to the
// module-runtime workspace and returned as a *dagger.File.
func (r *KubernetesCluster) Kubeconfig() *File { // kubernetes (../../../../../daggerverse/kubernetes/kubeconfig.go:38:1)
	q := r.query.Select("kubeconfig")

	return &File{
		query: q,
	}
}

// Stop tears down every service container backing this cluster (the
// control-plane plus every worker). SIGKILL skips graceful shutdown
// — kubeadm drain timeouts a torn-down test cluster doesn't need.
func (r *KubernetesCluster) Stop(ctx context.Context) error { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:243:1)
	if r.stop != nil {
		return nil
	}
	q := r.query.Select("stop")

	return q.Execute(ctx)
}

// Kubernetes is the root namespace for every exported function in
// this module. All cluster constructors and the remote-client factory
// hang off *Kubernetes so the generated Dagger SDK surfaces them
// under `dag.Kubernetes().<Func>(...)`.
func (r *Query) Kubernetes() *Kubernetes { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	q := r.query.Select("kubernetes")

	return &Kubernetes{
		query: q,
	}
}

// Load a KubernetesClient from its ID.
func (r *Query) LoadKubernetesClientFromID(id KubernetesClientID) *KubernetesClient { // kubernetes (../../../../../daggerverse/kubernetes/client.go:31:6)
	q := r.query.Select("loadKubernetesClientFromID")
	q = q.Arg("id", id)

	return &KubernetesClient{
		query: q,
	}
}

// Load a KubernetesCluster from its ID.
func (r *Query) LoadKubernetesClusterFromID(id KubernetesClusterID) *KubernetesCluster { // kubernetes (../../../../../daggerverse/kubernetes/cluster.go:36:6)
	q := r.query.Select("loadKubernetesClusterFromID")
	q = q.Arg("id", id)

	return &KubernetesCluster{
		query: q,
	}
}

// Load a Kubernetes from its ID.
func (r *Query) LoadKubernetesFromID(id KubernetesID) *Kubernetes { // kubernetes (../../../../../daggerverse/kubernetes/main.go:30:6)
	q := r.query.Select("loadKubernetesFromID")
	q = q.Arg("id", id)

	return &Kubernetes{
		query: q,
	}
}
